.gitignore
Makefile
README.md
bin/release
tools/Dockerfile
tools/build.sh
weave

We package ethtool and conntrack into a `weavetools` image and run that as a short-lived container with `--privileged` and `--net=host` (or, in one case `--net=container:<id>`).
We use a plain ubuntu container as a build environment, so a) we don't require onerous tooling on the build host, and b) don't pollute the build host with build artefacts. The latter arise because building conntrack requires 'global' installation of its dependencies.
Closes #101.

eliminate dependency on ethtool and conntrack on host

---

common/testing_utils.go
nameserver/mdns_client.go
nameserver/mdns_client_test.go
nameserver/mdns_lookup.go
nameserver/mdns_server.go
nameserver/mdns_server_test.go
nameserver/server.go
nameserver/server_test.go
nameserver/zone.go
nameserver/zone_test.go
weavedns/main.go

* The Zone interface is split in two, DB operations and another interface Lookup
* The (regular) handlers are given a list of Lookup implementations to try in order
* The mDNSy server uses a dns.ServeMux to serve only the .weave.local and .in-addr.arpa domains
* The mDNSy server now answers PTR queries if it can

Refactor, Reimplement, Repair (m)DNS

---

nameserver/mdns_client.go
router/connection.go
router/connection_maker.go
router/consts.go
router/local_peer.go

As mentioned at https://github.com/zettio/weave/pull/313/files#r22720060

Remove repeated 'iota' in const lists, since Go knows what you mean

---

weave
weavedns/Dockerfile
weaver/Dockerfile

- ensure that we have the weavetools image downloaded before entering any time-critical sections, in particular post-container-startup network configuration
- in the weave router and dns containers, wait for longer for the ethwe interface to become available
Fixes #321.

cope with weavetools delays

---

Makefile
nameserver/http_test.go
nameserver/mdns_client_test.go
nameserver/mdns_server_test.go
nameserver/zone_test.go
testing/util.go

So as not to pollute command-line flags with test.* options.
It appears that importing "testing" (from stdlib) will add flags. To
avoid this, we need code to not depend on testing. But, since
testing_utils was previously in the same package as the rest of the
code, it dragged testing in.
Renaming testing_util.go to e.g., nameserver/util_for_test.go might be enough to
avoid it being compiled with the regular code. We may want it to be
available to tests for other packages -- after all it is utilities for
testing -- so it goes in its own package.

Move testing utils to its own package

---

nameserver/http.go
nameserver/mdns_lookup.go
nameserver/mdns_server.go
nameserver/mdns_server_test.go
nameserver/server.go
nameserver/updater.go
nameserver/zone.go

* Put prefixes (including msg IDs) in front of log messages to
distinguish them
* Failed lookups get logged under Info as per issue #311
* More accurate messages as per issue #311 
(and switch debug logging on during tests, just to be helpful)

Reform logging in weaveDNS

---

router/connection.go
router/connection_maker.go
router/local_peer.go
router/router.go
router/types.go

1) log more lifecycle events
- acceptance
- handshake completion
- added & removed (from our connection map)
The latter is a bit verbose but may help us track down the cause for
#341. If we had different log levels, which is not something I am
going to introduce here, then this would fall in the 'debug' category.
2) better error logging
- log error as part of "shutting down" log event rather than separately
- indicate "blocked UDP connectivity" as a possible cause when
getting a timeout on a not-fully-established connection.
The rationale for the latter is that inbound connections get
marked as established when first receiving a heartbeat frame over
UDP, which are the only frames that get transmitted prior to the
connection being fully established. Note that outbound
connections get …

improve connection logging

---

nameserver/http_test.go
nameserver/mdns_client_test.go
nameserver/mdns_lookup.go
nameserver/mdns_server.go
nameserver/server.go
nameserver/server_test.go
nameserver/zone.go
nameserver/zone_test.go
test/300_fallback_dns_test.sh

weaveDNS now uses the servers in /etc/resolv.conf as fallbacks. It will ask the fallback server(s) if the query is for a name not under its authority; i.e., in .weave.local. It doesn't filter by query type, so as the smoke test shows, it will work for other kinds of question e.g., MX records.
As part of this, I've changed the names of the Lookup methods to get rid of the needless and inaccurate "Local" qualifier. Another factoring would be to have one method, pass through the whole question (or at least both the type and the name), and let the zone or whatever figure out how to answer it; but this will do for now.

Act as a proxy for non-weave DNS queries

---

test/200_dns_test.sh
test/210_dns_multicast_test.sh

It's more precise to use dig rather than ping. The stock ubuntu image
doesn't come with dig (in package dnsutils), but luckily Aanand made
an image which is exactly ubuntu+dnsutils.

Add tests for resolving names across hosts

---

docs/architecture.txt
router/connection.go
router/consts.go
router/peers.go
router/router.go
router/types.go

Currently we cannot distinguish bi-directional and uni-directional connectivity between peers. This is what currently happens for a connection from A to B...
A: remoteUDPAddr=X
B: remoteUDPAddr=nil
A: send fast heartbeats over UDP
B: receive heartbeat; remoteUDPAddr is nil
remoteUDPAddr=Y
send 'established' over TCP
established=true
send slow heartbeats over UDP
A: receive 'established' over TCP
established=true
send slow heartbeats over UDP
If udp packets make it through from A to B but not B to A then both ends mark the connection as 'established'. Conversely, if udp packets make it through from B to A but not A to B then the connection is not marked as 'established' at either end.
In the new scheme, this is what happens...
A: receivedHeartbeat=false, remoteUDPAddr=X
B: …

better handling of undirectional udp connectivity

---

router/connection.go
router/consts.go
router/crypto.go
router/local_peer.go
router/protocol.go
router/router.go

- Instead of representing protocol messages as []byte, represent them as instances of a ProtocolMsg struct, containing a ProtocolTag identifying the message type, and a []byte for the payload.
- Introduce ProtocolSender interface, containing a SendProtocolMsg method. This is implemented by LocalConnection and LocalPeer, replacing the former SendTCP/BroadcastTCP methods. In the former case the ProtocolMsg is sent to the peer at the other end of the connection, in the latter case it is sent to all peers the local peer is connected to.

better abstraction for protocol messages

---

weave

This will should allow one to use an unmodified version of the script to create the bridge so it can be used with `docker --bridge=weave`, if required.

Add create-bridge command

---

router/connection.go
router/consts.go
router/gossip.go
router/gossip_test.go
router/local_peer.go
router/protocol.go
router/router.go
router/utils.go
site/how-it-works.md

The old ProtocolUpdate and FetchAll requests disappear, replaced with a more generic Gossip implementation.
In addition to the usual send-to-some mode, this Gossip layer implements Broadcast-to-all and Unicast requests, although they are not used to communicate topology.

Gossip layer to communicate topology between peers

---

router/connection.go
router/consts.go

Prior to the introduction of gossip, a tcp connection would not see
regular communication until it had been marked as 'established',
because the topology communication scheme would periodically send
'FetchAll' only after that. So in the absence of udp connectivity we'd
time out. The timeout could of course occur for other reasons, namely
disrupted tcp connectivity, but the combination of a timeout and 'not
established' pointed to a lack of udp connectivity as a likely
cause. So that's what we checked for.
In the new gossip-based topology communication, however, gossip (of
anything, not just topology) occurs as soon as we have tcp
connectivity. Therefore we will no longer encounter a timeout when
just udp connectivity is disrupted. Which makes our check invalid.
So instead we introduce a …

tear down connections that have no (initial) udp connectivity

---

weave

Those two commands are used in the pre-docker phase when you setup your
weave bridge using create-bridge, e.g. inside /etc/network/interfaces.
This extends #357.

Also avoid calling ethtool in expose and hide

---

router/connection.go
router/gossip_test.go
router/local_peer.go
router/mocks_test.go
router/peer.go
router/peers.go
router/protocol.go
router/router.go
site/how-it-works.md

Topology gossip can be received on a connection before that connection has been marked as 'established'. If we do not include unestablished connections in topology gossip, then parts of the topology can be removed by gc, since they are deemed unreachable, which can cause subsequent incremental topology gossips to be rejected due to them containing references to peers that have been removed by the gc.
Including unestablished connections in topology gossip requires:
- removing the check for 'established' connections in the encoding of peers for topology gossip,
- adding the 'established' flag to the internal representation of remote connections,
- adding the 'established' flag to to encoding of connections in topology gossip,
- only considering 'established' connections in route …

prevent premature peer topology gc

---

nameserver/server.go
nameserver/server_test.go

Addresses #360.  A complete fix would involve implementing TCP fallback, but raising the limit from 512 bytes to 1400 should accommodate a large fraction of real-world responses.
The 'unit' test makes the assumption that type ANY on cisco.com will give a large response.  Empirically you also have to add the EDNS0 record in order to get a long response - experiment with commands like `dig ANY cisco.com. +qr +noedns`

Use a larger buffer than the default, so that more queries will succeed

---

Makefile

This will make the test print code coverage report once done in each directory

Enable code coverage reports

---

router/connection.go

Addresses a source of deadlock in weave arising from LocalConnection's habit of exiting its queryLoop() routine while callers are trying to talk to it.  After there are 16 messages in the channel, the sends block, and some of them can be from places where locks are held.
This PR introduces a second 'finished' channel, which is closed on exit from queryLoop().  All callers select on the 'finished' channel as well as the 'query' channel, and since a closed channel is always ready to read, they do not block.
This issue was found while investigating #411, but without stack traces I cannot be absolutely certain that this is the cause of that incident.

Add 'finished' chan to stop callers blocking on closed connection

---

router/json.go
weaver/main.go

Json generation is done by creating dummy structs and arrays that match the format we want, copying the information into them, then getting Go's standard json encoder to do the work.
All the implementation is pulled into one file json.go rather than scattering it across all the relevant implementations; at time of writing this seems easier to grasp.

Obtain status info in JSON format

---

router/gossip.go

Copy connections so we don't hold a lock fixes #418.  
This problem was discovered while researching #411.

Avoid a deadlock

---

router/connection.go
router/consts.go

Addresses #373 - detect udp connectivity breakage.
Once a connection moves to the established state indicating that the remote peer has received one of our heartbeats a timer is started. If we do not receive a UDP heartbeat from the remote peer within this time (default is three times the slow heartbeat interval) the connection is terminated:
connection shutting down due to error: timed out waiting for UDP heartbeat
At this point the existing connection resumption mechanism takes over. In normal operation, the timer is reset each time we receive a heartbeat.
Implementation notes:
* It would be possible to merge `establishedTimeout` and `heartbeatTimeout` into a single timer; we would simply adjust duration and error messages depending on `conn.established` state.
* Alternatively, the …

Tear down connections on prolonged loss of UDP heartbeat

---

router/gossip_test.go
router/handshake.go
router/local_peer.go
router/mocks_test.go
router/peer.go
router/peers.go
router/peers_test.go
router/protocol.go
router/router.go
site/how-it-works.md
site/troubleshooting.md
weave
weaver/main.go

Implement `-hostname` flag to weave router for inclusion in `weave status`:
root@weave01:~# weave status
weave router git-170724472555
Encryption off
Our name is 7a:85:0d:3f:4b:8b (weave01)
Sniffing traffic on &{25 65535 ethwe 26:47:3f:b1:9f:35 up|broadcast|multicast}
MACs:
e6:eb:3d:c2:f2:c0 -> 7a:85:0d:3f:4b:8b (2015-02-19 14:36:43.698599704 +0000 UTC)
ea:9b:f6:9a:a8:94 -> 7a:ee:54:05:6d:19 (2015-02-19 14:36:45.467878022 +0000 UTC)
02:c5:dc:fa:4f:19 -> 7a:c4:7d:e3:0f:9b (2015-02-19 14:36:50.594692416 +0000 UTC)
Peers:
Peer 7a:c4:7d:e3:0f:9b (weave03) (v37) (UID 12377675045837118970)
-> 7a:ee:54:05:6d:19 (weave02) [178.62.77.81:6783]
-> 7a:85:0d:3f:4b:8b (weave01) [178.62.57.35:6783]
Peer 7a:85:0d:3f:4b:8b (weave01) (v8) (UID 8327482320931219319)
-> 7a:c4:7d:e3:0f:9b (weave03) …

369 name weave peers

---

router/connection.go

As noted in #415, the Actor channels into LocalPeer and a Connection can get locked in a deadly embrace.
But, we don't need to use the Actor mechanism for outgoing ProtocolMsg sends; they don't need to be serialised with the state of the Connection itself, so by doing the send directly we avoid this problem.
This then opens up a related problem that the Shutdown() arising from an error when sending can get blocked on a full channel, so we move all Shutdown() operations to their own goroutines.
Closes #415.  Possibly related to #411.

Remove deadlock in sending protocol messages

---

router/crypto.go
router/ethernet_decoder.go
router/local_peer.go
router/router.go

419 broadcast frametoobigerror

---

router/connection.go
router/connection_maker.go
router/gossip_test.go
router/local_peer.go
router/mocks_test.go
router/peers.go
router/protocol.go
router/router.go

Add an 'outbound' field on each connection, and only attempt new connections to the remote side of outbound connections.
This fixes #448, which is particularly important as you raise the connection limit per #426.
NOTE: This changes the wire protocol, hence the protocol version number is incremented.

Avoid many pointless connection attempts

---

weave

441 slow ARP fixes

---

router/local_peer.go

Weave sends all gossip down new connections. We do this so that new
peers learn about all gossip'ed information quickly, thus enabling
them to process subsequent incremental updates. In particular, for
topology gossip it ensures that the remote peer learns about all other
peers. This ensures that the incremental update, which is sent as a
result of the new connection getting established and which may
reference a number of other peers, can be processed.
So the intent really is to send all gossip to new peers. But what we
actually do is send it down every new connection. Not every new
connection is from a new peer. In fact most connections aren't. Hence
the current approach is wasteful.
To fix this we need a conservative detection of new peers, i.e. it is
preferable to have false positives. …

send all gossip to new peers only

---

nameserver/http.go
nameserver/http_test.go
nameserver/server.go
nameserver/zone.go
site/troubleshooting.md
weave
weavedns/README.md
weavedns/main.go

Addresses #237 - Add weavedns status to `weave status`.
Sample output:
````
~/weave$ sudo ./weave status
weave router git-9eeec2fa4835
Encryption off
Our name is 7a:6e:b1:a9:28:4d (ubuntu-14)
Sniffing traffic on &{12 65535 ethwe 6e:54:91:56:f2:9a up|broadcast|multicast}
MACs:
Peers:
Peer 7a:6e:b1:a9:28:4d (ubuntu-14) (v0) (UID 17345352114913090227)
Routes:
unicast:
7a:6e:b1:a9:28:4d -> 00:00:00:00:00:00
broadcast:
7a:6e:b1:a9:28:4d -> []
Reconnects:
weave DNS git-6f57774d1516
Local domain weave.local.
Listen address :53
mDNS interface &{112 65535 ethwe ea:43:db:f3:c3:3d up|broadcast|multicast}
Fallback DNS config &{[10.0.2.3] [] 53 1 5 2}
Zone database:
2aca5f21b82b1898f7e9bb6919b77a56999e6c4b7c292f3f88c8cec3a7db72b7 10.2.1.4 waff.weave.local. …
```

Include weave dns information in `weave status`

---

nameserver/server_test.go

Occasionally the test servers overlap and the test will fail with "address already in use".

Increment the server port for each test

---

router/gossip.go
router/gossip_test.go
router/local_peer.go
router/peers.go
router/peers_test.go
router/router.go

Introduce an intermediary - GossipSender - between GossipChannel and
Connection. This accumulates gossip data (now represented by the new
GossipData interface) from the former until it can be passed onto the
latter, allowing the former to proceed when the latter may be blocked
on i/o.
This
1) prevents deadlocks that arise from cycles in the communication
topology
2) improves performance by allowing GossipChannel and its calling code
to proceed when connection i/o is blocked
3) improves performance by accumulating GossipData - the accumulated
data often is considerably more compact than the sum of all the
accumulated bits, and it is transmitted in a single communication
event.
In order to support accumulation, the GossipData interface has a Merge
method. Furthermore, encoding is deferred …

accumulate gossip data until it can be sent

---

nameserver/cache.go
nameserver/cache_test.go
nameserver/dns.go
nameserver/mdns_server.go
nameserver/server.go
nameserver/server_test.go
testing/util.go
weavedns/main.go

#225 : this pull request implements a caching mechanism in the DNS server. The cache is used for saving positive and negative replies obtained by the local discovery system as well as by the recursive resolver.
Replies found in the cache are modified before being returned to clients by adjusting the remaining TTL and  shuffling answers (implementing a basic load balancing mechanism as a side effect, a first step for #226).

weave-225: [dns] caching (1/3)

---

nameserver/mdns_client.go
router/connection.go
router/connection_maker.go
router/gossip_test.go
router/local_peer.go
router/routes.go
router/utils.go

Instead of actor client methods passing data to the server via the actor's channel, and the server in turn invoking server methods with that data, we get the client methods to pass a closure of the server method via the actor's channel. This reduces boilerplate a fair bit.
Closes #475.

simplify actors

---

.travis.yml
Makefile
README.md

- Add .travis.yml
- Add target to makefile which doesn't use docker (can't use docker on travis right now)
- Add build image to readme.
NB sudo: false is to get their faster, docker based build.

Setup Travis CI for Weave.  

---

.gitignore
.travis.yml
Makefile
README.md

- Update said profile to coveralls.io
- Add badge to readme

Move away from recursive go test, as it cannot output a merged coverage profile.

---

weave

Factor the wait-for-status part out of `populate_dns()`, so we can call it at the end of `weave launch`
Fixes #500

Wait for the 'status' http call to return something after 'weave launch'

---

weave

The difference is that `docker stop` sends `SIGTERM` first, whereas `docker kill` just sends `SIGKILL`, and the latter cannot be caught by a process.  Although we don't presently know of anything that needs to shut down nicely, it seems better to use the variant that permits it.

Use docker stop instead of docker kill

---

router/gossip.go
router/local_peer.go
router/peers.go
router/protocol.go
router/router.go
router/routes.go

Transmit topology updates via gossip broadcast instead of the "send to all neighbours" periodic gossip mechanism.
This requires the following changes:
1. make `Gossip.GossipBroadcast` operate on `GossipData`. We need this so we can perform accumulation (see below). It also gives the opportunity to update data as we relay it, which is an optimisation.
2. add "representation of received update" to return of `Peers.ApplyUpdate`. We need this so we can perform the aforementioned data updating for when relaying topology gossip.
3. use `GossipSender`s for `GossipBroadcast`. Depends on 1. We need this so `GossipBroadcast` becomes properly async, which is required if we want to use it for topology gossip - in order to avoid deadlocks w/o spawning a unbounded number of goroutines. It is also a …

lower topology update gossip complexity

---

router/connection.go

We were invoking AddConnection in a separate goroutine, and this could
result in RemoveConnection getting invoked first, resulting in bogus
entries in our connection map, which would effectively prevent
connectivity to the other peer until the stale entry got removed
through a lost tie break. And if, per chance, the remote end ran into
exactly the same race condition, then connectivity between that peer
and ourself was broken permanently.
Hitting this race condition required a combination of a) no UDP
heartbeat being received for HeartbeatTimeout(30s) - this causes the
actorLoop to terminate and RemoveConnection to be invoked, and b) the
AddConnection invocation getting delayed for at least that long.
Fixes #529.

eliminate AddConnection/RemoveConnection race

---

router/connection.go
router/consts.go
router/gossip.go
router/protocol.go
router/routes.go

Instead of gossiping to all neighbours, we select up to log(n_peers) neighbours at random, based on a probability distribution that takes into account the topology, i.e. favours neighbours at the end of "bottleneck" links. The distribution is determined from the unicast topology.
Closes #517.

lower topology periodic gossip complexity

---

router/connection_maker.go
router/gossip_test.go
router/local_peer.go
router/router.go
router/udp_sender.go
router/utils.go
weaver/main.go

This commit adds two command line options, intended to allow multiple
instances of weave to run without container separation between them.
* -port=PORT makes weave bind to port PORT (an integer). Without the
option, the default value (6783) is used.
* -bindjsonto=BINDSTRING makes weave bind its control interface to
a different port. For instance "127.0.0.1:6784" can be used to
bind to localhost only. ":6784" is the default. An empty string
can be used to disable the control interface.
Signed-off-by: Alex Bligh <alex@alex.org.uk>

Add options to set ports on weaver command line

---

weaver/main.go

This prevents a nil pointer dereference if (e.g.) weaver is
invoked with no arguments.
Signed-off-by: Alex Bligh <alex@alex.org.uk>
Before this change:
$ weaver/weaver
weave 2015/04/10 14:54:39.431562 Command line options: map[]
weave 2015/04/10 14:54:39.431709 Command line peers: []
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4034df]
goroutine 1 [running]:
runtime.panic(0x82dc60, 0xfc1a68)
/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.main()
/home/amb/weave/weave/weaver/main.go:95 +0x12df
goroutine 3 [syscall]:
os/signal.loop()
/usr/lib/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
After this change:
$ weaver/weaver
weave 2015/04/10 14:59:11.852728 Command line options: map[]
weave 2015/04/10 …

Error if neither -iface or -name is specified

---

site/troubleshooting.md
weave

So, `weave ps` will still show you all containers, but `weave ps mycontainer` will just show you that one.
If you give a nonexistent name you get no output, which is consistent with Unix `ps`.

Allow container names to be supplied to `weave ps`

---

router/connection_maker.go
weaver/main.go

rather than post name resolution. This way we can forget them as given
even when name resolution has changed or fails.
Fixes #549.

remember user-supplied peer addresses as given

---

nameserver/cache.go
nameserver/cache_test.go
nameserver/server.go

Fixes zettio/weave#494 by using a different lookups set depending on the value stored in the cache.
PS: these changes have been tested with this [new WeaveDNS test tool](https://github.com/inercia/weave-dns-tests).

Fix for negative TTLs in WeaveDNS

---

nameserver/cache.go
nameserver/cache_test.go
nameserver/server.go
weavedns/main.go

Changes in this PR:
* do not modify the TTL in the reply stored when `Get`ting from the cache
* set all responses obtained with mDNS as authoritative
* minor improvements in the logs
Note: this PR depends on #501

Fix in WeaveDNS: do not modify cache when getting a reply

---

router/connection.go
router/connection_maker.go
site/troubleshooting.md

So that an administrator can see the messages with `weave status`

Allow ConnectionMaker to report the reason the connection broke

---

weaver/main.go

This eliminates a few variables, and the naming awkardness where we
have corresponding but distinct flag and router config variables.

Pull forward the declaration of the RouterConfig in main()

---

router/connection.go
router/connection_maker.go
router/peer.go
site/troubleshooting.md

in addition to the peer name/nick
This is handy for debugging, especially in situations when there are multiple connections in flight to the same peer.

always include the remote address in connection log entries

---

router/connection_maker.go
router/local_peer.go
router/router.go

If a peer was specified on the command line w/o a port, then do not connect to it if we have inbound connections from that IP.
This eliminates unnecessary (and ultimately failing0 connection attempts in the common scenario of several peers having been told about each other on their command lines.
Closes #478.

more discriminate connectivity

---

site/troubleshooting.md
weave

Fixes #385. Sample output:
````
$ sudo ./weave ps
e8f979801cd7 ae:50:e8:95:f6:03 10.0.0.1/24
2e25b47b08fe 6a:95:45:20:14:56
weave 7a:c4:8b:a1:e6:ad 10.0.0.2/24
````
The final entry uses `$BRIDGE` in place of the container name, for lack of anything better - thoughts @rade @bboreham ?

Include weave exposed addresses in ps output

---

README.md
site/features.md
weave

make weave port configurable via WEAVE_PORT

---

site/features.md
weave

Fix #375:
````
vagrant@ubuntu-14:~/weave$ ./weave expose 10.1.1.1/24 -h myservice.weave.local
vagrant@ubuntu-14:~/weave$ ./weave status
weave router git-59ae50eb4ef9
Encryption off
Our name is 7a:c5:c4:15:be:33(ubuntu-14)
Sniffing traffic on &{10 65535 ethwe 16:3d:0b:8a:66:e4 up|broadcast|multicast}
MACs:
7a:c5:c4:15:be:33 -> 7a:c5:c4:15:be:33(ubuntu-14) (2015-04-16 09:23:30.45427506 +0000 UTC)
6a:0a:da:89:30:de -> 7a:c5:c4:15:be:33(ubuntu-14) (2015-04-16 09:22:13.804277587 +0000 UTC)
16:3d:0b:8a:66:e4 -> 7a:c5:c4:15:be:33(ubuntu-14) (2015-04-16 09:22:03.786283726 +0000 UTC)
32:dd:63:79:54:df -> 7a:c5:c4:15:be:33(ubuntu-14) (2015-04-16 09:22:04.374157935 +0000 UTC)
Peers:
Peer 7a:c5:c4:15:be:33(ubuntu-14) (v0) (UID 5547860031843093274)
Routes:
unicast:
7a:c5:c4:15:be:33 -> …
```

Add optional hostname argument to weave expose

---

weave

Took out one `echo`, one `grep` and one subshell.

Simplify address parsing for populate_dns in weave script

---

weave

Fixes #568:
````
vagrant@ubuntu-14:~/weave$ ./weave run -ti ubuntu
Invalid CIDR: -ti
CIDR must of be of form <ip_address>/<routing_prefix_length>, e.g. 10.2.1.1/24
vagrant@ubuntu-14:~/weave$ ./weave start foo bar
Invalid CIDR: foo
CIDR must of be of form <ip_address>/<routing_prefix_length>, e.g. 10.2.1.1/24
vagrant@ubuntu-14:~/weave$ ./weave attach foo bar
Invalid CIDR: foo
CIDR must of be of form <ip_address>/<routing_prefix_length>, e.g. 10.2.1.1/24
vagrant@ubuntu-14:~/weave$ ./weave detach foo bar
Invalid CIDR: foo
CIDR must of be of form <ip_address>/<routing_prefix_length>, e.g. 10.2.1.1/24
vagrant@ubuntu-14:~/weave$ ./weave expose foo
Invalid CIDR: foo
CIDR must of be of form <ip_address>/<routing_prefix_length>, e.g. 10.2.1.1/24
vagrant@ubuntu-14:~/weave$ ./weave hide foo
Invalid …
```

Fix multi cidr error messages

---

router/connection.go
router/forwarder.go

Much of the state and code associated with Forwarder only applied in the
DF case.

Separate Forwarder and ForwarderDF

---

weavedns/README.md
weavedns/main.go

Documented the local domain argument in WeaveDNS
Renamed the command line argument for override the local domain.
Fixes #573

Added some documentation for the local domain argument

---

Vagrantfile
test/Vagrantfile
weave
weaveexec/Dockerfile

Fixes #458. All smoke tests pass (`400_weave_local_test.sh` necessitated updating the Vagrantfiles to Ubuntu 14.10) but nevertheless quite invasive - suggest merging after 0.10.0?

Replace `ip netns exec` with `nsenter`

---

test/100_cross_hosts_test.sh
test/110_encryption_test.sh
test/200_dns_test.sh
test/210_dns_multicast_test.sh
test/220_dns_custom_test.sh
test/300_fallback_dns_test.sh
test/400_weave_local_test.sh
test/config.sh

so we don't repeat the remote docker invocation command (complete with hard-coded port) over and over again.

add exec_on test helper

---

nameserver/addrs.go
nameserver/addrs_test.go
nameserver/cache.go
nameserver/cache_test.go
nameserver/dns.go
nameserver/http_test.go
nameserver/mdns_client.go
nameserver/mdns_client_test.go
nameserver/mdns_lookup.go
nameserver/mdns_server.go
nameserver/mdns_server_test.go
nameserver/mocks_test.go
nameserver/server.go
nameserver/server_test.go
nameserver/zone.go
nameserver/zone_test.go
weavedns/main.go

This pull request is the stepping stone for full support of multiple responses in WeaveDNS. It focuses in the mDNS client and server, where it provides
* support for "insistent" `Lookups` (maybe not the best name): mDNS queries that try to obtain as many responses as possible for up to 500ms (and, in consequence, they block for that period of time). This will be used in the next PR by a "updater" process that will _refresh_ the ZoneDb information by sending periodic queries to peers...
* support for multiple responses from all the `Lookup*()` methods
* a common `ZoneRecord` interface for many structs that contain names and IPs (used in `Lookup` methods, but also in the future database records)
* support for multiple records when building packets with `make*()` methods
* improved unit …

Support for multiple responses in mDNS

---

test/100_cross_hosts_test.sh
test/110_encryption_test.sh
test/200_dns_test.sh
test/210_dns_multicast_test.sh
test/220_dns_custom_test.sh
test/230_dns_unqualified_test.sh
test/300_fallback_dns_test.sh
test/400_weave_local_test.sh
test/500_weave_multi_cidr_test.sh
test/config.sh

Factor out test fixture teardown

---

nameserver/addrs.go
nameserver/addrs_test.go
nameserver/cache.go
nameserver/cache_test.go
nameserver/mdns_client.go
nameserver/mdns_client_test.go
nameserver/mdns_server.go
nameserver/mdns_server_test.go
nameserver/mocks_test.go
nameserver/server.go
nameserver/server_test.go
nameserver/zone.go

Added an external clock provider in the cache, specially useful for unit testing. We do not need the _"now"_ parameter in the cache anymore...
Added a TTL for the zone database records.
[Stringer](https://golang.org/pkg/fmt/#Stringer)'ify some structs.
Improved Zone database mock.

External clock provider for the cache

---

weave

Fixes #596.
````
vagrant@vagrant-ubuntu-utopic-64:~/weave$ ./weave launch
a4eba9d1b0a3dd0fd12ac3ce032387e1528b51641f286cf446182168c7983625
vagrant@vagrant-ubuntu-utopic-64:~/weave$ C=$(docker run -d -ti ubuntu)
vagrant@vagrant-ubuntu-utopic-64:~/weave$ ./weave detach 10.2.0.1/24 $C
vagrant@vagrant-ubuntu-utopic-64:~/weave$ echo $?
0
vagrant@vagrant-ubuntu-utopic-64:~/weave$ sudo ./weave --local detach 10.2.0.1/24 $C
vagrant@vagrant-ubuntu-utopic-64:~/weave$ echo $?
0
````

Detach of unattached container succeeds silently

---

weave

Fixes #597.
````
$ ./weave version
weave script (unreleased version)
weave router git-cc144eff0b84
Unable to find weaveworks/weavedns:latest image.
weave exec (unreleased version)
````

`weave version` continues after missing image

---

router/connection.go
router/consts.go
router/crypto.go
router/forwarder.go
router/handshake.go
router/protocol.go
site/how-it-works.md

replace random nonces with message sequence numbers

---

router/pcap.go

If gopacket is compiled against an older pcap.h that doesn't have pcap_set_immediate_mode, it supplies a dummy definition that  always returns PCAP_ERROR.  That becomes "Generic error", which is not very helpful.  The real pcap_set_set_immediate never returns PCAP_ERROR, so this turns it into a more informative message.
Fixes #623

Improve the "Generic error" message when compiled against old libpcap

---

test/130_expose_test.sh
weave

prevent interference of expose in other subnets

---

router/peers.go
router/protocol.go

Partially addresses #519 by merging the first two layers of gob.

Use same gob encoder/decoder for peers and peer connections

---

common/signals.go
router/router.go
weavedns/main.go
weaver/main.go

Both the router and the DNS server use a similar signals handler, so this PR implements a common handler for them. The DNS server and the router implement methods like Stop() and Status() now, called from the handler when some specific signals are received...

Use a common signals handler

---

nameserver/dns.go
nameserver/server.go
nameserver/server_test.go
test/200_dns_test.sh
test/config.sh

Fixes #588 by returning NOTIMP for some unimplemented query types, NXDOMAIN otherwise

return NXDOMAIN instead of NOTIMP

---

test/240_dns_add_name_test.sh
weave
weavedns/README.md

Added two new commands `dns-add` and `dns-remove` that call the `tell_dns` function method to store addresses and optionally a specific FQDN for a container ID.
This is useful for circumstances where containers may be configured with IP addresses outside weave, perhaps by some contaienr orchestration service or using a different SDN, but those addresses should still be resolvable and usable by the weaveDNS.

add `weave dns-add/remove` commands

---

circle.yml
test/gce.sh

- Don't need gsutil on circle
- Use a prebuild weave-build image and cache it locally.
- Name VMs after change I'm building, so I can do multiple concurrently
- Don't build gh-pages branch

Improvements to circle ci integration

---

site/build-and-publish.sh

Use rsync instead of cp to avoid uploading site to a subdirectory (when the directory already exists).

Fixes post #612

---

router/connection.go
router/connection_maker.go
router/gossip_test.go
router/handshake.go
router/json.go
router/local_peer.go
router/mocks_test.go
router/peer.go
router/peers.go
router/peers_test.go
router/router.go
router/routes.go

The principal idea here is to maintain just a single lock - on Peers - for the entire topology information, instead of individual locks for every peer. That makes sense since there are only two sources of updates to this information: a) topology updates received from other peers, the processing of which requires the Peers lock anyway, and b) reference counting as part of local connection lifecycle, which used to *sometimes* require the Peers lock, and now always does. Furthermore, there are very few consumers of the topology information - essentially just route calculation, gossip, connection management and diagnostics.
The exception is LocalPeer, the state of which changes based on local connection lifecycle, and is consumed in quite a few places. We therefore maintain a separate lock …

eliminate route calculcation deadlock

---

site/features.md
site/weavedns.md

- add ToC and anchors for all headings
- move docker bridge settings into "How it works" - it's a rarely used
feature
- highlight a bunch of features, extracting them from obscurely titled
sub-sections of "manual usage"
- basic rendundancy
- adding/removing extra DNS entries
- service hot-swapping
- ability to retain entries for stopped containers
- using a different local domain
- rename remainder of "manual usage" section to "Using weaveDNS
without `weave run`"
- remove "Unregistering" section - it was out of date and is not
covered by the "add/remove" section

revise weaveDNS docs

---

site/troubleshooting.md
weaver/main.go

For consistency with WeaveDNS, and common usage, `-debug` is hereby re-appropriated to mean "a bit more logging" and "give me a log-line per packet" is relegated to `-pktdebug`.
This change driven by IPAM, where there are some log lines you want to see when debugging.  If this change were merged on its own, `-debug` would have no effect.

Rename per-packet debugging flag to `-pktdebug`

---

weave

Trawling the history, this went in in October 2014.  It only matters if an error comes back from `docker inspect`, which is quite unlikely in the context here.

 Fix typo '&& true' in weave script, that could cause partial population of DNS

---

ipam/allocate.go
ipam/allocator.go
ipam/claim.go
ipam/http.go

Make clear that they come from the IP allocator, and reduce repetition in the text.
Also include the nickname for other peer, if known.
Addresses #684

Improve ipam error messages

---

proxy/client.go
proxy/common.go
proxy/create_container_interceptor.go
proxy/create_exec_interceptor.go
proxy/proxy.go
proxy/start_container_interceptor.go
test/640_proxy_restart_reattaches_test.sh
test/config.sh

Bug came up in a test where we are restarting and doing an exec checking
a network interface right away. weavewait is only added if the container
has a WEAVE_CIDR var set, the same as at container creation.

proxy needs to add weavewait to execs as well

---

test/130_expose_test.sh
weave

Fixes #620, as discussed in comments there.  All smoke tests still pass.

Drop traffic from docker0 bridge to weave bridge

---

test/140_weave_local_test.sh
test/610_proxy_wait_for_weave_test.sh
test/640_proxy_restart_reattaches_test.sh
test/config.sh

Closes #707. `ip link show` seems to "lag" the real state. In tests
checking the physical link state is good enough.

use grep in /sys to verify ethwe is up in tests

---

router/connection.go

From the golang spec: 'A "break" statement terminates execution of the
innermost "for", "switch", or "select" statement within the same
function.'  But the LocalConnection actorLoop seems to assume it
skips the "select" and terminates the enclosing "for".
As a result, if something did conn.Shutdown(nil), it would not actually
shutdown the connection. It turns out this is never a problem, because
Shutdown is always called with a non-nil error, even though there is code
in a few places to handle the nil case. By cleaning that up, the dubious
"break" is eliminated.

Fix use of "break" within "select" in LocalConnection actorLoop

---

site/build-and-publish.sh

This still keep all doc URL schema as is, but add an extram `head` subdirectory representing the latest revision.

Create `weave/<branch>/head` for latest branch docs

---

weave

Addresses #723.
Also comment the use of `-I`, as noted on c5d5dd5fdc07239001cd853a9137091e6406d4c1

Check if Docker using weave bridge before inserting DROP rule

---

nameserver/addrs.go
nameserver/cache.go
nameserver/dns.go
nameserver/dns_test.go
nameserver/http_test.go
nameserver/mdns.go
nameserver/mdns_test.go
nameserver/mocks_test.go
nameserver/server.go
nameserver/server_cache_test.go
nameserver/server_test.go
nameserver/zone.go
nameserver/zone_lookup.go
nameserver/zone_lookup_test.go
nameserver/zone_test.go
site/weavedns.md
test/210_dns_multicast_test.sh
test/config.sh
weavedns/main.go

This PR implements
- an improved Zone database, where names can have multiple IPs.
- The Zone database can also store (and differentiate) locally introduced information as well as data obtained from remote peers (with mDNS)
- Names and IPs accept _observers_ that will we invoked when they change, currently used for cache invalidation but with more potential use cases (eg, remote peers notifications)
- The mDNS client and server has been moved inside the Zone database. The Zone database will use them for obtaining missing information, for keeping information up to date, etc (this integration between mDNS and the Zone database could be even tighter in the future...)
- The _mDNS server_ responds with all the answers available in the Zone database, and the _mDNS client_ can make use of …

Background updates for names in the Zone database

---

router/connection_maker.go
router/json.go
router/router.go
test/150_connect_forget_test.sh

Also added connection maker status ("DirectPeers", and "Reconnects") to json status output.
Closes #659 and #660
Text Output is:
```
Direct Peers:
192.168.48.11
Reconnects:
->[192.168.48.11:6783] trying since 2015-05-27 15:03:51.389284634 +0000 UTC
```
JSON Output is:
```json
...
"DirectPeers" : [
"192.168.48.11"
],
"Reconnects" : {
"192.168.48.11:6783" : {
"TryInterval" : "4.111466676s",
"Attempting" : true,
"TryAfter" : "2015-05-27T15:03:51.389284634Z",
"LastError" : "dial tcp4 192.168.48.11:6783: connection timed out"
}
},
...
```

Add "Direct Peers" to weave status

---

proxy/common.go
weaveexec/Dockerfile

...so that the default output of the likes of `docker ps` shows some of the real entrypoint/command.
Closes #768.

shorten proxy entrypoint

---

weave

but still always show weavedns status, if present
Closes #784.

make `weave status` fail when weave isn't running

---

circle.yml
test/.gitignore
test/assert.sh
test/gce.sh
test/run_all.sh
test/sched
test/scheduler/app.yaml
test/scheduler/main.py
test/setup.sh

- Build the weave build container if we don't have it in the circle cache.  That way, when it changes, we just flush the circle cache.  It can be removed from the docker hub now.
- Add some timeouts to the test runs and GCE destroy vm function; this should help prevent stranded VMs.
- Checkin assert.sh instead of fetching it each time.  This allows us to modify it to expose test run time.  Its LGPL, so it should be fine.
- Add a simple scheduler to decide what tests run on which shard in circle.  This should balance tests more accurately, and bring down total test run time down by about a minute or two.

Various fixes to circleci integration tests

---

proxy/client.go
proxy/start_container_interceptor.go
weavewait/main.go

If weavewait times out, it now exits, so that the behaviour is consistent with the proxy failing to attach networking.
Closes #788

Proxy kills container and returns error when attach fails

---

proxy/proxy.go
weave
weaveproxy/main.go

Add proxy info to 'weave status' output

---

ipam/allocator.go

Use the presence of a ticker object to determine whether we are actually waiting for consensus.
I also pulled the 'pending' bit out of the if-I-have-a-ring clause, because it is of interest either way.
Status before anything has happened now looks like this:
Allocator subnet 10.3.0.0/16
and after one `weave run`:
Allocator subnet 10.3.0.0/16 awaiting consensus: Nodes known: 1, Quorum size: 5
Pending requests for Allocate for 8450fe9a4cf18299cc745d32b8d052ac9e6cb3f069710a58eaff19abed78d607, 
Fixes #787

Improve ipam status message before and after pending consensus

---

weave

Because launch-proxy runs in weaveexec container, DOCKER_HOST is never
set.
Closes #807

weave PROXY_HOST is always localhost, so just hardcode it as that

---

nameserver/cache.go
nameserver/cache_test.go
nameserver/dns.go
nameserver/dns_test.go
nameserver/mdns_server.go
nameserver/mdns_server_test.go
nameserver/mdns_test.go
nameserver/server.go
nameserver/server_cache_test.go
nameserver/server_test.go
nameserver/zone.go
site/weavedns.md
weavedns/main.go

This PR introduces a `--ttl` argument in WeaveDNS for specifying a TTL different from the default 30secs. This TTL is used by WeaveDNS in:
* mDNS answers sent to other peers (these peers will honor this TTL when keeping these answers in the cache)
* DNS answers sent to local clients for locally introduced records (as they are not introduced with a TTL).
Some other changes:
* an undocumented `--neg-ttl` argument has also been introduced (not intended to be used by users)
* some minor refactorings (specially in TTL constants names)
Fixes #711

Make the TTL configurable

---

nameserver/server_cache_test.go

Improved unit tests for the cache:
* cache invalidations as a result of `AddRecord()`/`DeleteRecord()` calls
* cache expirations

WeaveDNS cache tests

---

test/run_all.sh

`./run_all.sh 110_encryption_test.sh`
Handles the assert_* calls better than running the test bare. If people like/use this, it would be nice to rename `run_all.sh` to something more appropriate.

allow test/run_all.sh to run specific test files

---

Makefile
prog/weavewait/main.go
proxy/start_container_interceptor.go

There was a race condition with containers running and exiting before
`weave attach` was finished, which would cause an error.
Closes #812

[proxy] Use USR2 signal to tell weavewait when to continue

---

prog/weavewait/main.go
proxy/create_exec_interceptor.go

Due to https://github.com/docker/docker/issues/9098, there is no way to
signal an exec. Instead we'll have to just poll the interface and hope.
Adds `weavewait -s` which is the way to tell weavewait to skip waiting for a signal, which we use on execs

[proxy] We can only rely on receiving a signal when we are a container

---

weave

since $CONTAINER_PID is in a different process namespace.
Fixes #829.

kill -0 $CONTAINER_PID does not work inside weaveexec container

---

router/router.go
site/how-it-works.md

The main purpose of this is to set an upper bound on the rate at which
an attacker might execute a brute force attack on the weave password.
No need to get clever or precise here.
Closes #837.

limit acceptance rate on peer connections

---

prog/weaveproxy/main.go
proxy/proxy.go
site/proxy.md
weave

There are two problems with obtaining the proxy status via the normal
proxy endpoint...
1. when TLS is enabled, this requires using TLS at the client end
2. the status URL is mixed in with the docker remote API, which is
rather unclean
There is limited value to having some status output from the proxy,
since all the output is constant.
So instead we log the version and command line args.
We still want a way to wait for the proxy to start up, and log a nice
error if it dies. We do this by polling the docker logs for a startup
message.
Fixes #877. Fixes #876.
Undoes #756, #800, #854.

remove most of proxy status

---

prog/weaveproxy/main.go
site/proxy.md
weave

Closes #805 and #810
`weave status` will pick a random port to connect on (due to map ordering of `docker inspect`).
Renames `-L` flag to `-H` to match docker daemon, which means renaming the existing `-H` flag to `-D`. The `-H` flag doesn't *completely* match the docker daemon's, which takes a `tcp://` prefix, but is at least closer.
Debating adding a smoke test for this. Would be nice to have, but adds to the test run speed.

Add support for custom proxy bind address

---

router/gossip.go
router/gossip_test.go

Make flushing of GossipSender wait till done, and take extra locks to avoid race conditions.
Fixes #885.

Avoid gossip test race conditions

---

proxy/proxy.go
site/proxy.md
test/650_proxy_env_test.sh
weave

If the overall approach looks fine, I want to modify the tests to use this.
Closes #753

add proxy-env and proxy-config which query weaveproxy for port

---

test/260_dns_removal_test.sh
weave

We erroneously assumed that `docker start` returned the full container id. It doesn't and as a result we populated DNS with records with ids other than full container ids. And that's also what we told IPAM. As a result, DNS and IPAM didn't clean up after the container's death, resulting in stale DNS entries and leaked IPs.
Fixes #881.

feed full container id on `weave start` to DNS/IPAM

---

.gitignore
Makefile
net/route.go
net/route_test.go
prog/netcheck/netcheck.go
prog/weaveexec/Dockerfile
site/ipam.md
weave

Somewhat arbitrary default of 10.16.0.0/12 chosen to be pretty big and yet avoid regions like 10.0.2.0/24 used by VirtualBox.
The default subnet will also be 10.16.0.0/12. (This will need to change to accommodate various other IPAM requirements).
A new helper program 'netcheck' is introduced to see if any existing routes cover that address range, which is a proxy for 'is that space unused' (technique borrowed from Docker). Netcheck is put on the path inside the `weaveexec` container, to simplify the problem for people doing `weave --local launch` who want the default `-iprange`.
Fixes #743 
Also addresses #870, although it will perhaps annoy some people who don't want to use IPAM, if they do have a clash with the default, since it will force them to pick a non-clashing range.

Default value for -iprange

---

site/ipam.md
weave

... so it doesn't clash with CircleCI address
We were getting a lot of failures like this:
````
---= Running 150_connect_forget_test.sh =---
Connecting and forgetting routers after launch
network 10.128.0.0/9 would overlap with route 10.240.0.1/32
Default -iprange 10.128.0.0/9 overlaps with existing route.
Please pick another range and set it on all hosts.
````

Use /10 instead of /9 for default iprange

---

common/sched_queue.go
common/sched_queue_test.go
nameserver/mocks_test.go
nameserver/server_cache_test.go
nameserver/zone.go
nameserver/zone_lookup.go
nameserver/zone_lookup_test.go
prog/weavedns/main.go

This is an extension of #836. Original comment:
Fix the zone refresh unit test by using a scheduled queue where callables are invoked at specific times. This also simplifies the refreshing mechanism in the Zone database. And there are some minor tweaks in the unit test as well...
Fixes #798
Further fixed by ensuring all background calls are flushed ever time we move the mock clock.

Return of the Fix for the zone refresh unit test

---

ipam/allocator_test.go

otherwise we can re-insert the entry into the map after a parallel
`allocateAgain()` has cleared the flag. And if *that* happens in
parallel with a `free()` then the data-structure can get out of sync.
Fixes #915
Also bumped the test parameters up a bit to give more chance of spotting race conditions.

Fix spurious unit test failure in TestAllocatorFuzz()

---

weave

Fixes #916
Will print an error message if any of the calls to `weave` or `weavedns` fails after we've decided the container was running.
I've added `-S` to the curl options for all calls, so we get some explanation too.  In the example of #916, we now get:
````
curl: (52) Empty reply from server
Call to weave failed.
````
This implied an extra redirect to `/dev/null` in `wait_for_status` as we expect some of those calls to fail and don't want the user to see error messages.

Output error message if http call to weave or weavedns fails

---

nameserver/zone_lookup.go

Release lock before sending on a channel, but *after* modifying mutable variables.
Fixes #923, #924, and #926.
Didn't have write-permissions to @bboreham's fork, so opened new PR on main repo.

Fix deadlock in weavedns

---

nameserver/zone_lookup.go

Fix a potential deadlock by using read/write-locks instead of read-locks
Fixes #930

Use read/write-locks instead of read-locks in the Domain*Lookup()

---

proxy/create_container_interceptor.go
site/weavedns.md
test/230_dns_unqualified_test.sh
test/635_proxy_dns_unqualified_test.sh
weave

Behaviour is:
* If search-domain specified by user, do nothing
* If hostname specified by user, search domain is .
* If weaveDNS is available, set search domain to the weaveDNS domain
* Otherwise, set to `.weave.local.`
Fixes #749
@awh, please review.

[dns] resolve names in `weave.local` by default unless hostname or search path is specified

---

common/logging.go
nameserver/cache.go
nameserver/mdns_client.go
nameserver/mdns_server.go
nameserver/mdns_server_test.go
nameserver/server.go
nameserver/server_cache_test.go
nameserver/server_test.go
prog/weavedns/main.go

Most are artefacts of the test code, but having so many reports made it difficult to check for any real problems.
The only one which looks like a real problem is a34d2ec45c5d4065010f9ce035a270313a8cd228, though aa85e19256c6bceb3fa2b0f82a45ea033787e7ac could conceivably result in a crash.

Fix all reports from `go test -race` in weavedns unit tests

---

weave

`docker log` outputs an error if stdout is closed before it is done, so
silence that
Fixes #939

[proxy] Remove spurious output from proxy-(env|config)

---

proxy/common.go
proxy/create_container_interceptor.go
proxy/create_exec_interceptor.go
proxy/proxy.go
proxy/start_container_interceptor.go
site/proxy.md
test/650_proxy_env_test.sh
test/660_proxy_ipam_test.sh
weave

Tells the proxy not to do anything with this container. We set it when
running weaveexec/weave/etc containers, so that the weave script works
through the proxy.
Fixes #950
Now:
```bash
vagrant@host1:~$ ./weave launch-proxy
d4a0717b0c9e0ab217c02d8f84fa518454cd639f48fc748088b99816f36cee2c
vagrant@host1:~$ eval "$(./weave proxy-env)"
vagrant@host1:~$ ./weave version
weave script (unreleased version)
weave router git-c45b586a4424
weave DNS git-c45b586a4424
weave exec (unreleased version)
vagrant@host1:~$ ./weave launch
f274564cc22d7810f80f2d467485407546a757f02f32238e6421e62421ad9699
```

[proxy] Add support for WEAVE_CIDR=none

---

proxy/create_container_interceptor.go
proxy/proxy_intercept.go

The go docker client's `ErrNoSuchImage` does not include the image name. However, it is imperative that this name appears in error messages sent to clients, since the docker client, as of version
1.7.0, only automatically pulls images when their name is present in the error.
Fixes #967.

include image name in errors

---

site/proxy.md

It doesn't do anything useful since the weave script needs to be able
to talk to docker on the standard unix socket.
Also remove dangling reference to 'localhost', and move note about
firwalls to where it is most pertinent.
Part fix to #972.

remove the `-D` proxy option from the docs

---

site/proxy.md

Previously, no proxy examples used the `net:` syntax, and this particular example duplicated the one 18 lines above.

Change one IPAM proxy example to use a network

---

site/features.md
test/500_weave_multi_cidr_test.sh
weave

show IP addresses in attach/expose/detach/hide

---

proxy/create_container_interceptor.go
test/610_proxy_wait_for_weave_test.sh

This way `docker commit` will not stack up weavewaits.
Fixes #979

[proxy] Only prepend weavewait if not already present

---

test/610_proxy_wait_for_weave_test.sh
test/config.sh
test/setup.sh

This gives more consistent test execution times, and also make image fetch failures more apparent and decoupled from the tests.
We could *always* just run `pull`, but it's an expensive operation, so we check for the presence of the image first. The downside is that we could be running old images. That is not a problem on our CI infrastructure though since it spins up fresh VMs per for every tun.

prefetch test images

---

README.md

Now that Dockercon is past, removed the link to Dockercon

Remove Link to Dockercon from README

---

weave

This reduces `weave launch|launch-dns` execution time.
Closes #992.
On my machine, `time weave launch` takes ~1.95s before this change, and ~1.15s after.

sleep for 0.1s instead of 1s in the wait_for_status loop

---

.gitignore
Makefile
build/Dockerfile
site/building.md
test/setup.sh

That way the export can be just a single tar, which is more convenient.

separate the image build and export phases

---

router/connection.go
router/connection_maker.go
router/forwarder.go
router/gossip.go
router/gossip_channel.go
router/gossip_test.go
router/local_peer.go
router/mac_cache.go
router/router.go
router/routes.go

Most start methods in the router are trivially redundant.  Apart from the redundancy, start methods raise the question of the state of an object prior to the start method being called (i.e. which fields are valid, which methods can be called, etc.).  So they should only be used when there is a reason.
(Extracted from #991)

Eliminate start methods

---

Makefile

The `-t` flag asks Go to fetch anything required for tests, which is more necessary now we have added testify.
I considered adding a `go get` line to the `make tests` target, but it's already unwieldy and not necessary if people do 'make' first.

Extend 'go get' to tests

---

ipam/allocate.go
ipam/allocator.go
ipam/ring/ring.go
ipam/ring/ring_test.go
router/gossip_channel.go

Replacing #1005 which was against master not 1.0
Note I have done it a slow and stupid way in one commit, then improved the algorithmic complexity using a CDF and binary search in the next commit.
Fixes #896

Try other peers for space if we get errors

---

prog/weaver/main.go
router/ethernet_decoder.go
router/forwarder.go
router/local_peer.go
router/router.go

The router extracts the DF flag from a received frame early on and passes it around.  But it doesn't use it in any significant way until it reaches the UDP forwarder code.  These commits defer extracting it until it is really needed.

Don't inspect the DF flag earlier than we need to

---

ipam/allocator_test.go
ipam/testutils_test.go

(replaces #1017, branched against 1.0 this time)
Refactored mock router, and added a `flush()` function which we then call every time gossip messages are generated in `TestTransfer()`, thus avoiding the problem that they may be dropped if the previous message has not been removed from the channel, or may not have arrived by the time we check what has happened.
`flush()` is not called in the other two tests that use the mock router; one of them hardly does anything, and the other benefits from the message-dropping behaviour, in that it makes it also a test of recovery from network issues.
Fixes #982.
Also replaced a `Sleep` with the `flush`, so the unit tests run faster.

Flush messages from mock gossip in IPAM test

---

prog/weaveproxy/main.go
proxy/proxy.go
site/proxy.md
weave

- proxy still listens on 0.0.0.0; can now listen on multiple endpoints
- bind mounts /var/run instead of /var/run/docker.sock so the host can see the proxy sock.
- copies owner & permissions from /var/run/docker.sock to /var/run/weave.sock
Fixes #1003

Make proxy listen on unix:///var/run/weave.sock

---

test/140_weave_local_test.sh
test/config.sh
test/gce.sh
test/run_all.sh
test/sanity_check.sh
test/setup.sh

Since scope has to check out the latest weave release anyway, we may as well use the test helpers from there, and only manage them in one place.
This must be merged, and into a release before: https://github.com/weaveworks/scope/pull/273

Let Scope use these integration test helpers

---

test/config.sh

As discussed at #1042, calling `conntrack -D` before shutting down older containers seems to improve the reliability of our smoke tests.
Also it gives a more gentle shut-down, so a better model to copy in case someone is trying to do something similar.
Replaces #1052, which was against the wrong branch.

Call `weave reset` earlier in smoke-test set-up, to improve reliability

---

Makefile
net/route.go
prog/netcheck/netcheck.go
weave

Fixes #437, #480.
Issues a warning but carries on.
Note that we are still not checking ranges passed to IPAM; I'm still considering whether that is a good idea.

Check addresses supplied by users for conflict with existing routes

---

proxy/create_container_interceptor.go
test/270_use_name_as_hostname_test.sh
weave

Rebased version of #1038. Fixes #1006.

Disable hostname derivation when container name is too long

---

README.md
site/features.md
site/how-it-works.md
site/proxy.md
site/troubleshooting.md

in order to reduce potential confusion about its role.
Closes #1019.

introduce 'Proxy' as 'Docker API Proxy'

---

proxy/common.go
proxy/proxy.go
proxy/start_container_interceptor.go

[proxy] print all stderr output from callWeave to the proxy logs, even if successful

---

common/init.go
common/logging.go
common/sched_queue_test.go
ipam/allocator_test.go
ipam/http_test.go
nameserver/addrs_test.go
nameserver/cache_test.go
nameserver/dns_test.go
nameserver/mdns_client_test.go
nameserver/mdns_server_test.go
nameserver/mdns_test.go
nameserver/server_cache_test.go
nameserver/server_test.go
nameserver/zone_lookup_test.go
nameserver/zone_test.go
prog/weavedns/main.go
prog/weaveproxy/main.go
prog/weaver/main.go
site/troubleshooting.md
test/config.sh

Addresses #329.
Note that some log levels do not sit well with some combinations of usage, e.g. the parts of the `weave` script that scan logfiles looking for specific messages are broken if your log-level inhibits those messages.  But it offers flexibility to advanced users.

Give the user more choice of log levels

---

site/features.md
site/proxy.md
site/weavedns.md
test/650_proxy_env_test.sh
weave

Keep error message to stderr, as the proxy should be launched with
'weave launch'. Or would you rather have no output at all?
Fixes #1014

rename proxy-(env|config) to (env|config)

---

weave

ATM that's just --loglevel=...
Closes #1043.

pass common `launch` args to all three components

---

README.md
site/features.md
site/ipam.md
site/proxy.md
site/weavedns.md
weave

To avoid clashing with Digital Ocean's and GCE's default private networks.
Fixes #1036 
(note this PR is raised against master; will re-raise if it was supposed to be against 1.0)

Change default IP allocation range from 10.128/10 to 10.32/12

---

bin/multiweave
docs/dockerless.txt
prog/weavedns/main.go
prog/weaveproxy/main.go
prog/weaver/main.go
site/features.md
site/ipam.md
site/proxy.md
site/troubleshooting.md
test/100_cross_hosts_test.sh
test/110_encryption_test.sh
test/130_expose_test.sh
test/140_weave_local_test.sh
test/210_dns_multicast_test.sh
test/270_use_name_as_hostname_test.sh
test/500_weave_multi_cidr_test.sh
test/620_proxy_entrypoint_command_test.sh
test/660_proxy_ipam_test.sh
weave

Namely:
* long options get two hyphens at the start; e.g., `--password`; and,
* options made from multiple whole words are hyphenated; e.g., `--no-discovery`; and,
* some options that are applied to DNS but sound universal have `dns` prepended, e.g., `--dns-port`.
There are exceptions; "ipalloc" is treated as one word for hyphenation; the `--tls*` options are left as-is since they correspond to Docker options; some niche options don't get hyphenated e.g., `--bufsz`; some options that are likely to disappear are left alone.
In all cases, the old version of an option will work, while outputting a deprecation warning. Mostly these will end up in container logs. Renamed options that are mentioned in the script usage, or otherwise specially-treated in the script, have a deprecation notice …

Consistent option naming

---

weave

In any place we munge options, treat the form with an equals the same
as the form without.
The exes ultimately invoked by the script handle both forms, so unless
we need to do something with the option in the script, we can just let
options fall through.
Fixes #1087.

Handle --option=value as well as --option value

---

common/docker/client.go
ipam/http.go
nameserver/http.go
weave

...rather than conducting it implicitly when an ID "looks like" a container ID.
Closes #971.

make container aliveness check part of the ipam & dns API

---

weave

so that the likes of $(weave proxy-typo-env) don't do weird things
Closes #1082.

display usage on stderr

---

ipam/allocator.go
ipam/allocator_test.go
ipam/claim.go
ipam/http.go

If an error is immediately apparent, e.g. we have already allocated that address on this host, or we have been told via gossip that another host owns that range, then it will go back to the caller.
If an error is possible but not detectable yet, then the claim is left pending and the caller is told it's ok (nil error return).
Another change in behaviour is that we stop tracking whether the caller has closed the http socket before we managed to reply properly; since this happens naturally on the first 'nil' return and we don't expect to be processing the request very long anyway.
Fixes #1083

Don't wait to claim addresses from IPAM

---

Makefile
circle.yml
common/signals.go
prog/weaver/main.go
prog/weaver/main_test.go
test/140_weave_local_test.sh
test/150_connect_forget_test.sh
test/config.sh
test/gen_coverage_reports.sh
testing/cover/cover.go
testing/util.go
weave

Code coverage for smoke tests.

---

prog/weaveproxy/main.go
prog/weavewait/main.go
proxy/create_container_interceptor.go
proxy/proxy.go
test/610_proxy_wait_for_weave_test.sh
weave

Partial fix for #68. Won't help with dynamic `attach/detach` or the weave script.

[proxy] weavewait rewrites /etc/hosts so weave ip is returned first from 'hostname -i'

---

test/120_discovery_test.sh
test/Vagrantfile
test/config.sh
test/gce.sh

test peer discovery, multi-hop routing and gossip forwarding.
increases code coverage as follows:
````patch
$ diff /tmp/coverage-before.txt /tmp/coverage-after.txt 
59c59
< github.com/weaveworks/weave/ipam/allocator.go:454:		actorLoop			90.9%
---
> github.com/weaveworks/weave/ipam/allocator.go:454:		actorLoop			100.0%
86,87c86,87
< github.com/weaveworks/weave/ipam/http.go:14:			badRequest			0.0%
< github.com/weaveworks/weave/ipam/http.go:20:			HandleHTTP			54.5%
---
> github.com/weaveworks/weave/ipam/http.go:14:			badRequest			100.0%
> github.com/weaveworks/weave/ipam/http.go:20:			HandleHTTP			56.8%
340c340
< github.com/weaveworks/weave/router/connection.go:125:		BreakTie			0.0%
---
> github.com/weaveworks/weave/router/connection.go:125:		BreakTie			66.7%
351,352c351,352
< …
```

Multi hop tests

---

test/setup.sh

Each time we copy new images the old ones lie around unreferenced, and eventually fill up the disk.  
So this PR deletes the dangling ones.

Remove Docker dangling images in smoke-tests

---

test/100_cross_hosts_test.sh

change in coverage:
````patch
$ diff /tmp/coverage-before.txt /tmp/coverage-after.txt 
372c372
< github.com/weaveworks/weave/router/connection_maker.go:161:	queryLoop			87.5%
---
> github.com/weaveworks/weave/router/connection_maker.go:161:	queryLoop			100.0%
411c411
< github.com/weaveworks/weave/router/ethernet_decoder.go:33:	sendICMPFragNeeded		0.0%
---
> github.com/weaveworks/weave/router/ethernet_decoder.go:33:	sendICMPFragNeeded		88.9%
419c419
< github.com/weaveworks/weave/router/forwarder.go:78:		forward				57.9%
---
> github.com/weaveworks/weave/router/forwarder.go:78:		forward				63.2%
549c549
< github.com/weaveworks/weave/router/router.go:147:		handleCapturedPacket		81.5%
---
> github.com/weaveworks/weave/router/router.go:147:		handleCapturedPacket		85.2%
609c609
< total: …
```

test that large packets can be transmitted over weave

---

router/router.go
router/token_bucket.go
site/how-it-works.md

This PR adds adaptive connection acceptance rate limiting in the form of a lazy token bucket implementation, replacing the constant 1ms sleep in use before. The bucket contains a maximum of 100 tokens, replenished at a rate of one every 100ms; this allows a burst of up to 100 connection attempts without any delay, limiting to 10 per second thereafter under sustained load. Quiescence allows the bucket to refill back to its maximum, the intended effect being that initial network formation and partition healing are not hindered at all, but a sustained denial of service will be.
Testing reveals that this does not address the reported issue entirely - even at the lower bound of 10 requests per second there may not be enough entropy gathered on a headless system to keep pace. Nevertheless, …

Mitigate entropy depletion

---

test/Vagrantfile

The 'overlay' driver is [claimed](http://jpetazzo.github.io/assets/2015-03-03-not-so-deep-dive-into-docker-storage-drivers.html#57) to be the best choice right now, but requires Linux kernel 3.18.
You can feel the difference - using `vfs` (which our Vagrant set-up did because it didn't install the extra bits for `aufs`) the machine would bog down when tests were running, but with `overlay` you rarely notice this.
I will post some timings to illustrate the difference soon.

Upgrade smoke-tests to use 'overlay' storage and Ubuntu 15.04

---

nameserver/dns.go
nameserver/names.go
nameserver/names_test.go
nameserver/server.go
nameserver/server_test.go
nameserver/zone_lookup.go
nameserver/zone_lookup_test.go
test/230_dns_unqualified_test.sh
test/config.sh

Resolve unqualified names in the local WeaveDNS domain

---

prog/weaveexec/Dockerfile
site/features.md
site/weavedns.md
test/250_dns_lookup_test.sh
weave

Requires #987 to work as documented.
Fixes #1028.

Implement `weave dns-lookup`

---

test/Vagrantfile
vagrant-common.rb

Docker needs to be restarted and not started, since it already starts running after installation
@paulbellamy @bboreham please review

Restart docker after vagrant tweaking and refactor tweak-code

---

nameserver/dns.go

Copy dns requests and give them a fresh id when doing recursive queries.

---

ipam/allocator.go
ipam/allocator_test.go
ipam/testutils_test.go
nameserver/nameserver.go
router/gossip.go
router/gossip_channel.go
router/gossip_test.go
router/router.go
router/surrogate_gossiper.go
testing/gossip/mocks.go

We unicast the ring back to the originator, since we don't want everyone broadcasting every time someone new but ignorant joins the network.
Requires a change to the Gossiper interface so we know who to unicast to.
Fixes #1118; brings test 120 time down from 37 seconds to 14 on my machine.

Respond to paxos messages when we already have a ring

---

nameserver/entry.go
nameserver/entry_test.go
nameserver/nameserver.go
test/210_dns_cross_hosts_test.sh
testing/gossip/mocks.go

- merging old entry versions should not yield a diff
- when there is no diff, return nil, not the empty list of entries
- extend mock gossip router to ensure reconsumption off diffs yield nil
- add dns test for 3 (or N) hosts.
Fixes #1151

Make DNS gossip converge correctly

---

weave

$$ refers to the pid in the container's process namespace, so using it as a reference into /hostproc is entirely wrong.
Fixes #1162.

fix detection of host netns when weave script runs inside container

---

prog/weaveproxy/main.go
site/proxy.md
test/690_proxy_autoconfig_test.sh
weave

Use the docker daemon's `-H` flags as the proxy's default.
No support for auto-configuring TLS. For that we would have to do the procfs and flag parsing in the weave script (so that we could mount the certs into the proxy container).
This is possibly a bit linux-specific, as the layout of procfs is not standardized.
Fixes #1055

Proxy autoconfig

---

ipam/allocator.go
ipam/allocator_test.go
ipam/claim.go
test/160_claim_test.sh

Implement claiming addresses from other peers

---

prog/weaveexec/Dockerfile

Combining multiple ADDs on the same line reduces the number of layers, and moving the stuff that doesn't change earlier in the file improves the chance it will re-use that layer from cache.
Empirically, the ADD lines are never cached, so they should come last.

Re-arrange weaveexec Dockerfile to improve download times

---

nameserver/entry.go
nameserver/entry_test.go

Make nameserver.checkAndPanic look for dups, call it more often.

---

site/boot2docker.md

The TLS options bit is quite gross. It goes away with [this branch](https://github.com/paulbellamy/weave/tree/1105-proxy-autoconfig), which auto-configures the proxy's tls based on the docker daemon (if we want to go that way).
The other option is to disable tls for boot2docker:
```
host1$ ./weave launch-proxy -H tcp://0.0.0.0:12375`
host1$ eval "$(./weave proxy-env)"
host1$ unset DOCKER_TLS_VERIFY
``` 
Fixes #975, but needs modifying for master

updating boot2docker docs for proxy

---

ipam/allocator.go
ipam/ring/ring.go
ipam/ring/ring_test.go
net/address/address.go

Fixes #1128
I did an additional check at the `Allocator` level rather than modifying the check inside `Ring`, to keep the latter unaware of why `Merge` has been called.

More helpful error message when --ip-alloc-range mismatched

---

site/_layouts/default.html
site/assets/custom.css

Instead of using `> ` for warnings in the docs, we'll use 
```html
<div class="alert alert-warning">
Crazy stuff happening...
</div>
```
Fixes #1061

Use Boostrap styles for warnings in docs

---

nameserver/nameserver_test.go
testing/gossip/mocks.go

Correctly stop the test gossip router to prevent complaints of data races in subsequent tests.

---

bin/multiweave
prog/weaver/main.go
weave

Introduce a `--no-dns` option to `weave launch[-router]`. Undocumented, since it's mainly intended for testing. And use that in multiweave, so it works again, post #1065.

Disable dns in multiweave

---

nameserver/entry.go
nameserver/nameserver.go

Fixes #1156 
5mins max clock skew seems too small to me; I suggest we make it bigger (and therefore make the DNS tombstone timeout larger).

Make Gossip DNS reject gossip messages if clockskew > tombstoneTimeout / 2

---

proxy/proxy_intercept.go
proxy/proxy_intercept_test.go

1) We cannot send "Connection: close", because the fsouza docker client
expects the tcp socket to stay open between requests.
2) Because we cannot force-close the connection, we can't hijack the
connection (because go's net/http doesn't let use un-hijack it).
3) Because we need to maintain the individual chunking of messages (for
docker-py), we can't just copy the response body, as Go will remove and
re-add the chunking willy-nilly.
Therefore, we have to read each chunk one-by-one, and flush the
ResponseWriter after each one.
Fixes #1103
Merging into master instead of 1.0, as it is definitely not a "patch" change. Replacing #1110.

[proxy] rewrote chunked response handler

---

nameserver/nameserver_test.go

To ensure there isn't a build up of pending messages.
Fixes #1158

Flush gossip messages after each turn

---

test/units.sh

When running unit tests, output coverage for imported modules.

---

router/consts.go
router/crypto.go
router/protocol.go

...replacing it with length-prefix encoding.
Addresses part of #519.

remove outermost gob

---

ipam/allocator.go
ipam/allocator_test.go
ipam/claim.go
ipam/http.go
weave

Fixes #687 and #598
One quiet change in this PR:
* avoid printing error messages from 'claim' twice in the logs

Check manually-assigned addresses with IPAM to see if they clash

---

ipam/allocator.go
ipam/claim.go

* the comment "don't make the caller wait" applies to both branches
of that if clause, and having it on one branch implies the other
does make the caller wait
* there's no reason for DeniedBy to start with a capital: it's a
method on a private struct and it's not part of an interface.

Remove misleading comment and lowercase deniedBy

---

nameserver/dns.go
nameserver/dns_test.go
prog/weaver/main.go

So we can run the weave router in the host net namespace.
In FDP the weave script will need to set ```--dns-listen-address=<docker bridge ip>:53```
Part of #1215

Allow users to set dns listen address

---

circle.yml
ipam/allocator_test.go
test/gce.sh
test/setup.sh

We're hovering around the 12:30 min mark on master.  This change brings it down to about 8:30:
- improve gce.sh so it only ssh's into the VMs once to copy over the /etc/hosts file, and does this in parallel.  Also minimise the number of calls to GCE, as they are slow.  Save 20-30secs
- improve setup.sh to copy and fetch images in parallel.  Saves ~1min
- reduce the parallelism in ipam tests, as this interacts particularly badly with the race detector.  Saves ~3.5min.  Fixes #1234

Improve CI run time

---

testing/runner/runner.go

Silence the stdout from successful tests, (add -v or DEBUG options to show it).
Lists failed tests at the end, e.g.
```
>>> Ran 34 tests, 2 failed
>>> Fail /home/vagrant/src/github.com/weaveworks/weave/test/160_claim_3_test.sh
>>> Fail /home/vagrant/src/github.com/weaveworks/weave/test/601_proxy_docker_py_test.sh
```

Some usability tweaks to the test runner

---

common/utils.go
router/connection.go
router/connection_maker.go
router/ethernet_decoder.go
router/gossip_channel.go
router/local_peer.go
router/router.go
router/udp_sender.go
router/utils.go

Many router files do a dotted import of `common` for the sake of `Log`.  This means everything else from `common` ends up in scope, for the sake of a single variable.

Fix dotted imports for logging

---

prog/weavewait/main.go
proxy/create_container_interceptor.go
test/610_proxy_wait_for_weave_test.sh

The docker daemon can't do this because we set /w/w.
Fixes #1241

[proxy] Handle case where no command is specified.

---

weave

send ARP update for *all* container IPs; not just the first one

---

test/600_proxy_docker_py.sh

don't save the python test file when running test/600

---

nameserver/zone_lookup.go

When we issue two concurrent mDNS queries for the same name, the answer to the second one encounters a DuplicateError when inserting into the zone. We would return that error, which causes the query would fail. And we'd cache that fact. All bad.
So ignore DuplicateError.
Fixes #1270.

ignore DuplicateError when inserting mDNS answer in zone

---

test/160_claim_3_test.sh

Fixes #1243.
I've also raised #1267 to address the issue more directly. The reason this is cropping up in this test more than others is that here we only start one container between launching weave and 'ping'ing, whereas elsewhere we start two. The extra start adds just enough of a delay for the routers to establish connectivity. So does a 'sleep', which is how I've "fixed" it - I've had 10 successful runs on CircleCI like that, only interrupted by some unrelated failures.

add a sleep to improve test reliability

---

test/100_cross_hosts_2_test.sh
test/105_frag_2_test.sh

All credit goes to @dpw for figuring out how to break the kernel's packet fragmentation:
> 'man iptables' documets a --fragment option, which looks ideal for this purpose: It matches non-initial fragments.
>
>But if you try to use this, you will find that, mysteriously, a rule using --fragment never seems to trigger.
>
>The reason is that if the conntrack module is loaded, then iptables always reassembles packets before evaluating iptables rules (even rules that don't involve conntrack in any way).  So the rules never see any fragments.  And of course, if you have started docker, you have conntrack loaded.
>
>So that rules out dropping non-initial fragments with iptables.  But it is possible to get a similar effect by crafting an iptables rule that drops any UDP packet larger than the …

add test for PMTU discovery and packet fragmentation

---

router/pcap.go
router/router.go
router/status.go

Closes #1185.
````
$ weave report
...
"CaptureStats": {
"PacketsDropped": 1881,
"PacketsIfDropped": 0,
"PacketsReceived": 78612
},
...
````
I decided not to add this to `weave status`; we can do that later if/when it proves to be an important for troubleshooting.

add pcap stats to `weave report`

---

test/680_proxy_weave_run_test.sh
weave

...which could result in containers unexpectedly getting multiple IP addresses.
Fixes #1279.

prevent proxy from interferring with `weave run`

---

test/630_proxy_dns_test.sh
test/635_proxy_dns_unqualified_test.sh
test/640_proxy_restart_reattaches_test.sh
test/660_proxy_ipam_test.sh
test/config.sh

This also eliminates the redefinition of 'start_container' by some of the tests, which causes failures when multiple tests are run with `run_all.sh`.
Fixes #1294.

extract test functions for "start container via proxy"

---

proxy/create_container_interceptor.go
proxy/create_exec_interceptor.go
proxy/proxy.go
proxy/start_container_interceptor.go

- 'ignoring' could be misread as 'dropped request', so change that to 'leaving container alone'
- more elaborate reasons

Improve log messages for when the proxy ignores a container

---

nameserver/server.go
nameserver/server_test.go

Try to compress too long replies (when forwarding).

---

nameserver/dns.go
nameserver/dns_test.go

Compress recursive answers if they are too big.

---

router/connection.go
router/connection_maker.go
router/status.go

When we discover that a connection target address leads to ourself we set the retry time to the zero time.Time value - the only special time.Time value. We use that marker to a) suppress subsequent
connection attempts, and b) display the next retry as 'never' in `weave status|report`.
Closes #1305.

don't reconnect to ourself

---

weave

`weave env` stashes the existing DOCKER_HOST in ORIG_DOCKER_HOST, and `weave env --restore` sets DOCKER_HOST to $ORIG_DOCKER_HOST.
Note that `weave env --restore` always executes locally, which means it will work when the env has a 'broken' DOCKER_HOST.
Closes #1288.

`weave env --restore`

---

router/gossip_channel.go

GossipChannel.sendDown is the (only) place which creates GossipSenders. It has two call sites, Send and SendDown, only the former of which performed a gc of existing senders. Therefore, in configurations with
- a lot of connection churn, and
- SendDown invocations for these connections, and
- few or no Send invocations
we can leak GossipSenders.
The most likely scenario for this to occur is a peer that, while having no other connections, is making/accepting connections which get torn down post handshake, e.g. because IPAM detected a clash.
Fixes #1329.

plug GossipSender leak

---

weave

Issue was discovered when testing scope with master vs 1.0 branches.
@inercia, Any reason not to do this? AFAICT it initializes the same thing on tcp and udp, but just doesn't expose the tcp.

Expose dns server on tcp as well as udp

---

test/160_claim_3_test.sh

The point of the last few lines of test 160 is to see whether starting weave in a state where it thinks it should talk to a currently-stopped peer will hang it.  This change makes this clearer (but does not run the launch command in a `timeout` wrapper because `weave_on` is a shell function and it's too complicated to extract it out for `timeout` to call).

clarify test 160

---

weave

better docker version check

---

weave

instead of showing '404 page not found'
Fixes #1328.

better error handling for invalid `weave status` sub-command

---

ipam/ring/ring_test.go

In ipam ring unit test, check if we have any peers with entries to avoid crash 

---

ipam/ring/ring_test.go

There were a couple of subtle bugs in how the information was copied around on removal of a peer and its ring.
Fixes #1336

Fix ring fuzz-test

---

prog/weaver/main.go

The standard mflags error reporting produces an error like
```
flag provided but not defined: -p
See '/home/weave/weaver --help'.
```
on stderr. This is misleading since the program name is container local, so not something the user actually invoked. Furthermore, what the user *can* invoke doesn't have a `--help` option.
With this change the error becomes
```
FATA: 2015/08/18 10:56:23.635119 Incorrect usage: flag provided but not defined: -p
```
There are a few issues with this:
- we no longer get a usage message
- we no longer get deprecation warnings logged
Fixes #1321. Alas I am not at all happy with this. Wasted several hours on this already. Somebody else please have a go.

eliminate misleading flag parsing error

---

nameserver/dns.go
nameserver/dns_test.go

This takes the refactoring bit of #1334, evolves it (the handler construction is neater here), adds some extra refactors, and an optimisation.
Best reviewed by looking at the individual commits. And the first of those is best view in a good diff viewer, e.g. kompare in whitespace-ignore mode, where it will appear *much* smaller than here on github.

Refactor dns handlers

---

nameserver/dns.go
test/295_dns_large_response_test.sh

Unify logic to tell if DNS response is too big.

---

circle.yml

Publish latest images from CI on successful builds.

---

nameserver/nameserver.go

Update comment to fix #1347

---

nameserver/dns.go
nameserver/dns_test.go
prog/weaver/main.go
weave

Flag is called ```--dns-effective-listen-address```, and is automatically populated by the ```weave``` script.
Fixes #1343 
Note we don't actually validate the contents of this field (ie check its a real IP address).  We can do, but I didn't see the point.

Pass docker bridge ip to dns server, and filter it out of upstream dns ips.

---

site/features.md

Escape a minus character to stop it being taken as a bullet, and clarify which example we are talking about.

Small improvements in features doc

---

test/295_dns_large_response_test.sh

Use `$*` instead of `$@` to get the desired quoting
Fixes #1362

Fix test 295

---

nameserver/nameserver.go
test/265_dns_reverse_test.sh
test/config.sh

Make reverse dns lookups honor tombstones.

---

prog/weaveexec/Dockerfile
prog/weaver/Dockerfile

As part of https://github.com/weaveworks/scope/issues/337, I'd like to label the weave & scope containers and have them filtered out of the scope view by default.
Let the bike shedding begin...

Add role label to weave containers so scope can filter

---

weave

These can occur when a container dies during `weave reset`.
Fixes #1356.

ignore interface deletion errors during `weave reset`

---

weave

Warn on detection of REJECT rule in FORWARD chain

---

.gitignore
Makefile
net/if.go
net/route.go
prog/weaveexec/Dockerfile
prog/weavehosts/weavehosts.go
prog/weaver/main.go
prog/weavewait/main.go
proxy/create_exec_interceptor.go
proxy/start_container_interceptor.go
test/666_the_beast.sh
weave

Also move the implementation of proxy rewriting /etc/hosts into the `weave` script, to guarantee it gets done before the interface is marked up.
Fixes #1209. Fixes #1258. Fixes #1300.

Wait for ethwe via netlink, not via polling or signals

---

proxy/create_container_interceptor.go
proxy/create_exec_interceptor.go
test/600_proxy_docker_py_test.sh

Docker-py was changed upstream to run using a test harness Pytest.
Also I have seen some failures due to the 'busybox' image not being found on the test host.

Fix docker api proxy smoke-tests after docker-py change (on 1.0 branch)

---

test/600_proxy_docker_py.sh

Docker-py was changed upstream to run using a test harness Pytest, but this wants the tests named in a slightly different way.

Fix docker api proxy smoke-tests after docker-py change

---

test/600_proxy_docker_py.sh

Previous one was only catching TestFoo, not FooTest. Python uses both.
~~Will expose a broken the test.~~
Found in https://github.com/weaveworks/weave/pull/1367
Depends on #1367

Looser docker-py test matcher for parallelization

---

site/features.md
site/ipam.md

Missed from #1200.
The phrase "The same IP range must be used everywhere" does not seem appropriate in that paragraph - if the user has multiple disjoint sets of containers they do not need to follow this advice -- so I dropped it.

Update docs for mixed manual and automatic IP allocation

---

Makefile
bin/release
docs/release-process.md

This PR refactors the `bin/release` script to have three steps:
````
bin/release build
bin/release draft [--pre-release]
bin/release publish
````
The second step creates the GitHub release in draft state, optionally marked as pre-release; the final step removes the draft state (making the release visible to the outside world) and updates latest in {Git,Docker}Hub only if the pre-release attribute is missing.
* The previous implementation used `git-describe` with a `--match=v*` to find the most recent version tag. To support non-mainline releases I've had to remove all the 'v' related logic with three consequences:
* The version in the changelog must match the exact tag name. For mainline releases it must include the 'v' prefix, which is not currently the case
* With no prefix to search …

Support draft and pre-releases in `bin/release`

---

site/weavedns.md
test/240_dns_add_name_test.sh
weave

  Make address argument to `weave dns-{add|remove}` optional

---

prog/weaveproxy/main.go
proxy/common.go
proxy/create_container_interceptor.go
proxy/create_exec_interceptor.go
proxy/inspect_container_interceptor.go
proxy/inspect_exec_interceptor.go
proxy/json.go
proxy/proxy.go
site/proxy.md
test/605_proxy_inspect_test.sh
weave

To return the weave ip/mac for docker inspect calls.
Fixes #117, and #1199 (possibly? Anything else outstanding for that?)

[proxy] add --rewrite-inspect flag

---

proxy/common.go

Fixes #1390
Note that setting both `--memory` and `--memory-swap` is done to avoid Docker issuing a warning that it can't set the swap limit.

Stop marshalling numbers as floats

---

bin/release
docs/release-process.md

Script now infers release type (mainline, branch or prerelease) from the version tag and adjusts its behaviour accordingly. The `--pre-release` option to `bin/release draft` has also been removed in favour of the new inferencing mechanism.
Fixes #1383.

Only update DockerHub `latest` images on mainline release

---

Makefile
router/utils.go

FIxes:
```
go get ./prog/weavewait
go install net: open /usr/local/go/pkg/linux_amd64/net.a: permission denied
make: *** [prog/weavewait/weavewait] Error 1
```
And:
```
link: warning: option -X main.version git-4c6a8f29c0ea may not work in future releases; use -X main.version=git-4c6a8f29c0ea
```
TODO:
- Update circle to install go1.5

Make Weave build & work with Go 1.5

---

prog/weaveproxy/main.go
weave

Report the proxy version instead of weaveexec version. That way we no longer rely on the weavexec image version tag, which may not always be present. Since the proxy is embedded in the weaveexec image, this effectively versions the image.
Also report the *local* script version instead of the embedded script version. There is no point in reporting the latter since it will always match the weaveexec version.
Closes #1341.

correctly report snapshot versions

---

test/170_ip_reuse_test.sh
weave

Previously we'd only do that when the container had no ethwe at the start. Therefore adding a recycled IP address to an already attached container would not send out an arp update for that IP, which would break connectivity to that IP for containers which had previously accessed that IP.
Fixes #1405.

always arp_update new addresses in 'attach'

---

Vagrantfile
test/Vagrantfile
vagrant-common.rb

Replacement for #1428, now targetted at 1.1 branch.
Docker 1.8+ uses a new package name (docker-engine) and repo configuration. This PR updates the build and smoketest Vagrantfiles with the new settings to get the latest release of Docker (currently 1.8.2)

Update docker repo, keys and package name

---

ipam/allocator.go
ipam/allocator_test.go

to avoid mis-indexing when more than one op is removed
Fixes #1424

Use explicit index into operations slice in cancelOpsFor()

---

.gitignore
Makefile
prog/docker_tls_args/main.go
prog/weaveexec/Dockerfile
site/boot2docker.md
site/proxy.md
weave

Fixes #1285
If there is no `-H` or `--tls*` set by the user, we get docker's TLS args via `/proc/<docker-pid>/cmdline`, and use them.
I'm not really sure of a better way to test, as it requires rebooting the remote docker daemon. So if the test exits abnormally there might be no docker daemon running on that host (or one with TLS), and interacts badly with different tests hosts methods of booting docker. (GCE vs vagrant)
@rade feedback, please?

Proxy TLS autoconfiguration

---

README.md

The intention is to use this as the single authoritative source of ECS AMIs, which right now are scattered around making them difficult to maintain.
@abuehrle Please review

Document ECS integration

---

proxy/proxy.go

If ContainerStarted fired before the response handler, then the "waiter"
chan would be nil, and the response handler would hang.

[proxy] fix race condition when waiting for containers to start

---

ipam/allocate.go
ipam/allocator.go
ipam/claim.go
ipam/http.go
weave

Make IPAM return a simpler message and have the weave script check for that message and exit with status 0, so the proxy does not print any error message.
Fixes #1418
(replacement for #1425 which was against master not 1.1)

Handle cancelled allocation in 'weave attach'

---

weave

Instead of duplicating most of the code, just inject an arg that has the same effect.
We lose a more specific error message when IPAM is disabled, but this seems like a niche interest.
Also, replace the `while [ $# -gt 0 ] ... shift` loop with a `for`.

Simplify ipam_cidrs function in weave script

---

prog/weaveproxy/main.go
proxy/proxy.go
weave

[proxy] use a container-local unix socket to get the address, instead of logs

---

build/build.sh
circle.yml
test/image/Dockerfile
test/image/test.sh

Run tests in a separate container.

---

test/690_proxy_autoconfig_test.sh
weave

Change default unix listener to `unix:///var/run/weave/weave.sock`, and always make a symlink from `/var/run/weave.sock` to `/var/run/weave/weave/sock`
Fixes #1455. Pretty ugly hack, but...
Not sure if there's a good way to test this which represents something a user would do/care about, but when I've broken it 690 has failed, so...

[proxy] unmount /var/run after boot, so the kernel can GC veth pairs

---

proxy/start_container_interceptor.go
test/666_abuse_of_start_test.sh
test/config.sh

[proxy] Handle null HostConfigs gracefully in start

---

nameserver/entry.go
nameserver/nameserver.go
test/245_dns_case_insensitive_test.sh
test/config.sh

DNS lookups should not be case sensitive.

---

site/proxy.md
test/690_proxy_autoconfig_test.sh
weave

It was left in for backwards compatibility, in 1.1.
This resolves #1492

Remove /var/run mount from exec_remote. Proxy uses /var/run/weave/weave.sock

---

router/connection_maker.go
router/status.go

If a connection gets through all the handshake and subsequent checks - i.e. it ends up getting added to the LocalPeer's connection list - but gets terminated within one minute (of the start of the successful connection attempt), then we apply the existing backoff logic to schedule a retry, instead of retrying immediately.
In order to do this we retain the 'Target' data structure for such connections, marking it as 'connected' instead of deleting it (as we did previously).
Fixes #953.

backoff late connection failures

---

weave

Apparently kernel 4.2 adds these, which breaks `weave reset` when we pass the names to `ip link del'.
Fixes #1364.

strip off @... from interface names returned by `ip link show`

---

test/510_detach_hide_no_ipalloc.sh
weave

Instead of POSTing to IPAM in order to obtain IPs, we GET existing IPs. We ignore 404s, so detaching/hiding remains idempotent.
Fixes #860.

don't allocate IPs on 'detach' and 'hide'

---

ipam/allocator.go
ipam/ring/ring.go
test/180_ipalloc_seed_mismatch_3.sh

This is an early detector for a multitude of other symptoms, some of which cause panics.
When creating the ring we record the paxos-supplied normalised list of peers used for seeding. This subsequently gets gossipped around as part of the Ring data structure, and checked in ring.Merge that it is the same for the recipient.
There are some subtleties due to the desire to maintain backward compatibility and deal with empty rings
- The gossip gob decoder will ignore the Ring.Seeds field when an old weave receives a Ring from a new weave. So everything on the old weave will just continue to work as before.
- The gossip gob decoder will set the Ring.Seeds field to nil when a new weave receives a Ring from an old weave. We therefore omit the seed equivalence check when the received Seeds slice …

detect when IPAM has been seeded by different peers

---

proxy/common.go
proxy/create_container_interceptor.go
proxy/create_exec_interceptor.go
proxy/inspect_container_interceptor.go
proxy/inspect_exec_interceptor.go
proxy/json.go
proxy/json_test.go
proxy/proxy.go
proxy/start_container_interceptor.go

That way we are less likely fall victim to go-dockerclient, or the API changing.
Fixes #1371

[proxy] all request modification is done through map[string]interface{}

---

prog/weaver/main.go
proxy/common.go
proxy/proxy.go
router/connection.go
router/consts.go
router/fastdp.go
router/flow.go
router/local_peer.go
router/mocks_test.go
router/odp.go
router/overlay.go
router/overlay_switch.go
router/peer.go
router/peers.go
router/peers_test.go
router/protocol.go
router/router.go
router/routes.go
router/sleeve.go
router/utils.go
test/190_no_fastdp_2_test.sh
weave

Smoke tests pass (modulo the one that is broken on master), so I think this is fit for a review pass.
Things still to do:
* The `weave` script changes are still a bit grotty.  But...
* I think there needs to be a "disable it all" option to weave, which disables fastdp, `--net=host`, and the MTU change.
* I haven't modified architecture.txt. To be honest, most of the contents are more like implementation notes that belong as comments in the code.  If the fast datapath code requires additional notes of that nature, I'd be happy to add them as comments. A high-level overview of fast datapath would be a good thing, but I think I'll need to re-write the whole of architecture.txt to match.
* 1.1 compatibility support.  That will be a separate issue.  Short ids is the tricky part here.
* I need …

Fast datapath

---

prog/weaver/http.go
router/fastdp.go
router/overlay.go
router/overlay_switch.go
router/sleeve.go
router/status.go

This is a replacement for #1513 that is targeted against master.
Fixes #1505.

Fast datapath weave status

---

test/650_proxy_env_test.sh
weave

The echo in proxy_addr was not preserving newlines, so the multiple
addrs were all getting returned.
Fixes #1527

[proxy] Fix bug in weave env/config when passing multiple -H flags

---

proxy/common.go

Fixes #1515 
Simply added to debug-level logging, to avoid the added complexity of a new command-line flag to turn this on.
Thanks to @tomwilkie for the implementation

Print request and response json when debugging weaveproxy

---

site/features.md
site/troubleshooting.md

This is a replacement for #1510 that is targeted against master.

Document fast data path feature

---

prog/weaver/main.go
router/connection.go
router/fastdp.go
router/flow.go
router/overlay.go
router/overlay_switch.go
router/pcap.go
router/peer.go
router/peers.go
router/router.go
router/sleeve.go

This is stacked on top of the fdp-rebase branch, so should not be merged until after #1438.
Addresses #1448.  Compatibility with 1.1 is intended to "just work", so that we won't need to explain any special procedure for doing rolling upgrades to 1.2.

Fast datapath compatibility with 1.1

---

site/weavedns.md
test/240_dns_add_name_test.sh
weave

...by omitting the container name
We associate non-container dns entries with 'weave:extern' because typically these entries will refer to external (non-weave) IP addresses. 'weave:extern' also happens to be the same length as the existing 'weave:expose' pseudo-container, which is desirable for 'weave status dns' output layout.
Fixes #1385.

`dns-{add,remove}` can add/remove non-container DNS records

---

proxy/proxy.go
test/640_proxy_restart_reattaches_test.sh

Fixes #1547.
First commit stops it killing containers when restarting the proxy.
Second adds a first pass at an attachment retry mechanism. Thoughts on that? I need to have a think about how to test it.

Proxy restart shouldn't kill containers

---

proxy/common.go
proxy/proxy.go
test/640_proxy_restart_reattaches_test.sh
weave

This is a follow-on to #1210, that fixes part (a) in #401
Replacement for #1359 which was against a different branch.
You get a bit of noise in the logs on a total restart (e.g. a reboot), because the router isn't necessarily up and listening before we start re-attaching other containers.  But it all works out in the end, because the router attach re-does all the parts that went wrong.

Get proxy to re-attach weave router if it restarts

---

weave

'weave --local create-bridge' is not compatible with fastdp

---

router/mac_cache.go
router/router.go

When we get a forwarded packet, we put its source MAC into the MAC cache,
overriding any existing entry.  But we could have a flow which says
to forward packets destined to that MAC based on the old entry.  Such
a flow could be prolonged indefinitely by attempts to send to the MAC.
This is obviously bad, so do InvalidateRoutes in such cases.

Do InvalidateRoutes when a forwarded packet updates a MAC cache entry

---

proxy/proxy.go
proxy/start_container_interceptor.go
test/695_proxy_failure_modes_test.sh

With the new ContainerStarted method were not returning the error back to the requesters.
While fixing it, I believe I found another race condition in the same code, so I've included a fix for that, also. (race condition is documented in the commit).
Fixes #1542

Fix weaveproxy silently breaking when weave not running

---

proxy/common.go
proxy/proxy.go

Use the container name in addition to the entrypoint to avoid triggering reattachment unnecessarily.
Fixes #1584.

Improved detection of router container restart

---

nameserver/dns.go
nameserver/dns_test.go

Fix unit test breakage caused by https://github.com/miekg/dns/commit/2d2c2ebcfc8f39f0393c32b2728e7757abc93761

Update unit test for miekg DNS API change

---

prog/weaver/main.go
router/odp.go

It's possible to build that kernel with openvswitch, and vxlan, but
without the vport_vxlan module that glues them together.  And at
least one distro has actually done this.
Addresses #1599.

Probe whether the kernel has ODP vxlan support

---

nameserver/entry.go
nameserver/entry_test.go
nameserver/nameserver.go
nameserver/nameserver_test.go
testing/gossip/mocks.go

Instead of sorting when creating the outbound GossipData object, we sort in `Encode()`.
Fixes #1603 and #1610
Since the extended unit tests revealed that it is expensive to re-compute `ToLower()` every time we look at a hostname, this PR also changes this to compute the lower-case version on entry to the data structure and hold on to it thereafter.
(replacement for #1611 which was against the wrong branch)

Hold DNS entries sorted case-insensitively until just before sending

---

site/features.md
weave

Prevent containers from accessing the weave router control port when fast datapath is in use.
Fixes #1632.

Bind router HTTP listener to localhost when fastdp enabled

---

net/address/address.go
site/ipam.md
site/troubleshooting.md

Drop use of interval notation when printing ranges

---

test/640_proxy_restart_reattaches_test.sh

Temporary band-aid for #1588 
It is suspected that Docker 1.9 fixes the underlying unreliability.  We will test that theory soon, after the initial post-release dust has settled.

Disable restart of docker in test 640

---

router/connection.go
router/local_peer.go
router/peers.go

Previously when a peer restarted, information about the new incarnation (i.e. with a different UID) was not accepted by other peers (and connections would be dropped) unless all knowledge of the
previous incarnation had been purged. This could result in a lot of connection churn and hence connectivity disruption, and, in some pathological cases, very slow convergence and hence acceptance of the new incarnation into the network.
We now no longer drop connections when encountering different incarnations of a peer. There are two situations when that can happen:
1) on connection establishment
we simply proceed
2) on receipt of gossip
to ensure convergence we
a) treat the UID as an additional discriminator when deciding whether we should update our information about a peer with that which was …

better convergence when peers restart

---

prog/weaver/http.go
prog/weaver/main.go
router/connection.go
router/fastdp.go
router/network_overlay.go
router/network_router.go
router/network_router_status.go
router/overlay.go
router/overlay_switch.go
router/router.go
router/sleeve.go
router/status.go

This is a preparatory step for extracting the control plane as a generic communication substrate into a separate package ('mesh').
The control plane shouldn't have to know what it is being used for, i.e. in our case creating an overlay network. We therefore introduce a more generic notion of an Overlay - something that hooks into the lifecycle of control plane connections and buddies them up with its own logical (or real) OverlayConnections. For weave we then have a specialised NetworkOverlay which represents a data plane, i.e. it knows about (i.e. has methods for) packet forwarding.
There is a similar separation at the Router, i.e. there is a generic control plane Router, and more specialised NetworkRouter - the latter knows about packet capture and forwarding.

separate the control and data planes

---

common/odp/odp.go
prog/weaver/main.go

Makes them easier to re-use from another project

Move ODP helper functions out to their own package

---

router/fastdp.go

Forward can return nil if the remote peer has HasShortID false.  That
can happen if we learn about a 1.2 peer from a 1.1  peer and attempt to
connect to it.
This change just fixes the panic.  HasShortID will never be set, so we'll
fall back to sleeve.  But if that occurs, if can be fixed by a restart of
the affected routers.
Addresses #1661.

Handle the case where Forward returns nil

---

weave

It doesn't need it since the task of rewriting `/etc/hosts` moved to the `weave` script where the same directory is bind-mounted again.
Fixes #1647 and #1666

Remove containers directory bind-mount from proxy

---

net/if.go
net/route.go

Now we are only using the higher-level `netlink` library, not the lower-level `netlink/nl`.
Closes #1440

Move some netlink code to upstream library

---

site/proxy.md
weave

[proxy] add --no-detect-tls flag, and proxy always tries to detect TLS.

---

test/690_proxy_config_test.sh
weave

This lets you use -H unix://*.sock outside /var/run/weave.
The giant gotcha is that if you use `-H /var/run/foo.sock`, you will reintroduce the bug with
namespaces not being GCed. We could make passing a socket in `/var/run`, an error...
Still working on the test...
Fixes #1579

[proxy] dynamically mount -H dirs into the proxy when launching

---

ipam/allocator.go
mesh/gossip.go
mesh/router.go
mesh/surrogate_gossiper.go
nameserver/entry.go
nameserver/entry_test.go

The same piece of `GossipData` can be shared and subject to different `Merge` operations. We either need to copy the data when we share it, or create copies on modification, i.e. copy-on-write.
We choose the latter, since it is more efficient and there is just one mutating operation.
Fixes #1697. Fixes #1450. Fixes #1452.

make GossipData immutable

---

site/proxy.md

Need to manually merge `latest_release_doc_updates`->`1.3`->`master` after PR merge.
Fixes #1693.

Fix erroneously hyphenated Docker TLS arguments

---

Makefile
README.md
build/Dockerfile
proxy/proxy.go
site/building.md
test/README.md
weave

Fixes #1683; replaces #1701 which was against wrong branch

Raise minimum Docker version to 1.6

---

proxy/proxy.go
test/650_proxy_env_test.sh
test/690_proxy_config_test.sh
test/gce.sh
weave

Uses approach 1 to fix #1694
Comments on approach vs 2, would be great.

Automatically symlink /var/run/*.sock sockets to /var/run/weave/*.sock

---

router/fastdp.go

Get some stats for `weave report` when using the FDP. This prints the number of _upcalls_ (ie, misses) as well as the number of flows in the datapath.
Fixes #1592

Add FDP miss counter to reports

---

weave

Forbid traffic to the Weave port from containers

---

ipam/ring/ring.go
ipam/status.go
prog/weaver/http.go

[WIP] Show some IPAM stats with "weave status ipam"

---

mesh/peers.go

This was missing.
There are two parts to this change:
1. updating the Peers.byName mapping when HasShortID changed (in addition to the existing update on ShortID change). We need to be careful about the sequencing here - both ShortID and HasShortID must be set between the calls to deleteByShortID and addByShortID, since the former is meant to delete the existing entry (hence use the old values) and the latter add the new entry (hence use the new values).
2. update a peer when the received info has the same version and UID but the current record has HasShortID=false, and the received info has HasShortID=true. This caters for the case where we receive an update about a weave 1.2+ peer first via a pre-1.2 peer (which does not transmit ShortIDs, and always sets HasShortID=false) and …

update Peer.HasShortID as part of topology merge

---

weave

Modify the weave script to interpose an intermediary bridge netdev between application containers and the OVS datapath. Fixes #1577.

Optional intermediary bridge netdev

---

Makefile
prog/weaveexec/Dockerfile
prog/weaveexec/symlink
prog/weaveproxy/main.go
proxy/proxy.go
test/650_proxy_env_test.sh
test/690_proxy_config_test.sh
weave

Needs an in-depth review, please.
We copy docker.sock owner to symlinks. Permissions are not copied,
because the permissions will inherit from the target.
Fixes #1694, using option 2 (having the proxy create the symlinks). If the weave script creates the symlinks, `weave env` would break (unless we passed the symlinks in, and that's awkward).
There is a slight change in behaviour of `weave env`. New order of preference is: tcp sockets, custom unix sockets, then `/var/run/weave/weave.sock`.
Most of the awkwardness/code in this is just to run a docker container. :disappointed:
Happy to refactor, any suggestions on ways to clean up the code would be great.

[proxy] Symlink sockets to /var/run/weave/weave.sock from inside the proxy

---

weave

remove CLIENT_TLS_ENABLED and DOCKER_CLIENT_TLS_VERIFY, as they're unused

---

mesh/local_peer.go
mesh/peer.go
mesh/peers.go
mesh/router.go

When encountering an unknown peer in received gossip, rather than ignoring the entire gossip we create a placeholder Peer. This has version 0 and uid 0, which means it will be replaced by any complete peer information subsequently received via gossip.
Not ignoring the gossip results in quicker convergence.
We also no longer need to broadcast about the remote peer when adding a connection, since we only did that in order to reduce the occurrence of `UnknownPeerError`s. Not needing to do this is is more efficient, since the broadcast was strictly redundant.

remove UnknownPeerError for quicker convergence and efficiency

---

Makefile
test/setup.sh

Building outside the container was breaking the CircleCI build, because CircleCI was variously running Go 1.4 and 1.5.1 which didn't match the build container.
This also saves ~3 seconds on every run of test/setup.sh

Move test/tls program into Makefile so it builds inside the build container

---

ipam/http_test.go
mesh/gossip_test.go
nameserver/nameserver_test.go
testing/util.go

It breaks stack traces on failure.
We can just rely on running `go test -timeout ...` instead, which we already do in tools/test.

ditch RunWithTimeout test helper

---

mesh/gossip_test.go

Real `Connection`s do not process gossip until after `LocalPeer.AddConnection`. `mockChannelConnection` wasn't behaving in that way, which resulted in some sporadic test failures since it would cause some gossip to get processed too early, which in turn would trigger gc of some of the just-received peers, which we would then find missing in the test assertions.
To fix this we introduce a latch on `mockChannelConnection` which closes when the remote end is ready to receive gossip. Effectively this emulates the entering of `LocalConnection.receiveTCP` after the call to `AddConnection` completes.
Unfortunately an open latch will cause `sendPendingGossip` to block. We get around that by abandoning checks in "half-connected" connection states.
Fixes #1765.

better emulation of connections in gossip tests

---

mesh/connection.go
mesh/router.go
mesh/status.go
prog/weaver/http.go
prog/weaver/main.go
router/fastdp.go
router/overlay_switch.go
site/features.md
site/troubleshooting.md
test/110_encryption_2_test.sh
test/115_optional_encryption_2_test.sh
weave

This PR adds support for optional encryption via the `--trusted-subnets` argument to `weave launch`. Whilst the control plane is always secured when a password is specified, peers will forego authenticated encryption on the overlay (data plane) connection between them only if both consider the other to be located on a trusted subnet.
I recommend that the commits are reviewed individually in sequence; most commit messages contain further explanatory text.
Fixes #82, #1788.

Optional encryption

---

weave

Prefix interface names with 'veth' so NetworkManager ignores them

---

Makefile
common/docker/client.go
prog/plugin/main.go
prog/weaveproxy/main.go
prog/weaver/main.go
proxy/common.go
proxy/proxy.go
test/650_proxy_env_test.sh
test/690_proxy_config_test.sh
test/gce.sh
vagrant-common.rb
weave

First part of fixing #1586.
Need to check it works with the plugin, and `DOCKER_HOST=tcp://*` as well. Any docker invocations I've missed, that need `DOCKER_HOST` passed in?

Support weave script running against non-standard DOCKER_HOST

---

docs/fastdp.md

Add fast datapath high level overview

---

test/280_with_or_without_dns_test.sh
test/config.sh
weave

Also deprecate --with-dns option to 'weave run'; since we were documenting this option until recently it seemed fairer to deprecate it than to take it out completely.
Doc change is in 1d9ef76080116194c904420b4a4adf639d2ca9cc on latest_release_doc_updates
Fixes #1748

Remove WITH_DNS variable from weave script

---

common/docker/client.go
prog/plugin/main.go
prog/weaver/main.go
proxy/proxy.go
site/plugin.md
weave

If Docker perceives "active endpoints" on a network, it will attempt to contact the driver about them, and if you've shut down the plugin then this will time out.  So if you get into this state the best thing to do is restart the plugin.
This is particularly bad on a restart of Docker (e.g. on host reboot), when Docker may never get going, hence leave you unable to start the plugin.

Warn user if weave network is in use on stop or reset of plugin

---

prog/weaveproxy/main.go
weave

Issue a warning on --with-dns option to proxy, because it was removed

---

test/650_proxy_env_test.sh
weave

Fixes #1820, at the cost of some flexibility: if `$DOCKER_HOST` is set to `tcp:xxx`, then the remote Docker must also be listening on the standard `/var/run/docker.sock`.
Previously it would work if `$DOCKER_HOST` pointed at a non-TLS TCP socket.  But those are [discouraged](https://docs.docker.com/engine/articles/security/#docker-daemon-attack-surface).

Only pass $DOCKER_HOST if it is a Unix socket

---

weave

so that `weave $(env --restore)` does the right thing regardless of how many times `eval $(weave env)` was invoked previously.
Fixes #1824.

make `eval $(weave env)` idempotent

---

weave

don't complain in `weave stop` when plugin is not enabled

---

prog/weaveproxy/main.go
proxy/proxy.go

First experimental pass at having the proxy retry attaching containers if the attach fails.
Nice to haves:
* Detect if there are causes where a container will *never* successfully attach, and handle those.
* Some sort of back-off
* Should also combine multiple requests to attach the same container (by name or id).
Fixes #1556

Proxy retry attaching containers

---

common/docker/client.go
ipam/allocate.go
ipam/allocator.go
ipam/allocator_test.go
ipam/claim.go
ipam/status.go
nameserver/nameserver.go
plugin/net/watcher.go
proxy/proxy.go
site/features.md
test/100_cross_hosts_2_test.sh
test/640_proxy_restart_reattaches_test.sh
weave

This fixes #1047, without any special reference to the restart command, because the same container ID will get back the same address as long as you start/attach it within the timeout window of 5 seconds.
Perhaps the timeout should be configurable?

Don't delete record of IP allocation immediately after container death

---

prog/weaver/main.go
router/bridge.go
router/fastdp.go
router/pcap.go

There is one behavioural change in this: the routerName, if not specified with --name, is now derived from the datapath network interface MAC (for --datapath) or the pcap interface MAC (for --iface). Previously it was only derived from the latter. So this removes an awkward asymmetry.
This doesn't actually make any difference to weave usage, since the script always supplies a --name.

refactor overlay creation

---

prog/plugin/main.go
prog/weaveutil/main.go
prog/weaveutil/plugin_network.go
site/plugin.md
weave

The main gotcha is that we lose the ability to specify a different mesh network name, or disable it altogether. That was always poorly supported and IMO is not worth losing sleep over until we / our users have a real need for it.
Closes #1897.

move plugin network creation/removal into weaveutil

---

net/if.go
net/route.go

...and bypass `netlink.LinkByIndex`.
Fixes #1909.

cope with errors during route traversal

---

Vagrantfile
test/Vagrantfile
vagrant-common.rb

Vivid is EOL on the 4/2/2016 and [there will be no Docker 1.10 packages for it](https://github.com/docker/docker/issues/19451).

Update Vagrant to use Wily 15.10

---

Makefile
circle.yml

That way a plain 'make' works out-of-the-box.
Fixes #1893.

move smoke test dependencies from 'all' to 'testrunner' target

---

test/690_proxy_config_test.sh
test/695_proxy_failure_modes_test.sh

docker/docker#14012 changed the exit codes returned by the docker client under certain circumstances; update the tests to accomodate.
NB don't merge until the CI infrastructure is switched over to 1.10.

Fix smoke tests for docker 1.10

---

api/ipam.go
plugin/ipam/driver.go
site/plugin.md

Fixes #1806 
It is perhaps cheating to get Docker to store the info we need, smuggled inside the pool name.  But I don't see any reason why it should break.

Support subnet and iprange arguments on network create

---

plugin/net/driver.go

Fixes #1803.
By moving endpoint creation into `CreateEndpoint` we can return the MAC address at the time Docker expects.  We find the endpoint later simply by looking it up with the same name, derived from the endpoint ID.
The third commit changes from using 5 chars from the endpoint-ID to using 8, to reduce the chance of collision from ~1/1000 to ~1/64K.  This is not backwards-compatible, e.g. if you stop/upgrade/start the plugin it will log a warning and leak the veth when asked to remove an endpoint, but it is believed the impact on users at this point will be minimal.

Refactor plugin to create veths in CreateEndpoint

---

test/810_plugin_router_restart.sh
weave

Fixes #1745
Veths created via the plugin will have a name like 'ethwe0'; previously we only looked at the device named exactly 'ethwe'. 
Covers `weave ps` and reclaim of addresses for IPAM and WeaveDNS.
Code now bails out in `container_ip_addr_show` if the container is in the host netns, otherwise it takes a while pondering all the devices visible at top level.

Make weave script scan veths with prefix 'ethwe'

---

plugin/net/driver.go
prog/plugin/main.go

We don't seem to be using it. 
Extracted from #1738 to simplify it; this change can be applied at a later date.

Remove 'nameserver' option from plugin

---

prog/weaveexec/Dockerfile
test/config.sh
weave

Fixes #1757
- Create an auxilliary container 'weavevolumes' to hold the '/w/w'
files, and map into that instead of creating new volumes every time.
- Show "/bin/false" as its command in `docker ps` instead of
"/home/weave/sigproxy".
- Remove volumes when cleaning up smoketest containers.
Replaces #1792 to change target branch - some discussion on design there.

Reduce docker volumes for weavewait to just one set per release

---

prog/plugin/main.go

Fixes #1934.
Note part of #1901 will need to be re-done for the merge to master.

Remove Unix domain sockets on shutdown

---

test/610_proxy_wait_for_weave_test.sh
weave

This was causing container entrypoints to execute too early, e.g. before the interface had been given an IP address. But only when running with `--no-multicast-route`, since otherwise weavewait is
waiting for the multicast route to appear.
Fixes #1942.

don't set the interface 'up' before it is fully configured

---

plugin/ipam/driver.go
plugin/skel/listener.go

Fixes #1906.
When I did just the simple fix, I got "invalid CIDR address" back from Docker, which suggested the error wasn't being propagated correctly, hence the other two commits.

Return an error when weave isn't running, on RequestPool

---

api/weaveapi.go
bin/multiweave
plugin/ipam/driver.go
plugin/net/driver.go
plugin/net/watcher.go
prog/plugin/main.go
prog/weaver/main.go
proxy/common.go
proxy/proxy.go
router/sleeve.go
test/190_no_fastdp_2_test.sh
test/gce.sh
weave

Fixes #1589,#1746.
~~This PR currently depends on an as yet unmerged change in mesh (weaveworks/mesh#5); that should be merged first and this PR rebased accordingly.~~

Always use host netns

---

.gitmodules
common/utils.go
prog/weaveproxy/main.go
prog/weaveutil/addrs.go
prog/weaveutil/main.go
proxy/common.go
proxy/json.go
proxy/proxy.go
weave

The proxy currently invokes `weave ps` to rewrite docker inspect network settings; this PR retrieves the IPs from the weave interface directly with netlink.
Partially addresses #1940.

Use netlink instead of shelling out to `weave ps`

---

ipam/ring/ring.go
ipam/ring/ring_test.go

Begun while investigating #1946; wasn't actually related but contributed here to improve code coverage.
The test for `ring.ClaimForPeers` doesn't do any special checks, relying on `checkInvariants` which is called via `defer`

Improve IPAM Ring unit testing, and streamline ring.ClaimForPeers

---

ipam/allocator.go

In IPAM, resurrect apparently-dead containers on ContainerStarted event

---

ipam/ring/ring.go
ipam/ring/ring_test.go

Addresses one of the points raised in #1949

Make error messages on ring merge clearer

---

net/if.go

Wait for multicast route on any interface, to match the weave script which only adds a route if there isn't one already.
Fixes #1956

Wait for multicast route on any interface

---

prog/plugin/main.go

Fixes #1959.
This code was originally added because leaving the weave network in-situ while Docker restarted would cause errors and delay Docker startup.  Unfortunately, somewhere along the line to Docker 1.10 the opposite situation came into effect, only it's now much worse.
The weave script already tries to remove the `weave` network on `stop` or `reset`, so this extra call should be unnecessary - we start the plugin with `--restart=always` so it should come up after Docker restart.

Don't remove weave network on plugin shutdown because it bricks Docker 1.10

---

weave

In order to continue progressing #1940 in an incremental fashion, we need to reimplement `create_bridge` in the weave script with weaveutil. Unfortunately `weave create-bridge`, intended for use when docker _isn't_ running (so that users can configure docker to use weave's bridge), relies on this function; consequently we need to provide another way for such users to continue using weave for L2 bridging between docker bridges. This PR implements `weave attach-bridge` for linking an existing `docker0` bridge netdev with the weave bridge, obtaining the same functionality; furthermore, it has the advantage of working with fast datapath, which the previous `create-bridge` method did not.

'attach-bridge' feature to link an existing bridge netdev with the weave bridge

---

weave

#1955 introduced *three* bugs:
* `weave reset` did not clean up veth pairs created by `weave attach-bridge`
* `weave reset` did not clean up iptables rules inserted by `weave attach-bridge`
* `weave attach-bridge` was not idempotent in terms of iptables rules creation

Fix attach-bridge bugs

---

weave

Invoke the new create_veth from a few places, eliminating code duplication and inconsistencies.
Semantic differences:
- init_bridged_fastdp now skips the veth creation/config if the veth
already exists. This eliminates routing blips. Though in reality
something very strange must have happened to end up in this code
with an existing veth.
- init_bridged_fastdp no longer deletes the $BRIDGE and $DATAPATH when
veth creation/configuration fails. This is consistent with
init_bridge, which does not delete $BRIDGE when something goes
wrong. And it is generally desirable since the init_* functions are
invoked on potentially existing bridges - e.g. following 'weave
stop'.
- attach_bridge and setup_router_iface_bridge used to mark one veth
end 'up', then invoke add_iface_* for it, and then mark the …

"refactor" veth creation

---

.gitmodules
Makefile
db/boltdb.go
ipam/allocator.go
ipam/testutils_test.go
prog/weaver/main.go
test/162_persist_ipam_2_test.sh

Revised version of #1928, with BoltDB specifics pulled out to a separate package.
We have a very simple persistence interface, just `Load` and `Save` an `interface{}`, with serialization (Gob) hidden behind the abstraction.
Partial fix of #678

Persist IPAM ring, take 2

---

plugin/ipam/driver.go

Add two functions required by ipamapi "contract"

---

weave

...and WEAVE_NO_FASTDP isn't set.
Fixes #1929.

don't complain on relaunch when ODP is not supported

---

ipam/allocator.go

We can have outstanding allocations for different ranges owned by different peers, so we should not short circuit after the first space request.
Fixes #1996.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/weaveworks/weave/2001)

Try all pending allocations

---

Vagrantfile

Otherwise it will always install the latest docker version, which will be
undesirable when new major releases are done, until they are well tested.
For instance, docker 1.9 was killing my VM when spawning a kubernetes cluster,
due to a high CPU consumption, probably due to
https://github.com/docker/docker/issues/17720
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/weaveworks/weave/1672)

Pin docker version in vagrant VM

---

ipam/allocate.go
ipam/allocator.go
ipam/allocator_test.go
ipam/claim.go
ipam/http.go
ipam/http_test.go
ipam/status.go
ipam/testutils_test.go
net/address/address.go
prog/weaver/main.go
weave

Partial fix for #1655 
The missing piece is having the proxy recover the addresses on restart.  Currently the proxy acts via `weave attach`, so we would need a variant of that to retrieve all addresses from IPAM.

Store all addresses+subnets in IPAM

---

ipam/allocator.go
ipam/paxos/participant.go
ipam/status.go
prog/weaver/main.go
site/ipam/overview-init-ipam.md
test/125_observers_cant_vote_3_test.sh
test/126_observers_can_call_election_3_test.sh

Initial PR to provoke design discussion on the following points:
1. I have used a `gossipState` ring update message where both `Ring` *and* `Paxos` are `nil` as a way for non-electors to poll their peers for a ring - are we happy with that, or would a separate message type be preferable
2. Most of the changes to `allocator.go` (various `alloc.paxos != nil` protections, introduction of `determinePaxos`) could be reverted if `paxos.Node` became an interface with electing and non-electing variants. The latter would implement null versions of `GossipState`/`Consensus`/`Propose`/`Update`/`Think` and `paxos.NewNode` could then be made to return the correct implementation based on the value of `quorum`
3. `--init-peer-count=0` isn't a great UI IMO; I would rather have something explicit like …

Support non-electing peers via --observer

---

api/weaveapi.go
prog/plugin/main.go
proxy/proxy.go

To reduce dependencies for other projects who decide to use the Weave Net API.  With this change, you have to pass in the logger you want to use when you create the `Client` object.
The `Logger` interface here is a bit arbitrary; the only function we are actually using is `Debugf`, but it seemed a bit weird to just have that one line.

Abstract out logging function from weave api package

---

weave

since the system uuid is not available on paravirtual EC2 VMs, and possibly other hypervisors.
Fixes #2021

fall back to hypervisor uuid for mac derivation

---

site/fastdp/fastdp-how-it-works.md
site/features.md
site/introducing-weave.md
site/router-topology/overview.md
site/using-weave/deploying-applications.md
site/using-weave/host-network-integration.md
site/using-weave/security-untrusted-networks.md
site/using-weave/service-export.md

Required by (the now misnamed) weaveworks/weave-guide-sync#1

Doc fixes required by updated WP markdown plugin

---

test/gce.sh

At the time of writing, this gives us Docker 1.10.3.

Bump template name so it will fetch latest Docker

---

weave

Fixes #2053
Return failure from various functions when sub-operation fails.
We cannot rely on `set -e` to fail the whole script in contexts where functions are called inside conditionals.

Fix missed errors in weave script

---

weave

This was missed from #1930.
Also rename function `attach_router` to `populate_router`, which describes the behaviour better.

Remove unnecessary netns change in attach_router

---

.gitmodules
Makefile
common/arp.go
common/utils.go
plugin/ipam/cni.go
plugin/ipam/driver.go
plugin/net/cni.go
plugin/net/driver.go
prog/plugin/main.go
site/features.md
site/plugin/cni-plugin-how-to.md
test/090_docker_restart_policy_2_test.sh
test/830_cni_plugin_test.sh
test/config.sh
weave

Fixes #1991 and #1992.
[CNI](https://github.com/appc/cni#cni---the-container-network-interface) expects to call an executable, which you name in your `/etc/cni/net.d/somenetwork.conf` file.  By default it looks in `/opt/cni/bin`
For the Weave plugin, `weave setup` creates a couple of scripts in `/opt/cni/bin` which run the plugin container with the necessary arguments, and also creates a configuration file `/etc/cni/net.d/10-weave.conf`.
If you do not configure an IPAM `type` in the configuration, the Weave CNI network plugin will call Weave IPAM directly.
If you don't want the overhead of a container execution on every plugin operation you can also use the Weave plugin executable directly, renamed:
- If you name it `weave-net` it acts as a CNI network plugin.
- If you name it …

Implement CNI plugin

---

site/ipam/stop-remove-peers-ipam.md
weave

This isn't as efficient as it could be. In particular we end up broadcasting the ipam state for every peer listed. To avoid that we'd have to change the HTTP API, and would no longer be able to use 'DELETE'. That is just not worth it.
Closes #2044.

make `weave rmpeer` accept a list of peers

---

nameserver/entry.go
nameserver/entry_test.go
nameserver/nameserver.go
test/215_stale_dns_3_test.sh

Fixes #1867 and #2023.
Also makes the merging of tombstones stable, where everything else is equal.

Override stale dns entries received via gossip

---

mesh/connection_maker.go
mesh/status.go

Fixes #2087 
We were removing the `cm.targets` entry because we had an incoming connection from that IP address, but that means we remove all knowledge of previous attempts so we will reconnect very quickly.
Leaving all "direct" targets in the `targets` set is a better approach: it is bounded (by the size of the direct peer list), and innocuous unless the connection is repeatedly failing.

Don't delete targets that seem invalid if they are 'direct' targets

---

ipam/ring/ring.go

Replacement for #2086 on 1.4 branch
Improves the behaviour seen in #2083 - instead of panicking, host2 now rejects the connection and logs the error.
It does reconnect rather rapidly, which is addressed by #2088.

Change invariant fail on Merge() from panic to error

---

weave

`WEAVEPLUGIN_DOCKER_ARGS` environment variable is used to pass custom args when creating plugin container
Our default docker log-driver is gelf (set via DOCKER_OPTS) and all containers send logs to logstash.
But we want weave logs to stay local and be accessible via `docker logs` command.
There are `WEAVE_DOCKER_ARGS` and `WEAVEPROXY_DOCKER_ARGS` variables, but no variable for plugin container.

Support custom docker args for weave-plugin

---

plugin/net/driver.go

Fixes #2097.
The error gets reported to the user like this:
```
$ docker run --net=weave --hostname=foo.weave.local -dti alpine /bin/sh
eb4c86806973513625b7e269a1711012896958ee3d46c21b129dde6a26db050c
docker: Error response from daemon: NetworkDriver.Join: failed to attach "vethwl73264" to device "weave": netlink error response: no such device.
```
Same in plugin logs.

fail plugin operation on bridge attachment error

---

ipam/allocator.go
ipam/paxos/participant.go
ipam/paxos/paxos.go
ipam/testutils_test.go
prog/weaver/main.go
test/700_status_and_report_test.sh

Do it by calling out into a function which has access to the list, rather than pushing updates in as suggested in #1721.
Fixes #1721 and #1881
The fix for #1881 is racy - if we decide to go for consensus before hearing back that the address refers to ourselves then we will still count ourself.

Use current target list to compute quorum

---

test/205_dns_disabled.sh
weave

...rather than exploding
i.e. the former returns nothing and the latter leaves naming related container settings untouched, just like happens in the proxy and plugin.
Fixes #2099.

make `weave dns-args` and `weave run` work with `--no-dns`

---

net/if.go
prog/weaver/main.go
router/fastdp.go

so that when the router container restarts after a reboot it waits for the proxy to create the datapath device, rather than dying.
Fixes #2113.

wait for datapath device to be ready

---

nameserver/entry.go

so we avoid the unnecessary gossip, and delayed convergence, that otherwise ensues.

make DNS tombstoning idempotent

---

weave

Fixes #2052.
The output from `curl` is placed in a temporary file, which is sent to stdout if the result is 2xx and stderr otherwise, except for 404 errors which are specifically handled in various places so `call_weave` swallows the "404 not found" message.
The "Call to weave failed." message is removed, in favour of whatever actual error came back from `curl`.  It may be that this makes some troubleshooting harder.
Also fixes an issue introduced by #1200 if the user has disabled IPAM with the (undocumented) `--ipalloc-range=""` whereby each fixed IP address specified would receive a "404" message, and this PR would otherwise have turned that into a failure of the entire command.

Report errors when weave script talks to weave component via http

---

test/120_discovery_3_test.sh
test/150_connect_forget_2_test.sh
test/320_claim_3_test_disabled.sh
test/370_persist_ipam_2_test.sh
test/config.sh

Also, stop weave in `end_suite` by using `weave stop` which does not remove the weave container (#1939).

Do not fail during teardown of test suites if $COVERAGE is not set

---

common/logging.go
router/network_router.go

Particularly to bring in https://github.com/weaveworks/mesh/pull/29
Note the test now has a `sleep 32` in it, to take us past a periodic gossip interval.  This is a bit nasty, arising from the fact that we don't immediately broadcast corrections to DNS gossip information received.
Fixes #2085

Update weaveworks/mesh to send gossip to restarted peer

---

nameserver/nameserver.go
test/215_stale_dns_3_test.sh

Further improvement to the issue raised at #2081 - don't wait for periodic gossip to get the data corrected on other peers.

Immediately broadcast DNS records that "re-assert a peer's authority"

---

ipam/allocator.go
ipam/allocator_test.go
ipam/paxos/paxos.go

Following #2070 we defer computing the quorum size until we need it.  This PR ensures that we do not have a bogus value of 1 lying around in the case where we never tried to compute a better value.
Also fix up `TestBootstrap()` which attempts to simulate and check the messages exchanged at startup.  This test is really operating at the wrong level.
Fixes #2139.

Don't try to form IPAM ring with a bogus quorum size

---

README.md
prog/weaver/http.go
prog/weaver/main.go
site/troubleshooting.md
test/700_status_and_report_test.sh
test/config.sh

The `AvailableVersion` field denotes the latest available version which is retrieved via go-checkpoint.
If checkpoint is disabled, the field will contain the `<checkpoint disabled>` value.
E.g.:
```bash
ubuntu@host:~$ weave status
Version: git-b7d49cdeb7db
AvailableVersion: 1.4.4
<..>
```
Fixes #2089

2089: Add info about new available versions to the `weave status` report

---

prog/weaver/http.go
site/ipam/troubleshooting-ipam.md

Be more general about what we're waiting for - non-observer peers in the network may be seeded and not using consensus.

Improve IPAM status wording

---

weave

...so that we can start multiple weaves on a machine w/o them sharing a single db container and tripping over each other as a result.
Unbreaks multiweave.
Fixes #2177

name db container after weave container

---

ipam/allocator_test.go

`GossipBroadcast` in the `TestRouter` only goes one hop. In `TestTransfer` the three peers are connected in a chain, and hence we need to take extra care to ensure propagation to all peers.
Fixes #2180.

fix simulation of periodic gossip in TestTransfer

---

router/network_router.go
test/370_persist_ipam_2_test.sh

Persistence of peer lists gives you a difference in behaviour compared with 1.4 that may lead to unexpected side-effects.  This PR disables the feature until we can think it through some more.

Disable persistence of peer lists

---

ipam/allocate.go
ipam/allocator.go
ipam/allocator_test.go
ipam/claim.go
ipam/http.go
test/370_persist_ipam_2_test.sh
weave

Fixes #2164 
Note the `owned` map changes type so breaks compatibility with earlier persistence files

Store 'checkAlive' flag in IPAM, so we don't delete non-container IDs

---

weave

Fixes #2197 
As discussed there, I don't think it really matters, but it's odd that we have one arg without equals and the others with.

Add equals sign to --dns arg, for consistency

---

ipam/allocator.go
prog/weaver/main.go

The function is registered within the mesh GC and it is responsible
for removing gone nicknames.
Fixes #2057

2057: Add allocator.PeerGone

---

bin/publish-site
site/troubleshooting.md

Fixes #2216.
Should be able to check at http://dev-weavewww.pantheon.io/documentation/net-2216-fix-link-troubleshooting/ once the CI build has completed.

Fix broken link

---

site/using-weave/finding-adding-hosts-dynamically.md
site/using-weave/service-management.md

- move "Managing Services in Weave Net" up so it comes after
"Integrating a Host Network with Weave Net", to which it is deeply
related
- move "Adding and Removing Hosts Dynamically" down so it is adjacent
to the other sections which talk about peer connectivity
@abuehrle

tweak 'Using Weave Net' section order

---

site/features.md
site/how-it-works/ip-addresses.md
site/using-weave/application-isolation.md
site/using-weave/configuring-weave.md
site/using-weave/host-network-integration.md
site/using-weave/manual-ip-address.md
site/using-weave/service-management.md

- strip "Weave" and "Weave Net"
- "Integrating a Host Network with Weave" -> "Integrating with the
Host Network"
- "Configuring Weave to Explicitly Use an IP Range" -> "Allocating IPs
in a Specific Range"
@abuehrle

Tweak titles under "Using Weave Net"

---

test/320_claim_3_test.sh

Coming back to #1482; the first commit here doesn't attempt to address the failures reported, but simply updates the test so it can be re-enabled to see if it's still occurring.
I have re-run the test several times on CircleCI and seen no failures. (Just like in #1268)

Update test 320 to cope with persistence

---

nameserver/dns.go
test/250_dns_negative_test.sh

Per RFC4074, return DNS no-error with empty answer if we have a matching name but the query is for a record type we don't support.  
Fixes #2244

Blank DNS response to AAAA queries where we have an A record

---

bin/publish-site

Release docs will now also be available with a stable 'latest' URL.

Upgrade to Wordepress 1.0.0

---

ipam/claim.go

This improves the error message from "address 10.32.0.1/12 is already owned by 10.32.0.1" to "address 10.32.0.1/12 already in use".  Also the code as it stands would not have removed the 'owned' entry if it was deleted from the plugin.
It does not address the basic point of #2194, which is that the situation does not deserve a diagnostic. When the re-launch does its "claim" operations, it passes in the container ID, which does not match up to the earlier allocation via the plugin.

Improve handling of `claim _`

---

Makefile

This means people who build on a Mac, using docker machine, don't have to type `make SUDO=` all the time.

Autodetect if we talk to docker via tcp in the Makefile

---

ipam/allocator.go
test/362_ipalloc_range_change.sh
test/380_ipam_seed_2_test.sh

Fixes #2209 and fixes #2246
Now, we don't use the persisted data if there is no name, if the name doesn't match, if there is no ring, or if the ring doesn't match.
Including new smoke-tests.

Better deleting of persisted IPAM data 

---

ipam/allocator.go
ipam/allocator_test.go

These cases were missed earlier.
Note this change also makes `AdminTakeoverRanges()` cause pending ops to be retried, which seems appropriate - e.g. we may have taken over a range which covers a pending claim.
Calling `ringUpdated()` instead of `AddRanges()` is less efficient, because we will compute what space has been added instead of using what we already know in `newRanges`, but this is ok as `rmpeer` should not be called rapidly.

Persist the IPAM ring on `weave reset` and `weave rmpeer`

---

ipam/allocator.go
ipam/allocator_test.go
ipam/claim.go
ipam/http.go
test/320_claim_3_test.sh

This PR aligns the behaviour of Claim with Allocate which blocks until the ring has been established.
Fixes #2232

make claim block if the IPAM ring is not established

---

ipam/allocator.go
weave

Since the implementation of `GossipBroadcast` requires a call back into the IPAM actor to encode the message, with the previous implementation it wouldn't actually get sent until after the sleep finishes.
Since we only use this function in one place, move the sleep out to the caller.

Move sleep on reset from IPAM Allocator to weave script

---

ipam/allocator.go
test/320_claim_3_test.sh

Fixes #2275
In the case that we do receive a ring very soon, the consequence of this change is that the requestor doesn't hear back so retries within 5 seconds.
I also moved the debug message so we still see it on requests that are ignored.

Ignore IPAM requests for space until we have a ring

---

test/320_claim_3_test.sh

UPDATED.
The problem was that the claim at https://github.com/weaveworks/weave/pull/2278/files#diff-1b73b6468431320099c9cbd2340c9a01L65 was sometimes failing because of `10.32.0.0/13` being assigned to `host2`. As a consequence, the assertion at https://github.com/weaveworks/weave/pull/2278/files#diff-1b73b6468431320099c9cbd2340c9a01L73 was failing.
The fix ensures that we always try to claim at `host1` for IP addr from the range assigned to the host. It's done by reusing the IP addr of `c4`.

Fix 320_claim_3_test.sh

---

ipam/allocator_test.go
ipam/space/space.go
ipam/space/space_test.go
net/address/address.go
net/address/address_test.go

If, say, we wanted to use the ranges for routing rules, having them aligned so you can describe each one with a single CIDR is useful.
Also fix up space tests to match.

Donate CIDR-aligned ranges instead of just slicing at the mid-point.

---

weave

Remove the Unix socket from the filesystem before doing volume operations, if the plugin is not running.
Fixes #2286
(Note the comparable problem for network operations is not helped by this measure.  I.e. if you:
````
$ weave launch
$ docker kill weaveplugin
$ weave reset
````
then `weave reset` will hang for a while trying to remove the `weave` network.)

Protect against Docker hanging trying to talk to a non-existent plugin

---

ipam/ring/entry.go
ipam/ring/ring.go
net/address/address.go

This change is backward compatible, because the underlying types of `address.Offset` (the previous type) and `address.Count` are the same and the Gob encoder does not require types to exactly correspond.
In addition to this PR, I'd suggest to rename `func (r *Ring) distance(start, end address.Address)`, because the existing function name implies the `address.Offset` return type.

Change the type of entry.Free to address.Count

---

proxy/proxy.go
weave

Fixes #2284; also ends up rather simpler.  Undoes much of #2264.
The change also removes two flags from the interface of `attach()`, at the cost of a duplicate `Inspect` in case of error.  I prefer it that way.

Move kill-on-failure responsibility to caller of weave script

---

.gitmodules
plugin/net/cni.go
test/830_cni_plugin_test.sh

To fix issues of packets disappearing when you re-use an IP address with a different MAC.
This brings the CNI plugin closer in behaviour to the weave script.

Send out arp update from CNI plugin

---

common/utils.go
net/arp.go
net/bridge.go
net/ethtool.go
net/netns.go
net/route.go
net/veth.go
plugin/net/cni.go
plugin/net/driver.go
prog/weaveutil/attach.go
prog/weaveutil/main.go
prog/weavewait/check_network_iface.go
prog/weavewait/check_network_iface_mcast.go
weave

Part of #1940 
Most of this is refactoring/enhancing the current plugin code to be closer to the script; see also #639 for `arping` and #1726 for `ethtool tx off`.
The plugin previously leaked a veth if something went wrong configuring it.
This PR does not mean the proxy can avoid shelling out when attaching a container.  Still to do: allocate IP addresses, rewrite hosts file, add to DNS.

Move container attachment from sh to Go

---

ipam/allocator.go
ipam/http.go
prog/weaver/main.go
test/500_weave_multi_cidr_test.sh

Be more consistent about this - check in the same way whether at startup or during allocation.
Note the error message used to talk about "allocation range" whether it was the range or the subnet we were checking, and now it says "subnet" in every case.
Fixes #2282

Check validity of IP subnets

---

proxy/proxy.go

Fixes #1988 per the last sentence in the description:
> I suppose the proxy could ignore all containers created with a network other than `default`, `bridge`, `none` or unset.
"unset" equates to `default`, as far as I can see.
Note this would be a breaking change for someone who is deliberately using the Weave proxy together with another plugin.  Those folks (if they exist) can `docker network connect foo`, I guess.
(note that `docker run --net a --net b ...` only connects to network `b`)

Proxy shouldn't weave-attach containers which are using a network plugin

---

prog/weaveutil/plugin_network.go
weave

Fixes #2320 
Example message:
````
$ weave stop-plugin
WARNING: the following containers are still attached to network "weave":
9e396c66e0d2 
Docker operations involving those containers may pause or fail
while Weave is not running
````

Augment warning on active plugin endpoints

---

site/installing-weave/systemd.md
site/operational-guide.md
site/operational-guide/autoscaling.md
site/operational-guide/concepts.md
site/operational-guide/interactive.md
site/operational-guide/tasks.md
site/operational-guide/uniform-dynamic-cluster.md
site/operational-guide/uniform-fixed-cluster.md

An operational guide that describes likely deployment scenarios and administrative tasks.
Fixes #726, fixes #1102

Operational guide

---

proxy/proxy.go

Check if socket is identical to weave socket after trimming prefix.

---

weave

Fixes #2326 
I did not put anything in about re-launching and re-resetting, because during `reset` we will have deleted the persistence data so re-resetting would require that we can connect to another peer who can supply us with our old IPAM ring and then do the reset.

Warn on 'weave reset' if DELETE fails

---

.gitmodules
api/ipam.go
ipam/allocator.go
ipam/http.go
ipam/http_test.go
ipam/ring/ring.go
ipam/ring/ring_test.go
ipam/tracker/awsvpc.go
ipam/tracker/awsvpc_test.go
ipam/tracker/tracker.go
net/address/address.go
net/address/address_test.go
net/veth.go
plugin/net/cni.go
plugin/net/driver.go
prog/weaver/main.go
prog/weaveutil/attach.go
router/awsvpc.go
router/bridge.go
weave

Please be aware that all the necessary enhancements are listed in https://github.com/weaveworks/weave/issues/2322.

Add AWSVPC

---

weave

Fixes #2318. 
~~Note that `weave run` with `--help` as part of the container command-line will produce odd results, because of #2351.~~ This no longer applies.

Print usage on --help argument to any command

---

ipam/allocator.go

In `Shutdown`, if no peer for transfer is found, we transfer them to `mesh.UnknownPeerName` to notify the ring update tracker.
Resolves an issue, when the stale entries are left in the AWS VPC route table after `weave reset` issued on the last peer.
Fixes https://github.com/weaveworks/weave/issues/2322#issuecomment-223910199

Transfer IPAM ranges to UnknownPeer if no peer is found during Shutdown

---

site/installing-weave.md

It got lost in d1e004d
This PR replaces #2336 which was against wrong branch.
Note it needed a sub-heading because I put it under the video (not wanting to move the video "below the fold")

Re-instate mention of checkpoint on install page

---

proxy/proxy.go

Alternatively, we could do the validation inside `proxy.weaveCIDRs`. But in this case, the method has to be changed to return a third parameter which would indicate whether CIDRs are valid and the returned value would be ignored in some cases to keep a container alive.
Fixes #2283

Validate CIDRs in proxy before attaching a container

---

site/weave-docker-api/using-proxy.md
site/weavedns/managing-domains-weavedns.md

Fix a couple of things I noticed in passing:
- implying that users should read and type in the enormous hex ID of a container
- telling users to look "above" when we're at the top of a file
ping @abuehrle for doc review.

Small doc fixes

---

Makefile
bin/release

Fixes #2189 
Note that the weavedb image will not be pushed by the CI build, to address the point at https://github.com/weaveworks/weave/issues/2189#issuecomment-215380936

Publish weavedb container from release script

---

common/utils.go
plugin/net/driver.go
plugin/net/watcher.go
prog/plugin/main.go
weave

Fixes #1726, the last remaining part.
Note that we are only reacting to container `start` events, so not doing the arp stuff when a user `docker network connect`s a container.  See #1914

Perform arp configuration for plugin-connected containers

---

weave

Fixes the fix in #2292.
Also extend to `weave reset`, in case the plugin was killed before it got a chance to remove its sockets.

Fix check before removing plugin sockets

---

proxy/proxy_intercept.go

As seen in wireshark, we are doing four sends for every entry in the http header, many of which contain just 2 bytes of data (and, if over TCP, 54 bytes of packet header).  This change uses the already-existing buffered writer to condense them all into one send.
I also condensed all the `if err != nil` lines into one.

Use buffered writer for http headers

---

common/docker/client.go
prog/weaver/checkpoint.go
prog/weaver/main.go
site/installing-weave.md

Fixes #2310 
I couldn't find any library anywhere that did the necessary kernel wrangling, until after I wrote my own, when I found https://github.com/docker/docker/blob/master/pkg/platform/.  I don't like the way they report errors unconditionally via `logrus` so didn't use it.
(No errors are documented for `uname(2)` except "bad pointer" which can't happen here)

Add kernel version, Docker version and awsvpc setting to checkpoint info

---

ipam/ring/ring.go
ipam/tracker/awsvpc.go
weave

In order to re-attach the router and make it work in awsvpc mode, the following has to be done:
* `expose_ip` on the router
* adjusting arp settings
* restoring host routes
To detect that we run in awsvpc mode, we inspect cmd parameters of the weave router instead of GET'ing /ipinfo/tracker. This is so, because the HTTP server started by the router might not be running at the time of restoration.
Fixes #2381

Fix re-attaching of weave router in awsvpc mode

---

test/090_docker_restart_policy_2_test.sh
weave

Fixes #2293.
I decided to error the entire `launch-plugin` operation if `weave` is not running; if I just errored on the network creation then there is no way to re-try that operation; next time round the code will see the plugin is running and return early.
Fundamentally, it doesn't seem to be very useful to run the plugin *and* output an error.

Check that weave router is running before launching plugin

---

common/utils.go
net/netns.go
net/veth.go
plugin/net/cni.go
prog/weaveutil/addrs.go
prog/weaveutil/main.go
proxy/proxy.go

This PR fixes the problem described in #2388. In addition, the PR optimizes the `GetBridgeNetDevs` and `containerAddrs` functions.
Keep in mind, that the fix is specific for this case, because we move all the code depending on a non-host netns to the bottom of `containerAddrs` instead of making `WithNetNS` safe.
To address the safety problem, I've filed https://github.com/weaveworks/weave/issues/2419 .
Fixes #2388.

Fix "weave ps"

---

weave

This was harmless, but annoying.
Discovered while investigating #2406.

remove duplication of `--no-dns`

---

site/using-weave.md

since people keep tripping over that.
Also
- add new error message spat out by recent dockers correct the socket
- URLs - they had fallen victim to a 'docker'->'Docker' replacement
- shorten the note on using the plugin

Make use of `sudo -s` more explicit

---

nameserver/dns.go
nameserver/dns_test.go
nameserver/status.go

With no logging of errors, it can be difficult to diagnose problems.

Log errors arising from reading resolv.conf

---

net/netns.go
prog/weaveutil/addrs.go

The #2418 has changed a behaviour of `weave ps` cmd when weave is not running: instead of outputting an empty line, the cmd returns `Link not found` error.
To fix that, we check (in an ugly way, because the netlink package does not export sentinel errors) whether the "weave" bridge can be found, as it has been done before through bunch of indirections.

Fix "weave ps" output when weave is not running

---

site/features.md
site/plugin.md
site/using-weave.md

since as of #2330 the proxy ignores containers started with specified user networks.
cc @abuehrle

remove dire warnings about 'eval' when using plugin

---

weave

Fixes #2464
The deprecation message remains, so anyone trying to use it before Docker is running should realise there is a better way.

Re-enable 'weave create-bridge' in fastdp mode.

---

Makefile

This flag was deprecated in Docker 1.10 and removed in Docker 1.12.

Remove -f flag from 'docker tag' commands

---

plugin/net/cni.go
site/cni-plugin.md
test/830_cni_plugin_test.sh

No need to call `weave expose` before use.  This simplifies set-up for Kubernetes, etc.
It only does if the config doesn't specify any routes or gateway, which may be too restrictive, but I guess we can wait for customer feedback.
CC @abuehrle for review of doc change

CNI plugin assigns an IP to the bridge by itself

---

weave

Fixes #2424 (in particular, https://github.com/weaveworks/weave/issues/2424#issuecomment-231032260)

Do not fail launching the proxy if unable to detect a running instance of docker daemon

---

site/operational-guide/concepts.md
weave

~~**NB**: Please review https://github.com/weaveworks/mesh/pull/51 first. After it has been reviewed and merged I will update the necessary submodule.~~ **DONE**.
This PR changes the way we generate the bridge MAC. Instead of relying on a single source, we concatenate multiple sources. In addition, we include the machine id, which is generated either by [systemd](https://www.freedesktop.org/software/systemd/man/machine-id.html) or [D-Bus](https://dbus.freedesktop.org/doc/dbus-uuidgen.1.html). The machine id is unique and should be stable across restarts unless a user regenerates it.
CC'ing @abuehrle as there are changes to the docs.
Fixes #2427 and probably #2451.

Detect and report peer name collisions

---

weave

This simplifies the code and makes `weave create-bridge` more useful
The key change is that the veths are now created before `weaver` is running instead of afterwards, but I can't see that this would be important.  This is already the case if you stop/start `weaver`.

Refactor: move bridge veth creation into 'init_bridge'

---

prog/weaveutil/plugin_network.go
weave

Fixes #2469.
New behaviour in Docker 1.12 means it disregards a plugin-supplied address pool that overlaps an existing route. When we pass in the subnet, Docker believes we really do want that address range and avoids the hang.

Pass in default subnet when creating 'weave' plugin network.

---

weave

Add a private flag for weave-kube to steer overlay traffic via the network policy engine chain.

Implement `--expect-npc` flag to `create-bridge`

---

common/process.go
prog/weaveutil/docker_tls_args.go
prog/weaveutil/main.go
prog/weaveutil/proc-addrs.go

Similar to weaveutil container-addrs, but for use in circumstances where we can't or don't want to talk to Docker.  E.g. weave-kube.

Add weaveutil process-addrs

---

prog/weaver/checkpoint.go

so that the code compiles regardless of the uts.Release array type, which varies across platforms.
Fixes #2506

inline (u)int8 array to string conversion

---

weave

Send blocked NEW connection attempts to NFLOG group 86 for accounting by the weave-npc process; required by weaveworks/weave-npc#7.

Log dropped policy controller traffic via NFLOG

---

site/weave-docker-api.md

On https://www.weave.works/docs/net/latest/weave-docker-api/
> Note that if a Docker container is started with the –net flag, then the Weave Docker API Proxy is automatically disabled and is not used to attach containers. See Integrating Docker via the Network Plugin.
has a dead link to https://www.weave.works/docs/net/latest/weave-docker-api/plugin.md
This PR fixes it.

Fixed broken link to plugin.md to weave-docker-api.md.

---

.gitignore
Makefile

Encode `$(DOCKERHUB_USER)` into the name of the generated Dockerfile so we only rebuild on change.

Improve Dockerfile template substitution

---

.gitignore
.gitmodules
Makefile
bin/release
docs/release-process.md
prog/kube-peers/main.go
prog/plugin/Dockerfile.template
prog/weave-kube/Dockerfile.template
prog/weave-kube/launch.sh
prog/weave-kube/weave-daemonset.yaml
prog/weaver/Dockerfile.template

This PR brings in code and artefacts from the https://github.com/weaveworks/weave-kube repo.
It also re-arranges the Docker image dependencies. Previously we had:
```
scratch <- weave
scratch <- alpine <- weaveexec <- plugin
```
Now we have:
```
scratch <- alpine <- weaveexec <- weave <- plugin <- weave-kube
```
This ensures that `weave-kube` has the `weaver` and `plugin` files it needs, while avoiding any double-copying of binaries.  It does mean that the `weave` container looks much bigger than before.
Note that `kube-peers` is kept as a separate executable rather than merging into `weaveutils`, since it would make the `weaveutils` binary 4x larger and hence (probably) slower to start up.

Merge weave-kube into the Weave Net repo

---

prog/weave-kube/launch.sh

We've got ability to run weave-kube as a static pod https://github.com/weaveworks/weave-kube/pull/36. But there is no posibility to run weave-npc as a static pod (static pod can't get secrets from service account).
And weave-kube doesn't work without weave-npc, because of default iptables rules for NPC.
```
-A FORWARD -o weave -j WEAVE-NPC
-A FORWARD -o weave -m state --state NEW -j NFLOG --nflog-group 86
-A FORWARD -o weave -j DROP
```

allow to not run NPC: do not create iptables rules for NPC

---

prog/weaver/metrics.go

To follow [the Prometheus naming conventions](https://prometheus.io/docs/practices/naming/): _"should have a suffix describing the unit, in plural form. Note that an accumulating count has total as a suffix, in addition to the unit if applicable"_

Rename weave_connection_termination_count metric

---

weave

So that an installation can use weave-npc, then do `weave reset`, then use Weave Net without npc.

Have 'weave reset' remove NPC rules

---

bin/circle-dependencies-post
test/gce.sh

This is a precursor to run Kubernetes smoke tests.
The current most up-to-date Docker version is 1.12.1 which [failed some Python tests](https://circleci.com/gh/weaveworks/weave/6920), so I went back to 1.11.3.  The previous version we were using, 1.10.3, is not shipped by Docker for Ubuntu 16.04, and the Ubuntu 1.10.3 [rejects our embedded Docker over the 'host' param](https://circleci.com/gh/weaveworks/weave/6924).
I took the opportunity to pre-load a few things into the image to shave off a few seconds from every test run.
`systemctl` waits for the Docker restart, so we don't need "a short delay".

Update CI VMs to Ubuntu 16.04 and Docker 1.11

---

Makefile
net/netns.go
prog/weave-kube/Dockerfile.template
prog/weave-kube/launch.sh
prog/weaveutil/cni.go
prog/weaveutil/main.go
weave

By the cunning tactic of embedding the CNI plugin inside `weaveutil`
Note I force all uses of `WithNetNS` in `weaveutil` to exec the current program (as defined by `/proc/self/exe`); this seemed better than having it sometimes exec `weaveutil` and sometimes self.
Fixes #2587

Fix CNI plugin calling weaveutil

---

prog/weave-kube/launch.sh

Fixes #2586
Manual tests:
1. Fresh installation:
```
$ rm -fr foo
$ ./test.sh 
$ ls -al foo/
total 12172
drwxrwxr-x 2 vagrant vagrant     4096 Nov  3 13:36 .
drwxrwxrwt 9 root    root        4096 Nov  3 13:36 ..
lrwxrwxrwx 1 vagrant vagrant       29 Nov  3 13:36 weave-ipam -> weave-plugin-git-bb639dbf322b
lrwxrwxrwx 1 vagrant vagrant       29 Nov  3 13:36 weave-net -> weave-plugin-git-bb639dbf322b
-rwxr-xr-x 1 vagrant vagrant 12454168 Nov  3 13:36 weave-plugin-git-bb639dbf322b
```
2. Idempotency of duplicate installation:
```
$ rm -fr foo
$ ./test.sh 
$ ./test.sh 
$ ls -al foo
total 12172
drwxrwxr-x 2 vagrant vagrant     4096 Nov  3 13:37 .
drwxrwxrwt 9 root    root        4096 Nov  3 13:37 ..
lrwxrwxrwx 1 vagrant vagrant       29 Nov  3 13:37 weave-ipam -> weave-plugin-git-bb639dbf322b …
```

Add support for atomic and versioned upgrades of CNI plugin.

---

prog/weave-kube/launch.sh
test/840_weave_kube_3_test.sh
test/gce.sh

This builds on #2551 and #2563, builds another new image with Kubernetes packages pre-loaded and adds one smoke-test script to try it out.
Currently the only thing the test does is checks to see whether 3 peers form 6 established connections.
If something should go wrong mid-test it will likely cause havoc during the rest of the run, because kubelet will be restarting things.  I considered adding the kubeadm tear-down steps (which are here in `840_weave_kube_3_test.sh`) to `config.sh` but it seemed overkill.

weave-kube smoke test

---

prog/weaver/checkpoint.go
prog/weaver/http.go
test/700_status_and_report_test.sh

`weave status` now prints:
```
failed to check latest version - see logs
```
when the checkpoint API is not available.
Periodicity of the checks is left unchanged.
Smoke tests based on `iptables` rules added to reproduce the failure.
Fixes #2537.

Improve 'status' to handle cases when the checkpoint API is not available

---

net/veth.go
plugin/net/cni.go
prog/weave-kube/launch.sh
prog/weaveutil/expose.go
prog/weaveutil/main.go
test/840_weave_kube_3_test.sh
weave

Remove 'weave expose' race in CNI plugin

---

test/700_status_and_report_test.sh

Unfortunately our assumption regarding `checkpoint-api.weave.works` having a stable IP address proved to be wrong, and we were seeing occasional failures where the iptables rule blocked a different IP than the one being used by the router. Instead, override the `/etc/hosts` used by the router to resolve checkpoint-api to return an unresponsive IP in the loopback subnet.

Replace iptables block with resolver override

---

weave

The previous regex matched a blank `--ipalloc-range` together with the following parameter, which defeated the whole point of the check.
I contemplated using `CIDR_REGEXP` but we explicitly are not trying to check the value, just trying to spot if it was in the args.
Fixes #2567

Better value for --ipalloc-range in attach-router

---

Makefile
build/Dockerfile
ipam/ring/ring_test.go
npc/namespace.go
prog/weaver/metrics.go
proxy/malformed_host_override.go
proxy/proxy.go

Build container FROM golang:1.7.3

---

npc/namespace.go

This is an improvement on the behaviour reported at #2632 - a complete fix will need to cover the case where the observed lifetimes of two pods overlap.
I am relying on the pod phases being as documented at http://kubernetes.io/docs/user-guide/pod-states/
Empirically this fixes the problem that any 'completed' or 'failed' pods can remain showing their old IP address, that is re-used by a later pod invocation.

Make NPC only look at IP addresses on running pods

---

ipam/allocator.go
test/830_cni_plugin_test.sh

The CNI spec doesn't say we can release the address at this time, so best not to.
Currently the Weave Net plugin will error if you call DEL after the container has died, so  this change means the address will leak, but this will probably be amended in the CNI spec and libraries - see https://github.com/containernetworking/cni/issues/309
Note this change is based on the observation that `api.AllocateIP` doesn't set `check-alive` so `IsContainer` gets set to `false`.

Don't release CNI-allocated IP address when container dies

---

prog/plugin/main.go
prog/weave-kube/launch.sh
prog/weave-npc/main.go
prog/weaveproxy/main.go
prog/weaver/main.go
site/troubleshooting.md
weave

The version string can be anything, including the default `"(unreleased version)"`, so must be quoted when used in a shell command-line.
Also we must supply extra args when the program is compiled with code-coverage.

Fix weave-kube launch.sh version usage

---

npc/metrics/metrics.go
site/kube-addon.md

Same as #2566 but without the bit.ly short URL, i.e.: 
- Added documentation to explain Weave's behaviour when used together with Kubernetes and Weave NPC, and to explain what a "Connection dropped by Weave NPC" message means.
- Improved the log message to be slightly more descriptive, and help users diagnose their setup.
Fixes #2546.

Clarified and documented Weave NPC packet drops (w/o short URL).

---

prog/weave-kube/launch.sh

Fixes #2669 
Doubtless this will be followed up by someone who specifically needs it to overlap and needs a new lever to disable this check.

Check whether Weave's IP range overlaps something on the host already

---

weave

Otherwise it is left in a half-created state and the user has to run `weave reset` to continue.
This is particularly important when using weave-kube, where most users don't have the `weave` script available.

Remove weave bridge if something goes wrong when creating it

---

prog/weave-kube/launch.sh
test/830_cni_plugin_test.sh
weave

Fixes #2594 
Points to note:
* The symlinks in `/opt/cni/bin` are now relative to that directory (i.e. to `weave-plugin-1.9.0`), not absolute.
* Test 830 has to run the plugin under sudo now.
* As before, `weave` only installs the CNI plugin if the directories `/opt/cni/bin` and `/etc/cni/net.d` exist, whereas `launch.sh` creates the directories it needs.
* The plugin location is overridable via `$WEAVE_CNI_PLUGIN_DIR`

Unify weave and launch.sh CNI setup

---

prog/weave-kube/launch.sh
site/kube-addon.md

Fixes #2673.
Previous change in a07e3301b1a8 meant that if there are no pods on this node then the 'expose' never gets run.
Also I documented the use of `WEAVE_EXPOSE_IP`, from https://github.com/weaveworks/weave-kube/pull/36

Re-add expose to ensure it gets run on all nodes

---

prog/weaver/http.go
router/awsvpc.go
router/fastdp.go
router/overlay_switch.go
router/sleeve.go
site/troubleshooting.md
test/700_status_and_report_2_test.sh

Fixes #2389 
I carry the data through Mesh in a map to make it generic; AWSVPC declines to supply it in this implementation.
Sample output:
````
$ weave status connections
<- 192.168.48.1:59366    established sleeve 6a:41:53:e1:d7:29(vagrant-ubuntu-wily-64) mtu=1438
<- 192.168.48.11:42128   established fastdp 5e:7e:09:ac:95:94(host1) mtu=1410
$ weave report
...
"Connections": [
{
"Address": "192.168.48.1:59366",
"Outbound": false,
"State": "established",
"Info": "sleeve 6a:41:53:e1:d7:29(vagrant-ubuntu-wily-64)",
"Data": {
"mtu": 1438
}
},
{
"Address": "192.168.48.11:42128",
"Outbound": false,
"State": "established",
"Info": "fastdp 5e:7e:09:ac:95:94(host1)",
"Data": {
"mtu": 1410
}
}
],
...
````

Add MTU to connection status

---

prog/weave-kube/launch.sh
prog/weaver/main.go

Fixes #2480
Cleans up `launch.sh` slightly, but not as much as when originally filed as weave-npc needs the bridge to be set up explicitly now.

Take peerName from weave bridge if not specified

---

common/odp/odp.go

If the datapath exists when creating it, `dpif.CreateDatapath` will return an empty handle which access causes the segfault.
Fixes segfault in #2638

Do not segfault if the datapath exists

---

prog/weave-npc/Dockerfile
prog/weavedb/Dockerfile
prog/weaveexec/Dockerfile
prog/weaver/Dockerfile.template

Fixes https://github.com/weaveworks/weave/issues/2705
This is more of a test PR for me to see if everything works as it should.
I've now used the lucas@weave.works address.
cc @bboreham

Remove the deprecated MAINTAINER field in Dockerfiles for "LABEL maintainer" instead

---

prog/weave-kube/launch.sh
prog/weave-kube/weave-daemonset.yaml

So we don't accidentally read or write the hosts's `/etc`.
Also move the other volumes under `/host` to be more consistent with what the weave script expects.

Mount /etc under a different path for weave-kube

---

test/150_connect_forget_2_test.sh

Fixes flaky test runs like the below:
```
>>> Running /root/src/github.com/weaveworks/weave/test/150_connect_forget_2_test.sh on [138.68.153.213 138.68.149.186]
>>> Test /root/src/github.com/weaveworks/weave/test/150_connect_forget_2_test.sh finished after 12.4 secs with error: exit status 1
test #5 "direct_peers 138.68.149.186 | sort" failed:
expected "138.68.153.213\n138.68.149.186"
got "138.68.149.186\n138.68.153.213"
```
Test:
```
#!/bin/bash
assert_peers() {
printf "$(echo "$1" | sort)"
}
fix() {
printf "$(echo -e "$1" | sort)"
}
echo "Current state (broken):"
assert_peers "138.68.153.213\n138.68.149.186"
echo
assert_peers "138.68.149.186\n138.68.153.213"
echo
echo "Target state (fixed):"
fix "138.68.153.213\n138.68.149.186"
echo
fix "138.68.149.186\n138.68.153.213"
echo
```
Output: …

Fix ordering bug in test #150.

---

test/601_proxy_docker_py_test.sh
test/602_proxy_docker_py_test.sh
test/603_proxy_docker_py_test.sh
test/604_proxy_docker_py_test.sh
test/670_proxy_tls_test.sh
test/840_weave_kube_3_test.sh
test/run_all.sh
test/setup.sh

Currently, depending on your current directory, `make`, tests, etc. may or may not run smoothly.
This is a pre-change refactoring for the #2647 work.

Finding and running tests no longer depends on current directory.

---

test/175_target_peer_persistence_3_test.sh

If the machine coordinating the test runs does not have `jq`, then test #175 fails with:
```
test #1 "weave_on test-0.lon1.weave-net report | jq -r '.Router.Targets[] | tostring' | sort" failed:
expected "test-1.lon1.weave-net
test-2.lon1.weave-net"
got nothing
```
This change completely removes the dependency on `jq` to make the test more robust and avoid potential confusion.

Removed dependency on jq in test #175.

---

test/setup.sh

Time spent running the setup steps becomes a blocker when trying to ramp up the number of test servers, given we are currently mainly blocking on I/O -- i.e. many files are uploaded/downloaded, which could easily be done faster.
This is a pre-change refactoring for the #2647 and #2648 work.

Parallelise setup.sh's individual tasks.

---

bin/circle-test-smoke
test/sanity_check.sh

Time spent running the sanity checks becomes a blocker when trying to ramp up the number of test servers, given ping check is `O(n^2)` and docker check is `O(n)`. This change makes it closer to "perceived" `O(1)`.
This is a pre-change refactoring for the #2647 and #2648 work.

Parallelise sanity checks in order to speed them up.

---

prog/weave-kube/launch.sh

So we only have one process running inside the container after all set-up is finished
Fixes #2684

Exec weaver from weave-kube launch rather than running in background

---

npc/ulogd/ulogd.go

Under certain circumstances (such as containerd-shim being killed) the main weave-npc process can be terminated without ulogd receiving any signals; consequently set PDEATHSIG so that ulogd is killed by the kernel.
Fixes #2653.

SIGKILL ulogd on weave-npc exit

---

weave

Fixes weaveworks/weave#2733 partially, where <host>/etc/resolv.conf is not a
symlink

Add partial support for non-FHS host systems

---

net/uuid.go

Fix a bug in #2711 
The symptom, on Scaleway, is:
```+ weaveutil unique-id /host//weave /host
All system IDs are blank
```

Don't fail if only half the system IDs are blank

---

.lintignore
Makefile
bin/circle-test-unit

Lint-ing all of Weave Net is currently not desirable because: 
* it would create conflicts on many branches,
* it would pollute the git history, 
* etc. 
and because `lint` currently lints all files except `./vendor`, this breaks Weave Net's build.
As a result, Weave Net is not using the latest commit in `build-tools`'s `master` branch, which is also source of problems:
* it limits standardisation of projects across Weaveworks, 
* it limits the ability to use the latest features of `build-tools`, 
* it complexifies merging changes in `build-tools` (e.g. #53 and weaveworks/weave#2694 for weaveworks/weave#2647), 
* etc.
This change:
* brings Weave Net to the latest version of `build-tools` (which now supports `.lintignore` files),
* adds such a `.lintignore` file to skip all bash scripts …

Upgrade Weave Net to latest version of build-tools, skipping bash scripts when lint-ing.

---

Makefile

Make manifest-tool using weave build container, and remove whitespace in blank lines and comment lines.
The latter principally because emacs complains about it, but also to remove the overhead of firing up a shell process to ignore a comment in a recipe.

Makefile cleanup after multiarch merge

---

Makefile

Alpine 3.5 doesn't provide PCAP plugin with ulogd, so until we investigate the problem upstream, we need to pin to 3.4 version.
Fixes #2732

Pin alpine container version

---

prog/weave-npc/main.go
site/kube-addon.md

Simple kludge for #2689 
I have made some steps towards a fuller solution in branch issues/2689-npc-mcast, but I realised it needs quite a bit more work - it should tie in with the way `net/veth.go` adds per-subnet multicast rules.

Add rule to allow multicast at top level

---

circle.yml

Instead of hardcoding this in the code, this should be passed by CircleCI from: 
```
Settings 
> weaveworks 
> weave 
> Environment Variables.
```

Remove hard-coded NUM_HOSTS env. var.

---

ipam/allocate.go
ipam/allocator.go
ipam/allocator_test.go
ipam/claim.go
ipam/testutils_test.go
prog/weave-kube/launch.sh
prog/weaver/main.go
prog/weaver/reclaim.go
test/320_claim_3_test.sh
weave

Fixes #2784 
`reclaim.go` is a re-implementation of the `launch.sh` code to claim addresses in Go.
We already had a `pendingClaims` list in IPAM, so we simply pre-populate this with entries for each existing address.  The claims will be processed as soon as the ring is known.
As it stands, this code is only good enough for `weave-kube`, not for `weave launch`
The code to find existing IPs works through the process table, and thus we do not have the Docker container ID.  To resolve that I propose to add another loop to go through Docker container IDs if we have a Docker API connection.

Claim existing IP addresses at startup with no race condition

---

build/Dockerfile
build/build.sh

Previous attempt to chown the dir inside `build.sh` resulted in a significant increase in a build time, and `build.sh` is exec'd once per every build.
Fix #2761

Make /usr/local/go writable to anyone

---

npc/ipset/ipset.go

To avoid crashing on error from `ipset` when we receive an Add before a Delete; fixes #2792 
Note that a real, long-lasting, IP duplication is a real problem, and this change makes it much less likely that we would spot that.

Reference-count ipset entries

---

prog/weave-kube/launch.sh

Once the number of cluster nodes is more than 30, then i need to build a new image. So, i think we should add an environment var for running weave container in a large cluster.

Add CONN_LIMIT environment var for running container

---

site/faq.md

Fixes #2223 
Also moved the FAQ back to the bottom of the menu - it's supposed to be easy to find.

Add anchors to faq questions

---

prog/weaver/metrics.go
site/metrics.md

We were bitten by #2797 yesterday (All of our nodes stopped working, because all of the address space was consumed by nodes we'd deleted)
When trying to figure out how to monitor for this situation, none of the existing metrics seemed suitable.
We plan to put alerting on `weave_ipam_pending_claims >0 for >5 minutes`, or something similar

Add prometheus metrics for pending Allocates and Claims

---

docs/weavenpc-design.md
prog/weave-kube/launch.sh
prog/weave-kube/weave-daemonset.yaml

Fixes #2726 
At least when `weave-npc` is executed via the `weave-kube` daemonset.  It would be nicer to separate those two concerns, but we already need to know that `weave-npc` is in use when creating the bridge.

Ensure we have the right modules loaded for weave-npc

---

prog/weave-kube/launch.sh
prog/weaveexec/Dockerfile.template

`weave-kube` is run in `alpine` image which uses busybox. `modprobe` of busybox will return the `"module not found"` error, if a module is built-in, which is an opposite behavior to `modprobe` distributed in mainstream distros (e.g. Ubuntu).
https://bugs.busybox.net/show_bug.cgi?id=5270
Fix #2820

Ignore modprobe errors in weave-kube/launch.sh

---

build/Dockerfile

It doesn't really matter if this makes it into master, but it can help improve the contributor experience in some organisations. - so feel free to close it if you're not interested :)
(Our corporate firewall doesn't allow the hkp port out, but does allow 80, so this change lets me run the weave build)

Use a keyserver port that's better for firewalls

---

router/fastdp.go

It is possible to receive `FastDatapathCryptoInitSARemote` control plane message before `Confirm`ing a connection. In such case, the handler for `FastDatapathCryptoInitSARemote` tries to reset `heartbeatTimer` which is nil, thus it makes `weaver` to crash. The timer is initialized in `Confirm`. 
The fix is to skip the reset for such situations, as the timer will be reset in `Confirm` (both handling `<..>InitSARemote` and `Confirm` are mutually exclusive).
Fix #2824

Do not reset fastdp heartbeat timer for non-confirmed connections

---

site/using-weave/security-untrusted-networks.md

doc: Remove invalid statement about missing encryption in fastdp

---

.gitmodules
Makefile
plugin/ipam/cni.go
plugin/net/cni.go
prog/weaveutil/cni.go
test/830_cni_plugin_test.sh

Prompted by the impending release of Kubernetes 1.6, which seems to rely on the behaviour that a blank netns is allowed on DEL.
Lots of lines changed, because the CNI return format changed.  The library should take care of returning backwards-compatible results to older runtimes.

Upgrade cni library to version 0.5.0

---

test/config.sh

Following #2836 / #2845, it appeared some other tests in our suite generated `defunct` processes.
In order to automatically flag such tests, it was decided we could include a similar check as in test 840 as a post condition of all tests.
Full discussion: https://weaveworks.slack.com/archives/C0DNGPKLY/p1489593552762037
1. Added `assert_common_postconditions` to `config.sh` with a check for `defunct` processes.
2. Added instructions to run `assert_common_postconditions` for all hosts as part of `end_suite`.

Assert no defunct process is generated as a postcondition of all tests.

---

README.md

The Slack Status badge doesn't work, at least for
non-signed-in users.  This gives a bad impression
as to the quality of the project.
Here's what it looks like for me, for example:

README: Drop Slack Status badge

---

ipam/allocator.go
ipam/allocator_test.go
ipam/space/space_test.go
prog/plugin/main.go
prog/weaveutil/docker_tls_args.go
prog/weaveutil/unique_id.go
router/sleeve.go

This covers most of #2843, with the exception of the obsolete http client used in the Docker proxy.
I sense that is either done that way on purpose or needs extra thought to update.

Fix various small issues revealed by staticcheck

---

ipam/http.go

Scope needs to know the IP addresses of containers.

Add GET /ip handler to return all IPAM mappings.

---

site/cni-plugin.md
site/features.md
site/how-it-works/encryption-implementation.md
site/how-it-works/network-topology.md
site/installing-weave.md
site/introducing-weave.md
site/ipam.md
site/ipam/stop-remove-peers-ipam.md
site/kube-addon.md
site/operational-guide/concepts.md
site/operational-guide/tasks.md
site/plugin.md
site/using-weave.md
site/using-weave/awsvpc.md
site/using-weave/dynamically-attach-containers.md
site/using-weave/fastdp.md
site/using-weave/finding-adding-hosts-dynamically.md
site/using-weave/host-network-integration.md
site/using-weave/multi-cloud-multi-hop.md
site/using-weave/service-management.md
site/weave-docker-api.md
site/weave-docker-api/ipam-proxy.md
site/weave-docker-api/using-proxy.md
site/weavedns/how-works-weavedns.md

Jekyll doesn't tolerate this, and it's generally considered a cleaner
style, we've had a bit of mixed style and this makes it consistent.

Consisten spacing in Markdown headings

---

prog/weaveutil/addrs.go
weave

This makes `weave ps` slightly cheaper, and will help Weave Scope to stop embedding the docker binary.

Fetch list of container IDs inside weaveutil

---

prog/weaveutil/addrs.go

`weaveutil/addrs.go#containerAddrs` previously was using `docker.ListContainersOptions{All: true}`, which is the equivalent of `docker ps -a`, and is not what we want here.
See also: https://weaveworks.slack.com/archives/C0DNGPKLY/p1492080958623977 and following discussion.

Only list active containers in weaveutil/addrs.go#containerAddrs

---

weave

Print helpful message; also stop and reset old weaveplugin container in case user has upgraded from <v2.0 and left it running.
per https://github.com/weaveworks/weave/pull/2727/files#r109466258, https://github.com/weaveworks/weave/pull/2727/files#r109468485 and https://github.com/weaveworks/weave/pull/2727/files#r109468670

More help for upgraders who use plugin commands

---

weave

Since we are making breaking changes in 2.0, it seems a good opportunity to clean out some old code.
I left in `--init-peer-count` since it's not as old as the others.

Remove deprecation warnings for things removed a long time ago

---

Makefile

The presence of the (old, v1.10) `docker` binary triggered a vulnerability check, because of something it embeds.  And these things are unnecessary bulk anyway, so get rid of them.

Remove some things we don't want in the v2 plugin image

---

weave

The `launch-dns` and `stop-dns` commands have been deprecated ~2 years ago.
Given we are planning a 2.0 release for Weave Net, now is a good time to fully remove these.
1. Removed `launch-dns` command.
2. Removed `stop-dns` command.
N.B.: I couldn't find any mention of these commands in `docs` and `site` by `grep -R`-ing these, so that should be it.

Remove deprecation warnings for `launch-dns` and `stop-dns` commands

---

prog/weaver/main.go
router/fastdp.go
router/injector_consumer.go
router/network_router.go
router/network_router_status.go
router/pcap.go

Since what it does it injects and consumes packets, and something else entirely does bridging.
The name seems to come from https://github.com/weaveworks/weave/pull/991#issuecomment-120427085; previously it was `IntraHost`.  But that wasn't right either, for what it does.

Rename router.Bridge to router.InjectorConsumer

---

weave

This logic was added for backward compatibility and to warn users about changes made ~2 years ago.
Given we are planning a 2.0 release for Weave Net, such logic is now irrelevant and can be removed.
Removed obsolete validation, parameters shifting and warning.

Remove obsolete validation and warning

---

build/Dockerfile
test/run-integration-tests.sh

In order to benefit from latest release's changes, e.g. `time.Until`, which is required for #2907.
See also: 
- `vendor/github.com/weaveworks/mesh/token_bucket.go:33: undefined: time.Until` in [Circle](https://circleci.com/gh/weaveworks/weave/8683)
- https://golang.org/doc/go1.8
Depends on: weaveworks/build-tools/pull/91

Upgrade Go version to 1.8.1.

---

prog/kube-peers/main.go

Why:
* In some environments Nodes have an ExternalIP but no InternalIP
This change addresses the need by:
* Falling back to ExternalIP addresses if there isn't an InternalIP for a node

fix(kube-peers): Add support for ExternalIP addresses

---

prog/kube-peers/main.go

Filter out IPv6 addresses from kube-peers

---

common/docker/client.go
plugin/plugin.go
prog/weaver/main.go
prog/weaveutil/main.go
prog/weaveutil/plugin_network.go
weave

In the process, use the default subnet instead of the whole IP allocation range.
Fixes #2919

Move plugin network creation from shell script to Go

---

prog/weaver/checkpoint.go
prog/weaver/main.go
router/network_router.go

Fixes #2771 
Requires https://github.com/weaveworks/go-checkpoint/pull/16 and https://github.com/weaveworks/mesh/pull/75
I took out the previous "network" flag which was awsvpc-specific.

Add checkpoint flag per connection type

---

weave

Check not only for plugin-v2 but also for plugin-v1, as both create the same plugin sockets (`weave.sock` and `weavemesh.sock`).
Should fix flakiness in 80* smoke tests.

Fix protect_against_docker_hang

---

plugin/net/cni.go

- Ignore errors when deleting a container's interface. Fixes #2921.
- Comply to CNI 0.5 spec by always returning `nil` on CNI `DEL`. Improvement.

Ignore errors on network interface delete during CNI Delete

---

prog/weave-kube/launch.sh

If this function dies in the middle, the leftover weave-kube-test set
causes this function and weave-npc to break. In particular
this means we can never restart weave with the launch script.
Here we clean up in advance, in case there's leftovers from a previous run
Fixes #2934

Clean up xt_set_exists components in advance

---

plugin/net/driver.go
plugin/plugin.go
prog/net-plugin/config.json
prog/net-plugin/launch.sh
prog/weaver/main.go
prog/weaveutil/main.go
prog/weaveutil/swarm.go

Current limitations:
* No `configure-arp`.
* Multicast can be enabled only for all networks (via `docker plugin set weaveworks/net-plugin WEAVE_MULTICAST=1` on each host).
Partly fixes #2906

Work around missing docker.sock in plugin-v2

---

build/Dockerfile

Golang containers seem to built on debian jessie, not ubuntu.

Fix build libssl issue: Use cross-compilers from debian rather than ubuntu

---

prog/weaveproxy/main.go

This warning was added in #1812 following the merge of DNS in the router ~1.5 year ago.
Given we are planning a 2.0 release for Weave Net, such a warning is now irrelevant and can be removed.
Remove deprecated flag `--with-dns` and related warning.

Remove deprecated flag --with-dns.

---

api/weaveapi.go
common/wait.go
plugin/plugin.go
prog/weaver/http.go
prog/weaver/main.go
prog/weaver/metrics.go
proxy/proxy.go

Various parts of the system initialize asynchronously at startup.
Callers should not attempt operations until all parts are ready; the `weave` script already delays until `curl /status` returns 200, but this could happen too early.
So, we introduce a `ready` function to be called by each sub-part: plugin, proxy, expose; this function comes from a wrapped `WaitGroup`.
We don't actually wait on the `WaitGroup`; that could perhaps be simplified, but I thought it was a good idea to follow the pattern.

Wait until ready; make test 810 more reliable 

---

prog/weaveutil/plugin_network.go
weave

Make plugin-v2 detection to work when plugin-v2 name includes a registry name (e.g. "store/weaveworks/net-plugin").

Better plugin-v2 detection

---

api/ipam.go
plugin/ipam/cni.go
plugin/ipam/driver.go
prog/weaver/main.go
prog/weaveutil/attach.go
prog/weaveutil/main.go
proxy/common.go
proxy/hosts.go
proxy/proxy.go
weave

Rather than calling out to the shell script.
This is the last part to fix #1940

Attach containers from Proxy using Go code

---

test/run-integration-tests.sh

This fixes new error raised by latest version of shfmt, leading to build failures.

Fix shfmt lint error by escaping $ in sed expression

---

prog/weaver/main.go
proxy/proxy.go
weave

This is a hold-over from the multi-container implementation, so we can slim things down a bit by removing it.
Although #2036 recommends going in the opposite direction :thinking:

Remove proxy status.sock

---

npc/shortname.go

Why:
* xml output of ipset is invalid because ipset itself doesn't appear to
escape invalid chars
* fixes #2958

fix(npc): create ipsets with only valid xml characters

---

plugin/plugin.go
plugin/status.go
prog/weaver/http.go
prog/weaver/main.go
proxy/status.go
weave

Fixes #2956 
Fixes #2709
1. `weave status` now does plugin-v1 and plugin-v2 in Go code.
2. all other uses of `is_plugin_vX_enabled`collapse to "is weaver running?"
2a. in `stop` before calling `remove-plugin-network`, if plugin was disabled then `RemoveNetwork` will return `NoSuchNetwork`
2b. in `protect_against_docker_hang` if weaver is not running it's ok to remove the plugin sockets.
2c. in `launch` we now error if weaver is already running for any reason

Simplify checks for plugin running

---

Makefile

The #2954 PR has changed the base image of `weaveworks/weave` which no longer includes sigproxy and docker client.

Do not remove sigproxy and docker from net-plugin build image

---

net/bridge.go

Fixes #2975.
We don't get a very useful error object back from go-iptables and I didn't feel like parsing the message, so just ignore all errors.
It would be racy to try to check if WEAVE-NPC existed before calling NewChain.

Don't clear WEAVE-NPC chain in weaver

---

Makefile
test/101_cross_hosts_2_test.sh
test/840_weave_kube_3_test.sh
test/config.sh
test/images/network-tester/Dockerfile
test/images/network-tester/webserver.go

This is intended to grow into a test we can use to get confidence the network works under various stress situations. `ping` is not good because it can be answered by a netdev we didn't expect.
The network-tester container was originally from Kubernetes, but modified a bit here.  It obtains a list of peer containers (currently via command-line args or via dns) and then attempts to contact all of them.
We use the new network-tester to upgrade the Kubernetes smoke-test; previously it only tested whether containers would run at all on the network and now it tests whether they can talk to each other.

Add a network test that isn't ping

---

net/bridge.go
npc/constants.go
npc/controller.go
npc/ipset/ipset.go
npc/namespace.go
npc/selector.go
prog/weave-npc/main.go
test/840_weave_kube_3_test.sh

This branch is based off the branch for #2978, because I need the rule to contact kube-dns.
Only the last four commits are relevant to this PR.
This PR does two things: it fixes #2622 by only adding IP addresses from pods on the current node; and it then corrects a bug exposed by that change: weave-npc used to filter on the destination address at both ends of a connection.
I suspect this is the cause of #2973.
To address that, I create a new IPset which has all local pod addresses, and if a new connection comes from a local pod but does not target a local pod we let it through.  In this way all the real filtering is done at the destination end of the connection.

weave-npc to check local addresses only

---

net/bridge.go
test/840_weave_kube_3_test.sh

Correct a change in behaviour when the iptables rules set-up was moved from shell-script to Go code in https://github.com/weaveworks/weave/pull/1958/commits/dd232775e68a18122560af20637d96626e991d94 - the "Forward from weave to the rest of the world" rule was moved inside the `if config.ExpectNPC`.
This had the effect that, when NPC was in effect, nothing could leave the weave bridge, even to contact the Kubernetes DNS server.

Allow outward traffic when NPC is on

---

build/Dockerfile

Before this change, `go get`-ting` would pick the latest version of `shfmt` which keeps changing, hence frequently breaking our builds.
After this change, we download the `shfmt` binary from its GitHub releases page which is fast and locks the version we use. Note that `RUN` does not like herestrings, hence `echo "..." | sha256sum -c` for checksum.
Alternatives considered:
- `go get gopkg.in/mvdan/sh.v1/cmd/shfmt` -- but `gopkg.in` currently doesn't behave well for this tool
- `go build` from a `git` tag -- but this is much more involved.

Use shfmt v1.3.0 instead of latest from master

---

prog/weave-kube/launch.sh
prog/weave-kube/weave-daemonset-k8s-1.6.yaml
prog/weave-kube/weave-daemonset.yaml
weave

`emptyDir` has the same lifetime as the pod, whereas we want our persistence to extend past that, e.g. when Weave Net is upgraded.
We assume that `/var/lib` is writable.
Fixes #2610

Change weavedb from an emptyDir to a hostPath volume

---

site/installing-weave.md

As discussed [on Slack](https://weaveworks.slack.com/archives/C0CGANX6W/p1495451119984880) this URL should be updated.
cc: @lukemarsden, @abuehrle, @soschwei

Fix broken link to ECS guide

---

prog/weave-kube/weave-daemonset-k8s-1.6.yaml
prog/weave-kube/weave-daemonset.yaml
site/kube-addon.md
test/840_weave_kube_3_test.sh

The current Kubernetes YAML for `weave-kube`
1. is static, which forces people to manually edit the file in order to customise it, to add environment variables, etc. and
2. exists in two versions, one for Kubernetes `v1.5`, and one for `v1.6` and above, which forces users to make choices about how they install `weave-kube`, hence increasing mental burden.
The latest version of the Launch Generator supports, among others: 
- passing additional options, arguments, and environment variables (weaveworks/launch-generator#66), which addresses 1. above;
- passing the output of `kubectl version` to automatically extract Kubernetes' "server version" and return appropriate YAML configuration (weaveworks/launch-generator#79) without having users to care about it, which addresses 2. above.
1. Update …

Update weave-kube docs and YAML files to leverage Launch Generator

---

prog/weaver/main.go
weave

And, since this was the last deprecated option, remove all code to generate deprecation warnings in the weave script.
This incidentally fixes a bug: calling `Enabled()` had the side-effect of computing `PeerCount` from `--ipalloc-init consensus=x`, so if it was called twice you would get a fatal error.
```
$ weave launch --ipalloc-init='consensus=3' --awsvpc
The weave container has died. Consult the container logs for further details.
$ docker logs weave
[...]
FATA: 2017/05/26 15:14:47.541745 At most one of --ipalloc-init or --init-peer-count may be specified.
```

Remove deprecated --init-peer-count option

---

net/veth.go
plugin/net/cni.go
prog/weaveutil/attach.go
site/kube-addon.md
test/830_cni_plugin_test.sh
weave

excerpted from #2971 from @deitch
> As discussed with @bboreham , there is an issue wherein kubernetes in CRI seems to have forgotten to handle hairpin. In pre-CRI, when kubelet received the veth back from the CNI plugin, it enabled hairpin (or not, depending on the kubelet command-line setting).
This PR adds a `hairpinMode` to the CNI config file to match the CNI bridge plugin, with a default of "on".
It also adds a hairpin option to `weaveutil attach` but that option is not set so again the option defaults on. To be clear, this means hairpin will also be on for containers attached by `weave run`, `weave attach` and the proxy, in Weave Net 1.9.

Turn on hairpin mode on veth bridge ports

---

prog/weave-kube/weave-daemonset-k8s-1.6.yaml
prog/weave-kube/weave-daemonset.yaml

It is necessary in case when kubelet's args includes `--hostname_override=`.
Without this change, pods on hostname overriding kubelets will never be local,
and all pod's traffic will be blocked.

Weave-NPC should get hostname from K8s Downward API.

---

api/ipam.go
plugin/ipam/driver.go
prog/weaver/main.go
proxy/proxy.go
test/610_proxy_wait_for_weave_test.sh

Otherwise it doesn't clear out addresses when it dies.
This is currently causing test failures on master after merge of #3010 
Note change of behaviour: previously if a container died we would retain its owned address across a `weave` restart; now we drop that allocation.  This means if you were counting on your container getting the same address when it restarted, this is now less likely to happen if `weave` restarts at the same time.

Pass check-alive flag on claim for container

---

prog/weave-npc/main.go
test/run_all.sh

If it's destined for a pod on another node it will be checked again when it reaches that other node.  The previous version was rejecting traffic coming in from outside the cluster.
Fixes #3011

Allow any non-local traffic onto the weave bridge

---

site/kube-addon.md

See also: weaveworks/launch-generator#118
Tested successfully against Kubernetes 1.6.2, latest version of the Launch Generator, and Weave Net from `master`.
Fixes #2614.

Document Launch Generator's password-secret query parameter

---

net/veth.go
prog/weaveutil/main.go
prog/weaveutil/netdev.go
site/cni-plugin.md

This became unsafe when we started calling `AttachContainer` directly from the proxy.
We need two sub-functions which enter the container netns: one is called before we set the host end of the veth up, and one after.  Linux networking semantics require this split.
This leaves two instances of `WithNetNSUnsafe`: one from `weaveutil detach` and one when the CNI plugin configures routes.  In both cases the process exits straight away, so they are low risk.

Remove unsafe netns change in proxy

---

prog/weave-kube/weave-daemonset-k8s-1.6.yaml
prog/weave-kube/weave-daemonset.yaml
site/kube-addon.md

... but can be customised via the Launch Generator, as per the updated documentation.
Fixes #2990.

Kubernetes' seLinuxOptions are empty by default

---

prog/weave-kube/weave-daemonset-k8s-1.6.yaml

See also:
- weaveworks/launch-generator/pull/130
- weaveworks/launch-generator/pull/125
Command used:
```
$ curl -fsSo prog/weave-kube/weave-daemonset-k8s-1.6.yaml "https://localhost:8080/k8s/v1.6/net?v=latest"
$ curl -fsSo prog/weave-kube/weave-daemonset.yaml "https://localhost:8080/k8s/v1.5/net?v=latest"
```
Annotations then removed.

Update YAMLs to be what the Launch Generator serves.

---

npc/controller.go
npc/namespace.go
test/840_weave_kube_3_test.sh
test/images/network-tester/Dockerfile

This is another take on #3027 
Fixes #3025 
Here we wind back to how weave-npc worked as at 1.9.5, but still track an ipset of local pod addresses so we can stop checking when we know the destination is not a local pod (because we only want to check ingress rules)
I also extended test 840 to add a network policy which would catch the problem; see it fail at https://circleci.com/gh/weaveworks/weave/9262

weave-npc: stop ignoring local pods

---

prog/net-plugin/config.json
site/plugin-v2.md

Unfortunately, we can not set `--ipalloc-range` using `EXTRA_ARGS` plugin configuration parameter. It's just not take effect in `prog/net-plugin/launch.sh` and there is no way to change `--ipalloc-range` for plugin.
This PR simply add `IPALLOC_RANGE` as plugin configuration parameter and update documentation accordingly.

Ability to set IPALLOC_RANGE via plugin-v2 configuration parameters

---

prog/weave-kube/weave-daemonset-k8s-1.6.yaml
prog/weave-kube/weave-daemonset.yaml

Save people getting in to trouble when they don't know to add `-n kube-system`

Put kube-system namespace back in the weave-kube yaml

---

test/run_all.sh
weave

`proxy_parse_args` is currently called:
- once, all the time
- again, if Docker is configured with TLS.
If a second call to `proxy_parse_args` happens, given the way we append to `PROXY_ARGS` and merge proxy and remaining args, genuine arguments like peers can be mixed with flags/options/etc. hence forming an invalid peers list and crashing Weave Net.
Manually tested:
- with TLS enabled for Docker daemon,
- without it.
Fixes #3034.

No longer merge proxy and remaining args

---

net/bridge.go
prog/weaver/main.go
prog/weaveutil/bridge.go

The fix ensures that if odp is not supported (usually due to missing `openvswitch`, `vxlan` or `vport-vxlan` kernel modules), weaver will create the pcap based bridge instead of crashing.

Fix fallback to pcap based bridge when odp is not supported

---

prog/weaver/discovery.go

Currently, any `weave reset` or `weave rmpeer` is contacting the discovery back-end, which is pointless if you haven't configured a token.

Don't contact peer discovery back-end unless we have a token

---

bin/release

Currently our `Makefile` and `bin/release` scripts are such that we effectively do the following when releasing:
```
publish:
for arch in [amd64 arm arm64]:
sub-publish:
clean_bin
publish
plugin_publish
```
which leads the Docker v2 plugin to contain `arm64` binaries even though we target `amd64`.
Swaping `publish` and `plugin_publish` is a simple way to avoid this.

net-plugin release: swap publish and plugin_publish

---

site/kube-addon.md

Document examples of `weave` commands against/within a Kubernetes cluster.
This hopefully addresses part of #3052.
Documentation of best practices, examples of hybrid clusters, etc. are not included in this PR.

Add operations section to weave-kube's docs.

---

npc/controller.go
npc/controller_test.go
npc/iptables/iptables.go
npc/namespace.go
npc/rule.go

It looks like the order in which `NetworkPolicy` and `Namespace` events are received can break weave-npc's ipset creation.
Not sure why, but here's a test that demonstrates it
See https://weave-community.slack.com/archives/C2ND76PAA/p1499776696249627
Also #3059

Fix weave-npc race condition

---

weave

There are 3 ways to get help:
• `weave --help`
• `weave help`
• `weave <command> --help`
At the moment, only the first one prints the usage instantaneously, the
others go much further in the script and take quite some time, which is
not idea of impatient users.
Note that "help" only works because it's not a recognized command and
ends up in the default case of "case $COMMAND" (and indeed, "Unknown
weave command 'help'" is displayed). This is because handle_help_arg()
always returns true and so the second part of:
handle_help_arg "$1" || handle_help_arg "--$1"
is never evaluated.
This commit changes things a bit so all 3 ways to get help are
recognized early, print the usage and exit.

Make help instantaneous in the weave script

---

npc/controller.go
npc/controller_test.go
npc/ipset/ipset.go
npc/namespace.go
npc/rule.go
npc/selector.go

Fixes #2621 
This is based off of #3057, as I need to update the tests to match the new signature.
Example output:
```
root@hotcpc17686:~# iptables-save | grep WEAVE-NPC
:WEAVE-NPC - [0:0]
:WEAVE-NPC-DEFAULT - [0:0]
:WEAVE-NPC-INGRESS - [0:0]
-A FORWARD -o weave -j WEAVE-NPC
-A WEAVE-NPC -m state --state RELATED,ESTABLISHED -j ACCEPT
-A WEAVE-NPC -d 224.0.0.0/4 -j ACCEPT
-A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-DEFAULT
-A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-INGRESS
-A WEAVE-NPC -m set ! --match-set weave-local-pods dst -j ACCEPT
-A WEAVE-NPC-DEFAULT -m set --match-set weave-k?Z;25^M}|1s7P3|H9i;*;MhG dst -m comment --comment "DefaultAllow isolation for namespace: default" -j ACCEPT
-A WEAVE-NPC-DEFAULT -m set --match-set weave-iuZcey(5DeXbzgRFs8Szo]+@p dst -m comment …
```

Add comments to iptables rules and ipsets

---

site/kube-addon.md

* Fix doc regarding `git.io` short URLs: GitHub only allows `git.io` to point to content hosted under `github.com`, therefore it was not possible to have the short URLs point to Weave Cloud's Launch Generator.
* Replace `git.io/weave-kube` with `cloud.weave.works` for manual rollout under Kubernetes <=`1.5`,
*  in order to harmonise instructions, and 
* as the LG handles `1.4` and `1.5` slightly differently.
* Remove `-n kube-system` from `kubectl apply` commands, since no longer required from `2.0.1` onwards.
* EDIT: Remove the section commenting on git.io short URLs as this creates more confusion than add value for end-users.

Update weave-kube documentation

---

prog/kube-peers/main.go

It was a hack for a badly-configured Kubernetes install: it shouldn't be necessary, it will only work on an unsecured install, and it generates confusing error messages when something is really wrong.

Remove localhost:8080 fallback for Kubernetes api-server

---

site/tasks/ipam/stop-remove-peers-ipam.md

- "You cannot call `weave rmpeer` on more than one host" - yes you can, but you must not call it on more than one host *for the same peer*
- `weave forget` has nothing to do with this
- "results in duplicate IPs" - no, it causes duplicate address range assignments
- "the address is reassigned" - it's the address *range* that is reassigned
- "claim" is a new and confusing term -> drop
- "address space" -> "address range" (that's what it's called elsewhere)

clarify rmpeer caution in docs

---

prog/net-plugin/config.json

Otherwise, the plugin is not able to load kernel modules (openvswitch, vxlan, vport_vxlan) required by fastdp which makes weave to fallback to sleeve if the required modules are not loaded a priori.
`CAP_SYS_MODULE` is required in order to load kernel modules.

net-plugin: bind mount /lib/modules

---

test/run-integration-tests.sh

Currently:
- there is no easy way to change the way we install Docker from Net
- if `build-tools`' default was to change, Net could break.
This change addresses this situation.

Make Ansible's docker_install_role overridable

---

npc/rule.go
npc/rule_test.go

fix: Missing nil checks

---

bin/release
prog/weave-kube/weave-daemonset-k8s-1.7.yaml
test/840_weave_kube_3_test.sh

Fixes #2998 
`iptables` uses the file `/run/xtables.lock` so that if changes are under way, another instance of the `iptables` command can wait till it is finished.
We need to mount the lock file from the host to the container in order for this mechanism to work at all.
Note we rely on `kubelet` touching the file before running any pods - see https://github.com/kubernetes/kubernetes/pull/47212

Mount iptables lock file in weave-kube

---

.gitignore
Makefile
bin/release
test/Vagrantfile
test/run-integration-tests.sh

Due to differences in the GNU `sed` and BSD `sed`, the builds were broken on OSX. 
It's a small and simple fix: we tell sed an extension for backup files when carrying our in-place operations, and ignore the backup files in the `.gitignore`
Tested on Alpine Linux and OSX.

Fix builds on OSX

---

net/arp.go
net/bridge.go
net/ipsec/ipsec.go
net/veth.go
npc/namespace.go
prog/weave-npc/main.go
proxy/proxy.go

It's sad because this changes a regular pattern into an irregular one, which will create spurious diffs if more work is added at the end of the function.  Still, this is easier than fixing the lint runner to ignore the report.
And it's nice to have a PR that makes the code smaller.

 Remove explicit error check at end of functions to placate lint

---

proxy/hosts.go
proxy/proxy.go
weave

Fixes #3136 
Also add error reporting so it's easier to figure out next time something breaks.
Was broken in #2947

Add back EXEC_IMAGE so proxy can docker-run itself

---

prog/weaver/main.go
proxy/proxy.go

Fixing a few things I noticed in passing: principally that we were using some values from command-line parameters before calling `mflag.Parse()`.  But only in AWSVPC mode which nobody seems to use.
Also, if `--docker-api` is supplied, use that for the proxy instead of the default setting.

Improve flag handling

---

api/ipam.go
prog/kube-peers/annotations.go
prog/kube-peers/main.go
prog/weave-kube/launch.sh
prog/weave-kube/weave-daemonset-k8s-1.6.yaml
prog/weave-kube/weave-daemonset-k8s-1.7.yaml
prog/weaver/main.go
test/870_weave_recovers_unreachable_ips_on_relaunch_3_test.sh
test/config.sh
test/run-integration-tests.sh

PR to fix #2797. Includes changes from #3022.

Fix 2797 on Kubernetes - Cluster goes down because all IPs become unreachable

---

prog/kube-peers/main.go
prog/weave-kube/launch.sh

If the persistence file doesn't exist (and it doesn't on first install), there's no point doing all the other checks to see if we should delete it.
And I was worried about what would happen if a user installs the new image with the old manifest, without adding the additional annotation permissions;  added `|| true` to make sure we continue past the `kube-peers reclaim` on error.  
Also, in that error case, it would report `Added myself to peer list <nil>`, so I fixed that too.

Rearrange peer reclaim checks in weave-kube launch script

---

npc/controller.go
npc/controller_test.go
npc/ipset/ipset.go
npc/namespace.go
npc/selector.go

There was a bug in handling `default-allow` ipsets - it could not cope with out of order receive of Pod updates. E.g:
1) `AddPod(Pod_A, PodIP_A)`,
2) `AddPod(Pod_B, PodIP_A)`,
3) `DeletePod(Pod_A)`,
would result with `PodIP_A` being removed from `default-allow` ipset, as such ipset entries were not refcounted. Bypassing of refcounting was due to the fact that adding a netpol which dst-selects a Pod which IP addr is in `default-allow` ipset has to remove the IP addr from the ipset regardless of refcount value of the IP addr entry in the ipset. So, refcounting in such case didn't make sense and it was bypassed.
This commit changes the way entries are refcounted in ipsets, and it makes `default-allow` ipset the same citizen as other ipsets, so from now `default-allow` ipset is refcounted. …

npc: Track ipset entries per user and refcount default-allow ipsets

---

prog/kube-peers/annotations.go
prog/kube-peers/main.go

There was a subtle problem with copying a map by reference, so the copy actually changed the data in the original so it looked like the operation succeeded.
This problem was masking another problem, that the keys used for annotations to mark a peer as 'currently being removed' contained `:` characters which are not allowed by Kubernetes.
The big improvement is to use the updated data that comes back from `Update()`, even after an error.
Fixes #3190 
I have tested this by creating a 10-node cluster using kops, then scaling down to 5 nodes, then scaling back up to 10 nodes, finally using the `nettest` image to check that 30 pods can all talk to each other.

Fix ipam reclaim

---

bin/release

We should never update the `latest_release` plugin on a `PRERELEASE` (meaning something not tagged like 2.1.4 or flagged as prerelease on GitHub)
We should always update it on a `MAINLINE` or `BRANCH` release (meaning the version name matches a pattern like 2.3.0 or 2.1.9)
Fixes #3150

Fix release script for plugin latest_release

---

prog/net-plugin/config.json
prog/net-plugin/launch.sh

Weave-net-plugin has `debug` as default log level without any way to change it. It is makes docker daemon logs (which we can get through `journalctl -u docker`) unreadable because there are a lot of useless debug messages from weave, like this:
ERRO[3989] DEBU: 2017/12/12 14:39:05.033040 Expiring flow FlowSpec{keys: [UnknownFlowKey{type: 25, key: 00000000000000000000000000000000, mask: 00000000000000000000000000000000} BlobFlowKey{type: 20, key: 00000000, mask: 00000000} BlobFlowKey{type: 2, key: 00000000, mask: 00000000} InPortFlowKey{vport: 1} BlobFlowKey{type: 15, key: 00000000, mask: 00000000} UnknownFlowKey{type: 22, key: 00000000, mask: 00000000} UnknownFlowKey{type: 23, key: 0000, mask: 0000} UnknownFlowKey{type: 24, key: 00000000, mask: 00000000} BlobFlowKey{type: 6, key: 0000, …

Add ability to set log level for net-plugin, and default to INFO

---

npc/json.go

Log size of weave-npc was getting out of hand.  We currently run at debug level by default, which includes a full JSON dump of every Kubernetes objects received.
Remove things like "args" and "env" which bulk the logs, aren't relevant to the function of weave-npc, and may include sensitive information.
Use a black-list rather than a white-list because we can't be sure what information will be necessary in future.

Trim the JSON logged for Kubernetes objects by weave-npc

---

site/kubernetes/kube-addon.md

https://v1-7.docs.kubernetes.io/docs/api-reference/v1.7/#networkpolicy-v1-networking/ ---> https://v1-6.docs.kubernetes.io/docs/api-reference/v1.6/#networkpolicy-v1beta1-extensions

Fix link to k8s legacy netpol docs

---

test/Vagrantfile

To be able to run k8s smoke tests.

Give more memory to vagrant test machines

---

common/odp/odp.go
net/bridge.go
net/netlink.go
net/veth.go
plugin/net/driver.go
prog/weaver/main.go
prog/weaveutil/attach.go
prog/weaveutil/bridge.go
prog/weaveutil/main.go
test/191_create_bridge_2_test.sh
weave

I recommend to review each commit separately.
This PR does a few things:
- Removes `create_bridge` from the weave script. As a consequence, `weave attach $CIDR $CONTAINER` is no longer possible without running weaver.
- Removes unnecessary `create_bridge` from `weave expose` and `weave hide`.
- Makes `net/bridge.go:EnsureBridge` do not skip creation of the bridge if such already exists, and also makes the function idempotent.
Part of the #3133 fix; going to add netlink subscribe for changes to the bridge in a separate PR.

Do not skip bridge creation if bridge exists

---

net/bridge.go
test/840_weave_kube_3_test.sh

We want our DROP rule to be executed ahead of any ACCEPT rules which might have been added by another program on the host.
Since #3204 gave us the framework to ensure we are recreating every rule, just inserting them all at the top, in order, works nicely.
~I also moved the NFLOG and DROP rules from FORWARD to WEAVE-NPC to simplify the logic about which order they come in.~
Extend kubernetes test to include the circumstances that trigger the issue.
Fixes #3209

Move weave-npc checks to top of FORWARD chain

---

net/bridge.go
test/191_create_bridge_2_test.sh

* The "-i docker0 -o weave -j DROP" filter/FORWARD rule used to be inserted after the "-j WEAVE-EXPOSE" rule, so the subnet isolation has been broken for exposed subnets. This was the reason for the 130 smoke test failure.
* Add comment to note the importance of the order of the "-j WEAVE-NPC" rule.
* Improve naming of `ensureRules` function.
* ~Update k8s to 1.9.2 in CI.~
* Update build tools fix flaky tests due to the defunct process.

Fix subnet isolation and bump build-tools to latest

---

prog/weaver/main.go
proxy/create_container_interceptor.go
proxy/proxy.go
proxy/start_container_interceptor.go
weave

Part of #1770 
* Make proxy use configured WeaveDNS address rather than assuming it is listening on the docker bridge
* Remove obsolete --dns-effective-listen-address parameter
* Pass the WeaveDNS Domain into the proxy instead of obtaining it via the http api
Remaining work on #1770 is to modify the `weave` script to respect the `--dns-listen-address` parameter and document it.

Make proxy use configured WeaveDNS address

---

site/kubernetes/kube-addon.md

A quick fix.
LG generates secretKeyRef.key w/o the ".txt" extension which makes it inaccessible to weave-kube when passwd is stored in "weave-passwd.txt".

Fix HOWTO for setting weave-kube passwd

---

npc/analyser.go
npc/controller_test.go

There was a bug in the npc analyser when adding a netpol with dstSelector == srcSelector. The analyser was overwriting dstSelector with srcSelector which resulted in Pod selected by dstSelector not being removed from a corresponding "default-allow" ipset.
This applies only to non-legacy netpols.
Fix #3222

Fix bug when dstSelector is overwritten by srcSelector

---

npc/controller_test.go
npc/namespace.go

Fix for https://github.com/weaveworks/weave/issues/3247
On namespace deletion default `ipset` will cleaned for the namespace

Delete defaultAllowIPSet on namespace delete

---

prog/weave-kube/weave-daemonset-k8s-1.7.yaml

During a rolling update we don't want Kubernetes to go as fast as it can across nodes, because each node will have a short interruption as iptables rules are recreated.
I think this will also have the effect of slowing down a first install, but hopefully people can wait a few extra seconds.
I picked 5 seconds somewhat arbitrarily; the setting may need more experimentation.
Note we don't specify a readiness check at the moment, so Kubernetes equates "running" with "ready".  If the pod crashes immediately it will not be ready.

Wait 5 seconds to let pod connect before rolling next pod

---

build/Dockerfile
ipam/testutils_test.go
vagrant-common.rb

I have changed the golang image from golang:1.8.1 to golang:1.8.7-stretch.
I have chosen stretch version because the ubuntu version used in vagrant is stretch compliant when we check the ``/etc/debian_version`` file.
Concerning the tests. Some tests failed but I think it does not come from the golang image. I have never built before, I don't know if it is normal in the current state of the project that those tests below failed.
> Ran 73 tests, 4 failed
> Fail /home/vagrant/weave/test/602_proxy_docker_py_test.sh
> Fail /home/vagrant/weave/test/150_connect_forget_2_test.sh
> Fail /home/vagrant/weave/test/870_weave_recovers_unreachable_ips_on_relaunch_3_test.sh
> Fail /home/vagrant/weave/test/840_weave_kube_3_test.sh

issue 3245 - change golang version

---

site/faq.md

Have seen a couple of these in the last few days.
e.g. https://groups.google.com/a/weave.works/forum/#!forum/weave-users

Add 'peer names collision' to FAQ

---

prog/weave-kube/launch.sh

Raise weave-kube default connection limit from 30 to 100

---

build/Dockerfile

go1.10.1 includes the fix: https://github.com/golang/go/issues/23995

Use go1.10.1 for building

---

prog/weave-kube/launch.sh
prog/weaver/main.go
site/kubernetes/kube-addon.md
site/tasks/manage/metrics.md

The handler for `--status-addr` exposes `/metrics`, `/status` and `/report`, and since we listen on 0.0.0.0 by default in weave-kube this could be attacked.
Change the default to only answer `/metrics`, while retaining compatibility for anyone who set the `WEAVE_STATUS_ADDR` variable.

Only expose metrics by default in weave-kube

---

docs/k8s-src-ip.md

I compiled the doc to list src IP addr of a packet destined to a k8s Service as a part of my work on #2924. Additionally, I checked whether in all cases packets enter the `filter/WEAVE-NPC` chain (= NetworkPolicy can be enforced; I'm going to create a separate issue for the cases where it doesn't).

Add docs/k8s-src-ip.md

---

Makefile
prog/weave-kube/Dockerfile.template
prog/weave-npc/Dockerfile.template
prog/weavedb/Dockerfile
prog/weaveexec/Dockerfile.template
prog/weaver/Dockerfile.template

Why? What?
- This should ultimately help for image-to-code back references.
- `org.label-schema.*` labels are now deprecated, in favour of `org.opencontainers.image.*` labels.
See also: https://github.com/opencontainers/image-spec/blob/master/annotations.md#back-compatibility-with-label-schema
- Git revision is now injected at `docker build` time.
Testing
```console
$ docker inspect weaveworks/weave
[
{
[...]
"ContainerConfig": {
[...]
"Labels": {
"maintainer": "Weaveworks <help@weave.works>",
"org.label-schema.description": "Weave Net creates a virtual network that connects Docker containers across multiple hosts and enables their automatic discovery",
"org.label-schema.name": "Weave Net",
"org.label-schema.schema-version": "1.0",
"org.label-schema.url": "https://weave.works", …
```

Add org.opencontainers.image.* labels to Dockerfiles

---

site/tasks/ipam/troubleshooting-ipam.md
site/troubleshooting.md

I put full instructions on the 'troubleshooting ipam' page, and a pointer from the 'troubleshooting' page.
Maybe we should also have a pointer from the Kubernetes Addon page.

Add instructions for 'seeded by different peers' message

---

docs/release-process.md

Extended docs to prevent such mishaps as #3276.
Perhaps we could automate this step, but it would be good to merge #3268 first, as it changes manifest-tool location.

Add instruction for validating whether imgs were pushed for all platforms

---

npc/ipset/ipset.go
prog/weave-npc/main.go
test/840_weave_kube_3_test.sh

Should fix #3289, although as mentioned there I couldn't get it to break on a 4.13 kernel.
I didn't try 3.10.

Make the ipset list size bigger

---

Makefile

The master branch builds are currently failing with:
```
make DOCKER_HOST= DOCKERHUB_USER=weaveworks WEAVE_VERSION=git-d15439aeac6a UPDATE_LATEST=latest-only push_ml_weave push_ml_weaveexec push_ml_weave-kube push_ml_weave-npc
make[1]: Entering directory `/home/ubuntu/src/github.com/weaveworks/weave'
"docker run --rm -v OME/.docker:/.docker weshigbee/manifest-tool --docker-cfg=/.docker" push from-args --platforms linux/amd64,linux/arm,linux/arm64,linux/ppc64le --template weaveworks/weave-ARCH:latest --target weaveworks/weave:latest
/bin/sh: 1: docker run --rm -v OME/.docker:/.docker weshigbee/manifest-tool --docker-cfg=/.docker: not found
```

Fix $HOME usage in Makefile

---

prog/kube-peers/main.go

Avoid getting into an infinite loop if some of the logic or underlying data is bad
#3310 has an example of one infinite loop:
```
DEBU: 2018/06/05 11:15:32.615919 [kube-peers] Preparing to remove disappeared peer {46:f4:4b:41:dd:11 ip-10-83-124-112.ec2.internal}
DEBU: 2018/06/05 11:15:32.615928 [kube-peers] Existing annotation 46:f4:4b:41:dd:11
DEBU: 2018/06/05 11:15:32.815841 [kube-peers] Nodes that have disappeared: map[ip-10-83-124-112.ec2.internal:{46:f4:4b:41:dd:11 ip-10-83-124-112.ec2.internal}]
DEBU: 2018/06/05 11:15:32.815867 [kube-peers] Preparing to remove disappeared peer {46:f4:4b:41:dd:11 ip-10-83-124-112.ec2.internal}
DEBU: 2018/06/05 11:15:32.815877 [kube-peers] Existing annotation 46:f4:4b:41:dd:11
DEBU: 2018/06/05 11:15:33.016143 [kube-peers] Nodes that have disappeared: …
```

Break out of kube rm-peers loop if nothing changes

---

prog/weave-kube/weave-daemonset-k8s-1.7.yaml

Fixes #3332
This permission is needed to update the node NetworkUnavailable condition see https://github.com/weaveworks/weave/issues/3249

Add permissions to set node status

---

plugin/net/cni.go

adding a check to verify if network namespace is not host network namespace
Fixes #3206

3206: Protect against CNI plugin being called with the host namespace

---

site/install.md
site/kubernetes/kube-addon.md

The Kubernetes project only supports three versions back, which is 1.8, 1.9 and 1.10 as of today.
The text I have removed is for people upgrading from 1.5 to 1.6, so well beyond that policy.  It's unnecessary and possibly confusing.
cc @abuehrle for interest

Remove mention of Kubernetes 1.6 from docs: it's very old now

---

bin/release
prog/weave-kube/weave-daemonset-k8s-1.8.yaml
test/840_weave_kube_3_test.sh

Creates a new prog/weave-kube/weave-daemonset-k8s-1.8.yaml with type "FileOrCreate" based on the existing 1.7 one. 
I tried to take care of the release and testing too but I might be missing something. Feel free to correct me if that's the case.
Fixes #3351

Fix xtables.lock race condition between weave and kube-proxy.

---

net/bridge.go
net/iptables.go
npc/analyser.go
npc/constants.go
npc/controller.go
npc/controller_test.go
npc/ipblock.go
npc/namespace.go
npc/rule.go
npc/rule_test.go
npc/selector.go
npc/types.go
prog/weave-kube/weave-daemonset-k8s-1.7.yaml
prog/weave-npc/main.go
prog/weaver/main.go
site/kubernetes/kube-addon.md
test/840_weave_kube_3_test.sh
test/images/network-tester/Dockerfile
weave

This PR implements Kubernetes Egress Network Policy (defined in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#networkpolicyspec-v1-networking-k8s-io).
Some important changes are mentioned/explained below.
Each "weave" packet (=sent over the `weave` bridge) is first checked against egress and then against ingress rules. 
For Egress NPC we introduce the following rules:
```
-A WEAVE-NPC-EGRESS -m state --state RELATED,ESTABLISHED -j RETURN
-A WEAVE-NPC-EGRESS -m set ! --match-set weave-local-pods src -j RETURN
-A WEAVE-NPC-EGRESS -d 224.0.0.0/4 -j RETURN
-A WEAVE-NPC-EGRESS -m state --state NEW -j WEAVE-NPC-EGRESS-DEFAULT
-A WEAVE-NPC-EGRESS -m state --state NEW -m mark ! --mark 0x40000/0x40000 -j WEAVE-NPC-EGRESS-CUSTOM
-A WEAVE-NPC-EGRESS -m state --state NEW -m …
```

Implement Egress NPC

---

weave

We suggest to run `weave reset` when weaver detects an existing bridge of different type than the requested one.
In case of Kubernetes, if a user runs `weave reset`, it returns `Weave is not running` which might make the user think that `weave reset` was not successful (happened in https://github.com/weaveworks/weave/issues/3318).

Make error "Weave is not running" less confusing when running on Kubernetes

---

test/config.sh

Instead of printing their count, print who they are. Should help to investigate #3361.

Print defunct processes if such exist

---

prog/weaveutil/container.go
prog/weaveutil/container_test.go

Allows `-l` or `--label` flag to be passed to the `run-container` command which starts Weave.
Fixes #3370 
Also a test.

Parse labels

---

npc/analyser.go
site/kubernetes/kube-addon.md
test/840_weave_kube_3_test.sh

This PR enables ipBlock in k8s Ingress netpol as described in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#networkpolicy-v1-networking-k8s-io.
When using the feature, one should be aware that in many cases a packet source IP addr gets mangled before reaching the `filter/FORWARD` chain in which the NPC filtering takes place. So, policies using ipBlock in ingress might not be applied to the packet. See https://github.com/weaveworks/weave/blob/master/docs/k8s-src-ip.md for the cases.
However, in some cases it is possible to disable mangling by setting `externalTrafficPolicy` to `Local`. See https://kubernetes.io/docs/tutorials/services/source-ip/.
Fix #3168 #3347

Add ipBlock support for Ingress netpol

---

weave

add missing --token argument in help for `weave launch`

---

net/bridge.go

Monitor and throw error message in the logs if Weave bridge interface is found to be in DOWN state
Fixes #3133 Do something more useful when the weave bridge is DOWN
On Weave restart there is already logic in place to create the bridge interface
and bring it up, this fix only monotors the weave bridge interface and logs error if
it is in DOWN state

Monitor and throw error message in the logs if Weave bridge interface is down

---

docs/entrypoints.md
site/kubernetes.md
site/kubernetes/kube-addon.md
test/860_weave_kube_portmap_3_test.sh
test/config.sh
weave

Fix to use `10-weave.conflist` instead of `10-weave.conf` as CNI config file.
Also adds support for `portmap` as additional plugin along with weave-net
Fixes #3016

support for portmap as additional plugin with wave-net

---

prog/kube-utils/main.go

Otherwise, such node will be rmpeer'd which can lead to the IPAM inconsistencies `"Received update for IP range I own at <..>"`.
Fix #3392 and maybe #3310.

Do not exclude k8s node without any IP addr in reclaim

---

site/install/installing-weave.md

- point to up-to-date AMIs
- remove reference to out-of-date ECS guide
closes #3338

docs: update ECS references

---

prog/kube-utils/main.go

If we can see that a different peer was previously running with the same node name, mark it for reclaim.
This is a straightforward change to improve #3394, but not a full fix, which would involve storing the UID and dealing with upgrading from a previous version which didn't store it.

Reclaim IPs when node name is re-used

---

ipam/http.go

In some cases, we do not create any IPAM tracker, which leads to a panic when GET'ing /ipinfo/tracker.
Fixes #3405.

ipam: Do not deref nil in GET /ipinfo/tracker if tracker doesn't exist

---

prog/kube-utils/main.go
prog/kube-utils/peerlist.go
prog/kube-utils/peerlist_test.go

handles an edge case where peer claimed to own the action to reclaim but no longer exists hence lock persists forever, fix makes a peer own the reclaim when nonexistent node found
Fixes #3386

own action to reclaim when peer does not exist

---

prog/weave-kube/weave-daemonset-k8s-1.6.yaml
prog/weave-kube/weave-daemonset-k8s-1.7.yaml
prog/weave-kube/weave-daemonset-k8s-1.8.yaml
prog/weave-kube/weave-daemonset.yaml

The liveness probe has the not-so-great side effect of killing the weave pods
if anything goes wrong, making debugging really difficult.
Not only that, we also bumped into the livenessProbe killing pods before they
had a chance to start (see below for the full story).
The readinessProbe is only used for Kubernetes Services: no traffic will be
routed to non-Ready pods when using the Service IP. We can use to to signal the
user something in wrong with Weave Net while not having Kubernetes delete the
pods behind our backs.
I removed the ininitialDelaySeconds field as Kurbernetes won't kill the pod if
not ready.
Notes from a debugging session:
Some nodes may have a vast amount of iptables rules, making each iptables
command take a few seconds (~5-10s). At startup, when the weave container …

kubernetes: Morph the livenessProbe into readinessProbe

---

router/fastdp.go
router/network_overlay.go
router/overlay_switch.go
router/sleeve.go

changes differentiate beteween fatal errors (for e.g. ipsec init)
from transient errors (heartbeast misses). In case of transient
errors OverlayForwarder is marked to be unhealty. When overlay forwarder
is unhealty its kept on hold so chooseBest() will skip selecting the forwarder
Once OverlayForwarder is considered healthy run chooseBest() again so the
forwarder can be selected if its the best forwarder
Fixes #1737

Add logic to re-try chooseBest() (which will select best forwarder)

---

npc/namespace.go
prog/weave-npc/main.go

by-pass ingress network policy chains and accept the packet if
destination is not one of the local pods
return the packets so the egress network policy chains are skipped
in case packet's source is not one of the local pods
Fixes #3344

Replace weave-local-pods ipset with physdev iptables rule

---

Gopkg.lock
vendor/github.com/weaveworks/go-odp/odp/datapath.go
vendor/github.com/weaveworks/go-odp/odp/dpif.go
vendor/github.com/weaveworks/go-odp/odp/flow.go
vendor/github.com/weaveworks/go-odp/odp/genetlink.go
vendor/github.com/weaveworks/go-odp/odp/vport.go

To include the fix https://github.com/weaveworks/go-odp/pull/7.
TL;DR: without this fix, `fastdp` would fail to work on the 4.19 kernel.
Thanks @lkpdn for spotting and providing the fix.

Bump go-odp dependency

---

build/Dockerfile

See https://github.com/golang/lint/issues/415.
Otherwise building the container image fails with:
```
---> Running in 949e82e8efa5
package github.com/golang/lint/golint: code in directory /go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
```
We do not checksum the downloaded artifacts.

Fix and improve build/Dockerfile

---

net/bridge.go

Prior ["bridge: Change local fdb entries whenever mac address of bridge device changes"][1], FDB entry for a bridge was not inserted when creating the bridge and it could only be inserted when a hw address of the bridge was changed. Therefore, on an older than the 3.14 kernel containers were not able to reach the `weave` bridge w/o setting the promiscuous mode on.
This should have hit hard Kubernetes users as the weave bridge in their case is used as a default gateway, and thus it works only after manually enabling the promiscuous mode.
Additionally, w/o the promiscuous mode a packet sent from a container and destined to the gateway is flooded on all ports, so it can reach the `datapath` device resulting in the `"Vetoed installation of hairpin flow"` error.
Fix #3336 #3297 #3239 (and …

net: Do not set bridge hw addr when creating it

---

prog/weave-npc/main.go

add --physdev-is-bridged flag when using physdev module for iptables rules created by weave-npc to prevent warning in kernel logs
Fixes #3449
Since previous iptables chains rules are flushed on weave pod start, fix works for both fresh install and upgrades.

add --physdev-is-bridged flag when using physdev module for iptables

---

prog/kube-utils/main.go

prevent kubernetes node connecting to self by excluding the node IP from the list of the peers passed to weaver
Fixes #3398

prevent kubernetes node connecting to self

---

prog/weave-kube/launch.sh

handle single node case where return peer list from kube-utils is empty resulting in launch.sh failing to launch weaver
fixes side affect introduced in #3454

handle single node case where return peer list from kube-utils is empty

---

site/kubernetes/kube-addon.md

Only `info` and `debug` log levels were mentioned in the documentation.
Fixes #2834

Document weave log warning and error levels

---

ipam/ring/ring.go

bump up the version of entry by large value so that transfer of range takes precedence (if there is any conflict in merging entry) over other operations on the entry
that increments the version
Fixes #3612

bump up the version of entry by large value so that transfer of range takes precedence

---

prog/kube-utils/annotations.go
prog/kube-utils/main.go
prog/kube-utils/peerlist_test.go
testing/kubernetes/testing/fixture.go

Re-read peers ConfigMap from Kubernetes at start of every reclaim - a previous reclaim may have left the map set to nil.
Fixes #3613 
Also make test harness and comments match Kubernetes behaviour on conflict error,
and error instead of panic if we still do somehow have a nil map

Avoid panic on nil map in reclaimPeer()

---

router/sleeve.go

Debugging an issue yesterday I realised this message is nearly useless because you have no idea which connection it refers to.
Also remove `EMGSIZE` because it catches the eye and looks like an error in the log file.
Maybe we should just remove this message, or move it to debug level?  I'm not sure why we need it.

Improve 'expecting PMTU update' message with address

---

npc/controller.go
prog/weave-npc/main.go

does not address #3464 but just avoids the issue atleast for those who
don't use network policies

lazily add iptables rule to drop egress traffic from the pods only if network policies are applied

---

plugin/net/cni.go

return error in case Weave CNI plug-in fails to perform CmdDel so that kubelet will retry DEL (preventing IP leak)
Also if there are no IP's associated with container iD just return (so that its idempotent) with out raising error. With out this change, if kubelet fails to perform successful ADD, it would perform DEL (as part of cleanup) with containerid. Weave IPAM will return an error as there are no IP's associated, resulting in kubelet performing the operation unsuccessfully (resulting in retry's forever).
Fixes #3587

return error in case Weave CNI plug-in fails to perform CmdDel 

---

docs/k8s-src-ip.md

With cluster IP, traffic is masquraded only when --masquerade-all option is specified
or --cluster-cidr is specified and the source is not from the cluster CIDR range
https://github.com/kubernetes/kubernetes/blob/v1.14.2/pkg/proxy/iptables/proxier.go#L842

Fix the incorrect case #4 in k8s-src-ip.md

---

ipam/allocator.go
ipam/ring/ring.go
ipam/ring/ring_test.go

implements tie-breaker suggestions in #1962 and unit-tests to test the behaviour
Fixes #1962

resolve inconsistencies detected during ring merge

---

npc/analyser.go
npc/controller.go
npc/controller_test.go
npc/namespace.go
npc/selector.go
prog/weave-npc/main.go

- enhance selectorSpec to accommodate both pod and namespace selectors
- enhance analysePolicy to handle policies with both selectors
Fixes #3312

add support for combination of podSelector and namespaceSelector in network policies

---

test/600_proxy_docker_py.sh

Pin busybox version to 1.28 to avoid CI failure in Python test

---

prog/weave-kube/weave-daemonset-k8s-1.6.yaml
prog/weave-kube/weave-daemonset-k8s-1.7.yaml
prog/weave-kube/weave-daemonset-k8s-1.8.yaml

If you add nodes with the following taint:
```
kubectl taint nodes node1 key1=value1:NoExecute
```
Weave is evicted from the node, and thus, the node will not be able to start any new pods due to it not being able to resolve network endpoints. By allowing the Weave DaemonSet to tolerate a `NoExecute` taint, Weave will run on these tainted nodes marked to avoid execution, as it should.
---
This is was found because I have a set of nodes that are marked with `NoExecute` so only certain applications that tolerate the taint can run on them. Turns out one of those certain applications became Weave. Pods that were running before I applied the taint were fine, but pods that were schedule after Weave was evicted from the node were unable to start and left in a `Pending` state.

Add tolerations for nodes tainted with NoExecute

---

bin/release
prog/weave-kube/weave-daemonset-k8s-1.9.yaml
test/840_weave_kube_3_test.sh

Move daemonset API to apps/v1

---

router/fastdp.go

It is possible for ipsec.InitSARemote to be called after ipsec.Destroy.
If an xfrm policy for that source/destination pair exists it will be
updated to the SPI from the Destroyed connection causing IPSEC to stop
working.
Fixes https://github.com/weaveworks/weave/issues/3675

Do not do ipsec.InitSARemote on a stopped fastDatapathForwarder.

---

npc/analyser.go
npc/controller_test.go

Fix https://github.com/weaveworks/weave/issues/3653

Fix iptable rules generated for Ingress NetworkPolicy when both port and IP block specified

---

net/ipsec/ipsec.go

Added a check to make sure the xfrm policy has not yet been updated to
a new spi. The ipsec mutex is held at this point so nothing else should
be modifying this policy.
Fixes #3666 
Fix was tested for 12 hours by constantly connecting and disconnecting network interfaces. The "xfrm not my policy" debug log was hit several times.

Fix incorrect xfrm policy being deleted by ipsec.Destroy().

---

prog/weave-kube/weave-daemonset-k8s-1.9.yaml

Currently, there is no explicit `dnsPolicy` specified, thus when the DaemonSet is deployed it gets the `ClusterFirst` policy. However, since the pods run with `hostNetwork: true`, the pods get configured with the DNS coming from the host instead of k8s. This means the out of the box weave pod would not be able to resolve any k8s service FQDNs. The more appropriate dnsPolicy would be `ClusterFirstWithHostNet` as that would ensure that the DNS resolution for any k8s services would be at least possible.

Change the dnsPolicy for the weave-net pods to ClusterFirstWithHostNet

---

common/docker/client.go

Docker [imposes a limit](https://github.com/moby/moby/blob/a6e1502575858cd063b0e75d400e04b6f334e86d/daemon/events/events.go#L107) that events have to be retrieved within 100ms or they are dropped on the sending side. Adding buffer space within the Weave Net process allows those events to be collected from Docker more quickly.
1024 is an arbitrary number, much higher than we expect to need.
Fixes #3432

Use buffered chan to avoid losing docker events

---

Makefile
build/Dockerfile

Changes details:
1) In Makefile have added cross build support w.r.t s390x .
2) Updated the build/Dockerfile to substitute  `golang:1.10.1-stretch` with `golang:1.12.7-buster` . As the debian:buster image already  has crossbuild-essential-${platform} binaries in it's repo, so I have removed the addition of emdebian repository in the repolists which was used  earlier that referred to the crossbuild-essential binaries.
I have verified and tested native and cross ARCH build of binaries and Images with these changes.

Build with Go 1.12.7; Added support for crossbuilding s390x binaries and images

---

prog/weave-kube/weave-daemonset-k8s-1.11.yaml

* fixes #3691; PR as discussed with @murali-reddy 
* `weave-daemonset-k8s-1.11.yaml` is `weave-daemonset-k8s-1.9.yaml` plus `priorityClassName: system-node-critical`
* notice that a Kubernetes cluster deployed with `kubeadm` has its `kube-proxy`s marked as `system-node-critical` (and several other pods, such as `kube-apiserver`, marked as `system-cluster-critical`)
```
diff weave-daemonset-k8s-1.9.yaml  weave-daemonset-k8s-1.11.yaml
211a212
>           priorityClassName: system-node-critical
```

mark pods weave-net with priorityClassName: system-node-critical

---

prog/kube-utils/main.go

This is a minor noise reduction - we already avoid actually doing the delete, but adding this check stops the program logging that it was thinking about it.
Also it goes round the loop three times wondering what happened.
```
INFO: 2019/10/10 12:39:39.717889 Our name is ea:46:33:c1:c2:0b(test-12533-0-0)
[...]
INFO: 2019/10/10 12:39:40.731487 [kube-peers] Added myself to peer list &{[{7a:ae:37:39:0e:52 test-12533-0-1} {4e:b7:93:6b:2b:49 test-12533-0-2} {ea:46:33:c1:c2:0b test-12533-0-0}]}
DEBU: 2019/10/10 12:39:40.754070 [kube-peers] Nodes that have disappeared: map[ea:46:33:c1:c2:0b:{ea:46:33:c1:c2:0b test-12533-0-0}]
WARN: 2019/10/10 12:39:40.754200 [kube-peers] not removing myself {ea:46:33:c1:c2:0b test-12533-0-0}
DEBU: 2019/10/10 12:39:40.765571 [kube-peers] Nodes that have …
```

Exclude myself when building a list of peers that may need deleted

---

prog/kube-utils/main.go
prog/kube-utils/peerlist_test.go
test/870_weave_recovers_unreachable_ips_on_relaunch_3_test.sh

Fixes #3690 - we should shut down Kubernetes before deleting the node otherwise Weave Net can restart.
While debugging this I found a few other things wrong with the `kube-utils` program, notably that the randomised wait would always take 3.081 seconds so we got a thundering herd every time.
And reduce the wait in the test script - now we have a callback when a node is removed and ipam broadcasts the reclaim, there should be no reason to wait 90 seconds.

Randomise wait to reclaim IPs on node deletion, and fix flaky test 870

---

ipam/allocator.go
ipam/ring/ring.go
ipam/ring/ring_test.go

Fixes #3693 
`Ring` wraps around at zero but `Space` doesn't know about this, so we have to normalise ranges coming out of `Ring`.  In turn we may need to split one range into two, across the end of the `Ring`.
The unit tests passed because they are calling `distance` inside the Ring package, which understands the wrap-around.  We may want to make them more realistic, maybe move up to `ipam` package.
Also log the event when we do accept another peer's token, since that should be a rare event, and it's important if we've made a mistake.

Handle range wrap-around when checking for allocations

---

Gopkg.lock
test/150_connect_forget_2_test.sh
test/191_create_bridge_2_test.sh
test/210_dns_cross_hosts_3_test.sh
test/215_stale_dns_3_test.sh
test/380_ipam_seed_2_test.sh
test/800_plugin_cross_hosts_2_test.sh
vendor/github.com/weaveworks/mesh/README.md
vendor/github.com/weaveworks/mesh/connection.go
vendor/github.com/weaveworks/mesh/connection_maker.go
vendor/github.com/weaveworks/mesh/local_peer.go
vendor/github.com/weaveworks/mesh/overlay.go
vendor/github.com/weaveworks/mesh/peers.go
vendor/github.com/weaveworks/mesh/protocol.go
vendor/github.com/weaveworks/mesh/router.go
vendor/github.com/weaveworks/mesh/routes.go
vendor/github.com/weaveworks/mesh/status.go
vendor/github.com/weaveworks/mesh/surrogate_gossiper.go

This release has a number of changes to defer updates by up to one second, to reduce the cpu usage of route recalculation and reduce network bandwith for topology updates.
The effect is it behaves much better on networks of over 100 nodes.

Update weaveworks/mesh to v0.3

---

prog/kube-utils/main.go

Handling concurrent updates to configmap and IP reclamation by multiple weave instances to fix #3722 
Signed-off-by: mmerrill3 <michael.merrill@vonage.com>

Handling concurrent updates to configmap and IP reclamation

---

ipam/allocator.go
ipam/claim.go

Test 320 has been failing consistently in CI, because an IP address claim fails on first attempt.
Probably this is because topology gossip has been slowed down.
This PR allows claims to be retried a few times before giving up.
Also add the error message why an IP claim is denied, if we have one, to make troubleshooting easier.

Retry IP allocator claims

---

.circleci/config.yml
Makefile
build/Dockerfile

After merging #3685 which took us to 1.12.7, I figure we may as well jump to the latest.
Needs an update to the `tools` submodule to cope with changes in `go vet`

Update to Go 1.13.3

---

test/320_claim_3_test.sh

Fixes #3727 
We were seeing flakes in test 320, seemingly because the `docker run` command would sometimes send a delete request for the container it had started, before dying.
We need the container to carry on running so we can check it does get attached when the cluster reaches quorum. Sending signal 9 means the command dies immediately and does not get a chance to delete the container.

Tell 'timeout' to use signal 9, so command dies immediately

---

Gopkg.lock
ipam/testutils_test.go
testing/gossip/mocks.go
vendor/github.com/weaveworks/mesh/circle.yml
vendor/github.com/weaveworks/mesh/gossip.go
vendor/github.com/weaveworks/mesh/gossip_channel.go
vendor/github.com/weaveworks/mesh/lint
vendor/github.com/weaveworks/mesh/peers.go
vendor/github.com/weaveworks/mesh/router.go
vendor/github.com/weaveworks/mesh/routes.go

[Weave Mesh 0.4](https://github.com/weaveworks/mesh/releases/tag/v0.4) improves CPU, memory and network utilisation in larger clusters.
Instead of broadcasting topology changes to every peer, they are sent to 2log2 neighbours, so in a very sparse cluster the information will take a little longer to reach everyone but it drops the workload on cluster formation from O(N^2) to O(NlogN).
Also we slowed down the rate at which new connections are added: 100 connections will now take 4 seconds.

Update Weave Mesh library to 0.4

---

CHANGELOG.md
prog/weave-kube/launch.sh
prog/weaver/main.go

This release reduces CPU and memory usage in larger clusters, by sending notifications to a smaller set of peers and coalescing updates to reduce topology recalculation.
Full details in `CHANGELOG.md`.
The default soft limit on connections has been raised from 100 to 200.

Release 2.6

---

site/kubernetes/kube-addon.md

Prompted by a talk from @lizrice
We did have a note already in the [isolation](https://github.com/weaveworks/weave/blob/master/site/tasks/manage/application-isolation.md) file but it's nice to have a Kubernetes-specific one.

Add a note about dropping CAP_NET_RAW in Kubernetes

---

test/320_claim_2_test.sh

This was necessary when we didn't have ipam persistence, as the comment said "to remember the IPAM CRDT when we stop host2". 
But we have persistence to hold the CRDT so we don't need host3.
Rename the test so the test runner only gives it 2 hosts.

Remove the need for a third host in test 320

---

site/kubernetes/kube-addon.md

A newline in the markdown for the kube-addon docs was preventing _Kubernetes Service Debugging Guide_ from being rendered as a link.

Fix kube-addon documentation broken markdown link

---

bin/release

This is the manifest for Kubernetes 1.11 and above.
It was added to release 2.6 by hand, but this change will mean it gets included automatically next time.

Add weave-daemonset-k8s-1.11.yaml to release script

---

prog/weave-kube/weave-daemonset-k8s-1.11.yaml
prog/weave-kube/weave-daemonset-k8s-1.6.yaml
prog/weave-kube/weave-daemonset-k8s-1.7.yaml
prog/weave-kube/weave-daemonset-k8s-1.8.yaml
prog/weave-kube/weave-daemonset-k8s-1.9.yaml
site/kubernetes/kube-addon.md

This setting is passed by Kubelet to the Linux scheduler to ask for a share of available CPU, so we should ask for a bit more than 1% of 1 CPU. Otherwise if a CPU is contended Weave Net will get throttled frequently.
Weave Net in fastdp mode shouldn't need a lot of CPU most of the time, but at startup there is quite a lot to do.
The setting is also used by the Kubernetes scheduler to decide how much will fit on a node, so setting it much higher will reserve CPU that we shouldn't need most of the time.

Raise Kubernetes CPU requests from 10m to 50m

---

Makefile
prog/weave-kube/launch.sh
prog/weave-npc/launch.sh
site/kubernetes/kube-addon.md

Fixes #3465
- upgrade to alpine image (for amd64 only) with iptables 1.8.3
- updated alpine image bundles both (legacy and nftable) version iptables, iptables-save, iptables-restore
- by default  iptables* commands soft linked to iptables-legacy*
- user can explicitly specify the iptable backed
- have borrowed back-end detection logic from kube-proxy
need to test with Kubernetes 1.17 which has kube-proxy in nft mode

support Iptables 1.8 with legacy and nf_tables support

---

site/tasks/ipam/manual-ip-address.md

Fixes #3765 
As the issue notes, there was no hint on this page that `WEAVE_CIDR` is only read by the proxy.
This PR is a bit rudimentary; it would be nice to cross-link all the related pages, but I figured it would be better to get some improvement now.  Further improvements welcome!

Note different ways to ask for static IPs

---

prog/weave-kube/weave-daemonset-k8s-1.11.yaml
prog/weave-kube/weave-daemonset-k8s-1.8.yaml
prog/weave-kube/weave-daemonset-k8s-1.9.yaml

- add missing dnsPolicy: ClusterFirstWithHostNet in weave-daemonset-k8s-1.11.yaml
- update apiVersion from rbac.authorization.k8s.io/v1beta1 to rbac.authorization.k8s.io/v1
`dnsPolicy: ClusterFirstWithHostNet` was added in `weave-daemonset-k8s-1.8.yaml` but missing in `weave-daemonset-k8s-1.11.yaml`

fix weave-kube manifests

---

router/pcap.go

Fixes #3774 
The value is passed by google/gopacket into a signed 32-bit int, so we must pick a timeout which is less than 2^31 microseconds.
See https://github.com/google/gopacket/issues/708

Reduce pcap timeout to avoid overflow

---

router/fastdp.go

send FastDatapathCryptoInitSARemote control message only if encryption is enabled

---

net/bridge.go
net/netns.go
net/veth.go
plugin/net/driver.go
plugin/net/watcher.go
plugin/plugin.go
prog/weaver/main.go

To retain control over addressing and routing.
Slight refactor to keep the `/proc` path out of the weeds, and plumb through the setting to the Docker plugin rather than second-guessing it there.

Disable accept_ra on Weave Net interfaces

---

npc/metrics/metrics.go
prog/weave-npc/main.go

Replacement for #3794 - this is a bit simpler and covers more errors.
Introduce `weavenpc_policy_enforcement_errors` Prometheus metric to track number of errors occured during enforcing network policies.
Fixes #3791

metric for NPC errors

---

net/bridge.go
weave

We expect the loopback address 127.0.0.1 to only be accessible from the local host.
However under some Linux configurations it can be accessed remotely. https://github.com/kubernetes/kubernetes/issues/90259
Add an iptables rule to block this case.

Block non-local traffic to the Weave control port

---

bin/provision_test_vms.sh
test/run-integration-tests.sh

Sparked by builds failing due to some tool no longer working with Python 2.
Move Ansible install to run only where need it, when we create VM images.
Bonus: this knocks about a minute off the run time!
(The image-creating part needs updates too - see #3687)

Move ansible install out from every CI run

---

net/bridge.go
prog/weaver/main.go
weave

Only block the specific port Weave Net is listening on.
Add a comment so users know what the rule is for.
Remove the rule added in v2.6.3 because it was too coarse.
Fixes #3810

Only drop traffic to the Weave Net port on 127.0.0.1

---

net/arp.go
net/bridge.go
net/veth.go

We are trying to turn off `accept_ra`, so if we get an error that the option doesn't exist we can just ignore it.
Fixes #3814

Don't exit if machine has no ipv6 installed

---

net/bridge.go
net/expose.go
net/ipset/ipset.go
net/iptables.go
npc/controller_test.go
npc/namespace.go
prog/weave-npc/main.go
prog/weaver/main.go
test/130_expose_2_test.sh
test/135_expose_iptables_refresh.sh

Adds a `CANARY` iptable chain and reloads all the weavenet iptable chains if the `CANARY` is removed by something (usually `firewalld`).
Partially addresses https://github.com/weaveworks/weave/issues/3586
- This exposes `ConfigureIPTables` and tries to make it safe to call again and again.
-  The destructive resets are pulled out into `ResetIPTables` and are called at launch so iptable state should remain mostly the same as prior to this PR.

Reload router iptables rules if they get cleared

---

prog/weave-kube/launch.sh

Hi weave-team,
I have found some code lines where the `-w` flag is missing for the `iptables` command.
What do you think about it?
It may could solve the issue: https://github.com/weaveworks/weave/issues/3828
The commands runs before the weave go application runs. Within the application all iptables commands are wrapped with the `go-iptables`-package which uses always the `--wait` flag internally

wait added to iptables commands

---

prog/weaver/Dockerfile.template

Use of `ethtool` was removed in #1958
`util-linux` was needed for `nsenter` which was removed in #3291 
I looked at removing `bind-tools` but we need that for `dig` used in `weave dns-lookup`.

Remove some unused tools from the Weave docker containers

---

plugin/net/watcher.go

Implements #3084 
When container in "our" network is started, we try to register only  
`<Config.Hostname>.<Config.Domainname>` DNS record.
When container in "our" network is started, we try to register:
- `<Config.Hostname>.<Config.Domainname>` (as before)
- `<Name>.<Configured_weave_domain>`, default weave domain is `weave.local.`
- all aliases from `<NetworkSettings.Networks.our_network.Aliases>`
Was forced to update `fsouza/go-dockerclient` submodule, because version (rather old: Feb 20) pinned in current master was unaware of network aliases. It was introduced on May 22 with [this](https://github.com/fsouza/go-dockerclient/commit/435a498ac62c62d69de89778bf367331ccd55dae) commit. Still decided to update to current latest version – not sure if it is OK.
Also I've noted that for …

Register container name and its network aliases with weaveDNS

---

nameserver/dns.go
nameserver/http.go
prog/weaver/main.go
site/tasks/weavedns/weavedns.md
test/225_dns_subdomain_test.sh
test/230_dns_unqualified_test.sh
test/280_with_or_without_dns_test.sh
test/config.sh
weave

Fixes #1770 
Also drive-by cleanup of `dns_args()` which was doing a lot of arg parsing needed for `weave run`, but not much use any more.
(Note if you were using `weave dns-args` with arguments like `-h` then that won't work now, but it was never documented to work)

 Fetch DNS listen address from daemon

---

prog/weaver/metrics.go
test/101_cross_hosts_2_test.sh
test/110_sleeve_encryption_2_test.sh
test/111_fastdp_encryption_2_test.sh
test/115_optional_encryption_2_test.sh
test/config.sh

Fixes #3788 
Notes:
- I don't have a good way of testing this out locally, but `make` succeeds, so that's encouraging...
- instead of limiting the `state` label's value to the values in `allConnectionStates`, the state will reflect whatever's in `conn.State` (which _may_ be out of sync with `allConnectionStates` some day? 🤷‍♂)
- I felt like maybe logging some sort of error message if the value of the `name` attribute was a non-string, but not sure if this is really necessary. Maybe removing the check and allowing a panic instead would be better somehow?
Signed-off-by: Dave Henderson <dhenderson@gmail.com>

Add new 'type' and 'encryption' labels to weave_connections metric

---

site/tasks/manage/metrics.md
site/troubleshooting.md

Weave Net monitoring can be setup using [kube-prometheus](https://github.com/coreos/kube-prometheus/pull/425).
This PR updates the Weave Net documentation for it.
Slack conversation: https://weave-community.slack.com/archives/C2ND76PAA/p1582724906028400
Weave Net kube prometheus PR: https://github.com/coreos/kube-prometheus/pull/425

Documentation Update for Weave Net Monitoring.

---

npc/controller.go
npc/controller_test.go
npc/namespace.go

Try to solve this issue #3836 .
The `*coreapi.Namespace` in struct `ns` may be set to `nil` in func [`deleteNamespace`](https://github.com/weaveworks/weave/blob/1ff09fd4d1c52bfa49222b724742f7b4bb80543a/npc/namespace.go#L538) before func [`deletePod`](https://github.com/weaveworks/weave/blob/1ff09fd4d1c52bfa49222b724742f7b4bb80543a/npc/namespace.go#L320) called，it will cause a pinic when `deletePod` use the namespace pointer.
I use a new map to store the lables of namespace, when the pointer is set to nil, it can avoid panic and work well. 
```
DEBU: 2020/07/23 11:09:37.920737 EVENT DeletePod {"metadata":{"creationTimestamp":"2020-07-23T08:30:24Z","deletionGracePeriodSeconds":0,"deletionTimestamp":"2020-07-23T11:09:31Z","generateName":"bp-s2-745c79479b-","labels":{"App":"f43f2b4120f7e4adbb8 …
```

Fix nil pointer panic in npc/namespace.go

---

prog/weave-kube/launch.sh
site/kubernetes/kube-addon.md
test/840_weave_kube_3_test.sh

Change NO_MASQ_LOCAL option to default ON

---

prog/weave-npc/main.go

This is #3792, rebased, squashed to remove back-steps, with a couple more commits to improve error reporting and remove an unnecessary variable.
Fixes #3764
Credit to @naemono
Work-around for https://github.com/kubernetes/client-go/issues/838 / https://github.com/kubernetes/kubernetes/issues/93641

Terminate NPC application if any of the watches panic

---

npc/controller.go
prog/weave-npc/main.go

Otherwise we might log a blocked connection even though the packet was not dropped.
Noticed while investigating #3829

Move egress logging rule beside drop rule

---

test/840_weave_kube_3_test.sh

There's no point stopping and starting the daemons now "no-masq-local" is the default.
Missed from #3756

Simplify Kubernetes externalTrafficPolicy:local test

---

prog/weave-kube/weave-daemonset-k8s-1.11.yaml
prog/weave-kube/weave-daemonset-k8s-1.6.yaml
prog/weave-kube/weave-daemonset-k8s-1.7.yaml
prog/weave-kube/weave-daemonset-k8s-1.8.yaml
prog/weave-kube/weave-daemonset-k8s-1.9.yaml
test/840_weave_kube_3_test.sh
test/860_weave_kube_portmap_3_test.sh

We shouldn't need this for the pod under Kubernetes, because the CNI plugin runs as root on the host.
Still need it for the regular Docker install, where the daemon attaches containers into namespaces.

For K8s, stop running in host PID namespace

---

site/tasks/weavedns/weavedns.md

Update documentation for #3090

add info about network aliases

---

net/ipset/ipset.go

There is an issue (#3847) with using both `iptables` in the `nft` mode and `ipset` on modern kernels (for example, the ones used by CentOS 8 or Ubuntu 20.04). If an ipset is being destroyed right after deleting a referencing rule then there is a good chance that the `ipset destroy` command will fail with a `"Set cannot be destroyed: it is in use by a kernel component"` error.
The more permanent solution would be retiring `ipset` and `iptables-nft` altogether, fully migrating to nftables and leveraging its native data types support instead of the IP sets.
This might be a lengthy process, so this PR offers a temporary solution until then: a second try after a 100ms pause that gets triggered if `ipset destroy` fails.

Pause and retry ipset deletion if it fails the first time

---

prog/weave-kube/init.sh

[Rebase of #3848 because the line affected has moved to a different file]
Sleep before ipset destroy in startup, otherwise the operation can sometimes fail - see https://github.com/weaveworks/weave/issues/3847

Workaround to fix ipset conflict with iptables

---

build/Dockerfile

Makes the images about 5% smaller (82.6MB -> 78.7MB)

Update Go to 1.15.6

---

prog/kube-utils/main.go
prog/weave-kube/launch.sh
prog/weaver/checkpoint.go

This reduces the size of the 'weaver' binary.
Also stops it crashing when run on 32-bit ARM.
Fixes #3842

Move Kubernetes API calls into kube-utils program

---

prog/weave-kube/weave-daemonset-k8s-1.11.yaml
prog/weave-kube/weave-daemonset-k8s-1.8.yaml
prog/weave-kube/weave-daemonset-k8s-1.9.yaml

Mounted as ReadOnly in order to minimize attack surface as in #3880
This fixes an issue I had running weave in a Kind cluster where `getOldStyleSystemUUID()` did not return any `uuid` as those files were not present inside the weave container. Because `/host/etc/machine-id` did not exist an attempt to read `/host/var/lib/dbus/machine-id` would be made but the host machine did not have a `/var/lib/dbus/machine-id` file. This would result in both `uuid` and `machineid` being "" and causing the container to exit. 
```
func getSystemUUID(hostRoot string) ([]byte, error) {
uuid, err := getOldStyleSystemUUID()
if err != nil && !os.IsNotExist(err) {
return nil, err
}
machineid, err := ioutil.ReadFile(hostRoot + "/etc/machine-id")
if os.IsNotExist(err) {
machineid, err = ioutil.ReadFile(hostRoot …
```

Update daemonset manifest to mount /etc/machine-id

---

site/kubernetes/kube-addon.md

closes: #3964 
documenting available options and adding how to encrypt traffic
tested via 
```yaml
containers:
- name: weave
command:
- /home/weave/launch.sh
env:
- name: INIT_CONTAINER
value: "true"
- name: WEAVE_PASSWORD
value: "wfvAwt7sj"
- name: EXTRA_ARGS
value: "--log-level=debug"
```
and logs shows traffic enctryped
```bash
✗ k logs -f weave-net-b9jk2 -n kube-system                                                                                <aws:sts>
Defaulted container "weave" out of: weave, weave-npc, weave-init (init)
DEBU: 2022/11/22 17:26:21.687729 [kube-peers] Checking peer "1a:04:b1:a3:35:b4" against list &{[]}
Peer not in list; removing persisted data
INFO: 2022/11/22 17:26:21.808174 Command line options: map[conn-limit:200 datapath:datapath db-prefix:/weavedb/weave-net …
```

Issues/3964 - added how to encrypt traffic
