site/features.md
weave

Elminate the need for `-passwordfile` and simplify the script a little

---

site/index.md
site/systemd.md

Installation note for systemd

---

Makefile
bin/release

and call it from the release script
Closes #331.

re-instate 'make publish'

---

nameserver/server.go
nameserver/server_test.go
test/210_dns_multicast_test.sh
test/300_fallback_dns_test.sh

(Incidental change: turn debug logging on during smoke tests.)

Use fallback nameserver for rdns

---

router/peers.go

log an error and close the connection, instead of blowing up

forgive all protocol decoding errors

---

router/routes.go

We already excluded such connections from unicast routing.
Fixes #452.

exclude non-established connections from broadcast routing

---

nameserver/http.go
weaver/main.go

[Gorilla mux](http://www.gorillatoolkit.org/pkg/mux) is an enhanced HTTP router for golang's http server, taking care of many routine tasks around HTTP method matching, URL parsing and dispatch. Mux is used by Docker's REST API implementation.

Replace hand parsing and validation of URLs with Gorilla mux

---

site/how-it-works.md

Add outbound and established flags to connection structure diagram

---

router/connection_maker.go
site/features.md
weave
weaver/main.go

Implement weave forget command

---

router/connection_maker.go
router/crypto.go
router/forwarder.go
router/json.go
router/peers.go
router/router.go
router/routes.go

Matthias seems to be in the mood for cleaning up the core router code.  While I enjoy nothing more than resolving the many rebase conflicts this creates for me, I feel I should push some obvious cleanups before Matthias gets to them.
More seriously: I haven't pushed these before because I'm reluctant to debate whether they are worthwhile when the best argument is simply to present them along with the more compelling work they lead to.  But on the other hand, I don't want to rebase them more often than necessary.  I think they look fairly obvious, but who knows.

Router cleanups

---

Makefile

Address comments from https://github.com/zettio/weave/pull/505 by @dpw

More feedback on test 'harness'

---

common/updater/updater.go
nameserver/zone.go
weavedns/main.go

This is so it can be re-used by IPAM

Generalise updater.go and move into its own package

---

docs/dockerless.txt

The IP address for VM1 is 192.168.122.2/24. 192.168.122.1/24 is virbr0.

Fix dockerless.txt

---

build/Dockerfile
build/build.sh
site/building.md

Docker needs golang 1.4.2 to build, so we do too

---

nameserver/http.go
weavedns/main.go
weaver/main.go

Similar to https://github.com/weaveworks/weave/commit/45740b1419508d442ec681893eb8f4c2aac93736

Simplify printing

---

weaver/main.go

When running multiple weaver daemons it is convenient for the HTTP
control interface to bind to a UNIX domain socket, to avoid the
need to allocate an additional unique port. This commit adds the
ability to specify
httpaddr="/path/to/socket"
on the command line.
Signed-off-by: Alex Bligh <alex@alex.org.uk>
Example of use:
$ weaver/weaver -name="00:11:22:33:44:55" -httpaddr="/tmp/weaversock"
then (`nc` which supports UNIX domain sockets required):
$ nc -U /tmp/weaversock
GET /status HTTP/1.1
HTTP/1.1 200 OK
Date: Fri, 10 Apr 2015 15:02:03 GMT
Content-Length: 301
Content-Type: text/plain; charset=utf-8
weave router git-c13980af4bd3
Encryption off
Our name is 00:11:22:33:44:55(nimrod-ubuntu)
Sniffing traffic on <nil>
MACs:
Peers:
Peer 00:11:22:33:44:55(nimrod-ubuntu) (v0) (UID …

Support using a unix domain socket for the HTTP control interface.

---

weave

Only check kernel version and ip command in local mode

---

.gitignore
Makefile
sigproxy/main.go
weave
weaveexec/Dockerfile

This is a rebase of #523 with the remaining review comments addressed.

Implement weaveexec signal proxy

---

router/local_peer.go
router/router.go
weaver/main.go

rather than copying the bulk of it

make the Router includer the RouterConfig

---

router/connection.go
router/crypto.go
router/local_peer.go
router/router.go

Closes #515.
I have filed #564 as a follow-up.

reduce crypto glitches and ignore crypto errors

---

test/100_cross_hosts_test.sh
test/110_encryption_test.sh
test/config.sh
test/run_all.sh

Fixes #591:
* Print overall status after running all tests
* Indicative script exit status
* Report ping failures through framework `assert`

Improved smoke test robustness

---

weave

guard against early container death in wait_for_status

---

README.md
weave

Require Linux kernel 3.8.0 or above

---

circle.yml
test/100_cross_hosts_test.sh
test/110_encryption_test.sh
test/130_expose_test.sh
test/200_dns_test.sh
test/210_dns_multicast_test.sh
test/220_dns_custom_test.sh
test/230_dns_unqualified_test.sh
test/240_dns_add_name_test.sh
test/400_weave_local_test.sh
test/500_weave_multi_cidr_test.sh
test/gce.sh
test/run_all.sh

- Small tidy up to gce.sh
- Using alpine linux image in tests (its smaller and quicker to fetch)
- Parallelise the integration tests
- Use circleci build number instead of git hash

More CircleCI Improvements

---

site/how-it-works.md

Makes the page a bit easier to navigate.

[docs] Add ToC to how-it-works docs page

---

test/100_cross_hosts_test.sh
test/110_encryption_test.sh
test/120_ipam_test.sh
test/130_expose_test.sh
test/140_ipam_expose_test.sh
test/200_dns_test.sh
test/210_dns_multicast_test.sh
test/220_dns_custom_test.sh
test/230_dns_unqualified_test.sh
test/240_dns_add_name_test.sh
test/250_dns_ipam_test.sh
test/300_fallback_dns_test.sh
test/500_weave_multi_cidr_test.sh
test/config.sh
test/sanity_check.sh

- remove lots of duplication
- improve consistency
- address some niggles

Refactor smoke tests

---

site/ipam.md

Give 'weave ps' example with IPAM and link to docs

---

test/400_weave_local_test.sh
weave

Fetch an address from IPAM for 'weave --local run'

---

test/130_expose_test.sh
weave

Silence complaints from http_call when at end of 'weave hide'

---

site/ipam.md

Expand documentation of 'weave launch' parameters for IPAM

---

site/ipam.md

Illustrate the usage of 'weave rmpeer'

---

ipam/allocator.go
ipam/ring/ring.go
site/ipam.md
site/troubleshooting.md

Also tidied up the output.  Addresses #692

Document ipam additions to `weave status`

---

weavewait/main.go

[proxy] use exec instead of run, to replace weavewait with subprocess

---

proxy/create_container_interceptor.go

refactor proxy entrypoint rewriting to match docker daemon

---

weave

Don't talk to IPAM unless 0 addresses supplied to 'hide'

---

site/features.md
site/proxy.md

Tried to make it clearer to someone coming to this completely fresh.
Also linked to Docker docs in case they haven't heard the specific terms used.

Reword weave proxy intro

---

router/gossip.go
router/protocol.go
router/router.go

Make gossip use channel names on the wire, not channel name hashes

---

router/connection_maker.go
test/150_connect_forget_test.sh
weave
weaver/main.go

A first step towards solving #656.
Are there some tests for this that should be updated?

weave connect/forget take multiple peers

---

proxy/create_container_interceptor.go
proxy/create_exec_interceptor.go
proxy/proxy.go
test/620_proxy_entrypoint_command_test.sh

Closes #744 
PRed into 0.11 branch this time.

Fix bug of --with-ipam not setting entrypoints

---

site/weavedns.md

add load balancing example

---

weavedns/main.go

This PR restores the `--fallback` argument in WeaveDNS, used for forcing a specific fallback server (instead of the one obtained from `/etc/resolv.conf`). This option is only used for testing/debugging.

Restore the "--fallback" argument in WeaveDNS

---

proxy/common.go
proxy/create_container_interceptor.go
proxy/proxy.go
test/620_proxy_entrypoint_command_test.sh

allow proxy to intercept unversioned (i.e. 1.0) urls

---

ipam/address/address.go
ipam/ring/ring.go
ipam/ring/ring_test.go

[ipam] fix panic when granting space from one peer to another

---

weave

add `weave stop_proxy`

---

net/if.go

in order to reduce container startup times
Closes #710.

reduce interface availability check interval

---

ipam/allocator_test.go
ipam/testutils_test.go

Removes  a couple of race conditions in the ipam unit tests found by `go test -race`.
Note that no adverse effects have been observed from this; just fixing them to make the unit tests closer to the way the code is used in production, and reduce noise when looking for a real race condition.

[ipam] Fix race conditions in unit tests

---

weave

simplifying and standardizing `launch-proxy`

---

ipam/http_test.go
nameserver/http.go
nameserver/http_test.go
weavedns/main.go

instead of random port, which can clash
Fixes #720.

use an automatically assigned port for http tests

---

router/connection_maker.go
site/features.md
test/150_connect_forget_test.sh
weave
weaver/main.go

add 'weave connect --replace ...'

---

nameserver/http.go
nameserver/mocks_test.go
nameserver/server_cache_test.go
nameserver/zone.go
nameserver/zone_lookup.go
nameserver/zone_test.go
test/240_dns_add_name_test.sh
test/250_dns_test_restart.sh
test/config.sh
weave

[dns] delete individual records

---

ipam/allocator_test.go

Introduce a flag 'block' to prevent an address from being freed during re-test.
Fixes #802

Fix race condition in allocator fuzz-test

---

weave

Add --no-trunc flag to docker ps for ipam_claim

---

weave

no timeout on wait for status

---

weave

kill container on network config error

---

docs/architecture.txt
router/connection_maker.go

fix connection retry delay calculation logic

---

site/boot2docker.md
site/building.md
site/features.md
site/how-it-works.md
site/index.md
site/proxy.md
site/systemd.md
site/troubleshooting.md
site/weavedns-design.md
site/weavedns.md

Also re-wording to make them match the page title.

Capitalizing and standardizing titles of pages in the docs.

---

site/features.md

recommend strong password

---

.gitignore
Makefile
prog/weaveproxy/main.go
proxy/proxy.go
proxy/tls.go
site/proxy.md
test/670_proxy_tls_test.sh
test/setup.sh
test/tls/generate_certs.go
weave

Accidentally merged and reverted #813. Continued work here...
Closes #506

Proxy TLS Support

---

nameserver/cache.go
nameserver/cache_test.go

Do not overwrite negLocal entries in the cache

---

weave

make `weave launch` args insensitive to order

---

site/_includes/header-navbaronly.html
site/_layouts/default.html

due to change in stylesheet in website repo
this change does not affect current deployment, but has to be deployed
when the website is deployed again

[site] header markup needs change after refactor

---

router/connection.go
router/protocol.go

simplify fragmentation test

---

router/gossip.go
router/gossip_test.go

Fix #885 more thoroughly, by looping across multiple routers until none of them have anything to say.

Keep flushing gossip until it's all gone

---

prog/weavedns/main.go
weave

DNS HTTP API listens on eth0 only

---

common/docker/client.go
ipam/http.go
ipam/http_test.go
nameserver/http.go
prog/weaver/main.go

Free allocated address if container is not running

---

router/crypto.go

Set high bit in TCP nonce to differentiate from UDP

---

nameserver/zone_lookup.go

Release lock before sending on a channel.
Fixes #923 and #924.

Fix deadlock in weavedns

---

nameserver/http.go
proxy/create_container_interceptor.go
test/270_use_name_as_hostname_test.sh
weave

Remove trailing dot from hostnames

---

prog/weaveproxy/main.go
proxy/create_container_interceptor.go
proxy/proxy.go
site/proxy.md
site/weavedns.md
test/240_dns_add_name_test.sh
test/280_with_or_without_dns_test.sh
test/630_proxy_dns_test.sh
weave

Weavedns default resolver

---

proxy/start_container_interceptor.go
weave

Kill the container we just started if we fail to allocate an IP address

---

nameserver/server_test.go

Ignore empty queries (sent when the server is being shut down)

---

prog/weaveproxy/main.go
proxy/create_container_interceptor.go
proxy/create_exec_interceptor.go
proxy/proxy.go
proxy/start_container_interceptor.go
site/proxy.md
test/600_proxy_docker_py_test.sh
test/620_proxy_entrypoint_command_test.sh
test/660_proxy_ipam_test.sh
weave

[proxy] --with-ipam -> --no-default-ipam

---

site/ipam.md

Trying to be helpful and accurate without overloading the reader.
Addesses #758.

Expand description of -initpeercount in docs

---

README.md
site/features.md

@rade @bboreham I'm not expecting this to be actually merged yet, I'm just using it to make changes available to you ASAP to get early feedback; I'll continue pushing self contained updates to other areas of the documentation + incorporate your feedback as you make it.
This PR updates just the main README initially - examples look much much better! Any advance on the rather boring h1c1/h2c1 container names? They're a bit mechanistic... something fun that we can carry through as a theme would be better IMO.
Fixes #869. Fixes #471. (eventually...)

Update documentation to leverage IPAM and DNS

---

README.md

As mentioned meet us at Dockercon will be removed on the 24th

README update to point at weave.works

---

README.md
site/features.md
site/how-it-works.md
site/index.md
site/ipam.md
site/proxy.md
site/weavedns.md

Update documentation to leverage proxy

---

site/features.md
site/ipam.md

'address allocation' is the feature covering both automatic and manual allocation.

improve IPAM doc integration

---

site/_includes/footer.html
site/_includes/header-navbaronly.html
site/_layouts/default.html
site/assets/custom.css

`style.css` needs to be included in this repo to untangle it from style changes made in the website repo.
Also needed, because website's custom.css is fingerprinted.
Using the opportunity to update header and footer include files.

Include stylesheet in repo, update footer

---

site/features.md
site/proxy.md
site/weavedns.md
test/150_connect_forget_test.sh
test/210_dns_multicast_test.sh
test/280_with_or_without_dns_test.sh
test/500_weave_multi_cidr_test.sh
test/620_proxy_entrypoint_command_test.sh
test/650_proxy_env_test.sh
test/660_proxy_ipam_test.sh
test/670_proxy_tls_test.sh
weave

Weave launch all the things

---

site/weavedns.md

Draw attention to --hostname precedence

---

prog/weaveproxy/main.go
router/crypto.go
router/ethernet_decoder.go
router/forwarder.go
router/pcap.go
router/udp_sender.go

Remove all the imports from "code.google.com"

---

net/if.go
prog/weavedns/Dockerfile
prog/weavedns/main.go
prog/weaver/Dockerfile
prog/weaver/main.go
prog/weavewait/main.go

Fixes #1023.
Is this an acceptable approach?

Wait forever for IPAM

---

ipam/ring/ring.go

Fixes #1004
I decided to do this closest to the place where I noticed that rand wasn't random.

Seed random-number generator from the host time

---

README.md

Remove weave proxy-(env|config) for just (env|config). Readme changes

---

prog/weaver/main.go

...instead if having a separate URL.
Also fix returned Content-Type.
Closes #1063.

output json status based on 'Accept' header

---

test/500_weave_multi_cidr_test.sh
test/config.sh

My impressive first pull request. I tried to make architecture independent changes, but can somebody test it in Linux before merging?

Fix integration tests for OSX

---

weave

...and not just `--dns-search=<arg>`
Fixes #1086.

detect `--dns-search <arg>`

---

net/route.go
prog/netcheck/netcheck.go
weave

Added --ignore-iface option to netcheck and use it to ignore weave bridge route
Fixes #1076

Don't complain about weave bridge routes clashing

---

router/peers.go

And call the callbacks outside of the peers lock.
This is broken out of #1065

Extend router/peers.go to allow multiple OnGC callbacks

---

.travis.yml
Makefile
build/build.sh
circle.yml
test/units.sh

Report coveralls.io from Circle.

Run unit tests in circle and include their coverage in the report.  

---

site/features.md
site/systemd.md
test/110_encryption_test.sh

Improvements to password handling recommendations

---

proxy/common.go
weave

[proxy] respect custom DOCKER_BRIDGE

---

Vagrantfile
vagrant-common.rb

update default vagrant box to ubuntu 15

---

proxy/create_exec_interceptor.go
test/610_proxy_wait_for_weave_test.sh

[proxy] should not attempt weavewait in on weave container's execs

---

proxy/create_container_interceptor.go
proxy/create_exec_interceptor.go
proxy/proxy.go
proxy/start_container_interceptor.go
test/660_proxy_ipam_test.sh

[proxy] do not weave attach containers in '--net=host|container:<name|id>'

---

circle.yml
test/210_dns_cross_hosts_test.sh
test/gce.sh

Also, make gce.sh less verbose, and do the env dance correctly.

Make 210_dns_cross_hosts_test.sh excercise gossip dns tombstones.

---

common/docker/client.go
ipam/allocator.go
nameserver/nameserver.go
nameserver/nameserver_test.go

Don't swallow errors in the docker client.

---

nameserver/entry.go
nameserver/http.go
nameserver/nameserver.go
nameserver/nameserver_test.go
net/address/address.go

Credit to @rade for finding this bug.
Fixes #1177

Don't periodically delete all non-tombstone entries.

---

proxy/proxy_intercept.go

Fixes #1182
Testing this behaviour involves either: allocating a pty for "docker run" and checking a timeout, or using a different client, so I'm not sure it's worth the time investment.

[proxy] Fully close TLS sockets, as they have no CloseWrite

---

proxy/create_container_interceptor.go
test/610_proxy_wait_for_weave_test.sh

[proxy] Mount weavewait readonly so it can't be tampered with

---

README.md

document how to run weave when docker access is root-only

---

test/units.sh

include directory of test code in coverage

---

testing/gossip/mocks.go

instead of abusing broadcast gossip, which has *much* worse complexity - with this change the nameserver tests, with race detection and coverage, take ~27s to run on my machine. Vs. ~10 minutes previously.
Fixes #1203.

proper mock periodic gossip

---

ipam/allocate.go
ipam/allocator.go
ipam/claim.go

Don't init the ring if the address is not in range.

---

weave

Enforce docker bridge address assignment type on launch

---

Makefile
prog/weaveproxy/main.go
prog/weaveproxy/main_test.go
test/690_proxy_autoconfig_test.sh
test/config.sh
weave

Add coverage to proxy for integration tests.

---

test/gce.sh

First part of fixing: https://github.com/weaveworks/scope/issues/334

parameterize test/gce.sh so scope can override TEMPLATE_NAME and NUM_HOSTS

---

prog/weaveproxy/main.go
proxy/create_container_interceptor.go
proxy/proxy.go
proxy/start_container_interceptor.go
router/crypto.go
test/610_proxy_wait_for_weave_test.sh

[proxy] only mount /w into weavewaited containers

---

site/weavedns.md

Add note to explain DNS shuffle effects.

---

prog/weavewait/main.go
proxy/create_container_interceptor.go
proxy/start_container_interceptor.go
test/610_proxy_wait_for_weave_test.sh
test/615_proxy_rewrite_hosts_test.sh
weave

Avoids problems when container user is non-root. Added a test for this
and the --no-rewrite-hosts flag.
Fixes #1252

[proxy] rewrite /etc/hosts from outside the container

---

weave

warn on -iprange overlap

---

nameserver/http.go
nameserver/nameserver.go

Remove DNS entries for dead containers when adding correctly.

---

proxy/proxy.go
test/610_proxy_wait_for_weave_test.sh

Docker 1.8 compatibility

---

proxy/proxy.go
test/660_proxy_ipam_2_test.sh

[proxy] attach containers with --net=none to weave

---

circle.yml

Add sudo apt-get update to circle.yml

---

weave

thus making them unaffected by docker breakages
Fixes #1322.

deal with `weave --help|help` locally

---

prog/weaveproxy/main.go
proxy/create_container_interceptor.go
proxy/proxy.go
site/proxy.md
test/680_proxy_hostname_derivation_test.sh
weave

This allows registering container hostnames based on a label provided when
creating the container.
Implements #1381

[proxy] Add --hostname-from-label

---

bin/release
docs/release-process.md

Automatically strip 'v' prefix for mainline and branch releases

---

test/README.md
test/gce.sh

New test image using docker 1.8

---

test/README.md
test/gce.sh
test/tls/generate_certs.go

https://github.com/docker/machine/pull/1729
Broke:
```
package github.com/weaveworks/weave/...
imports github.com/weaveworks/weave/common
imports github.com/weaveworks/weave/common/docker
imports github.com/weaveworks/weave/common/mflagext
imports github.com/docker/docker/pkg/mflag
imports github.com/docker/docker/pkg/homedir
imports github.com/weaveworks/weave/ipam
imports github.com/andybalholm/go-bit
imports github.com/google/gopacket
imports github.com/google/gopacket/layers
imports github.com/google/gopacket/pcap
imports github.com/gorilla/mux
imports github.com/gorilla/context
imports golang.org/x/crypto/nacl/box
imports github.com/weaveworks/weave/nameserver
imports github.com/weaveworks/weave/net
imports github.com/vishvananda/netlink
imports …
```

Update for docker/machine PR #1729

---

test/225_dns_subdomain_test.sh

Since there wasn't one.
Using ubuntu rather than alpine to get DNS search-paths to work.

Add smoke-test for subdomains

---

Makefile
circle.yml

This time rebuild without instrumentation first.
Fixes #1295

Publish latest images from CI on successful builds.

---

router/gossip_channel.go

In #1450 and #1475 we have an error from the Go runtime suggesting that a buffer grew beyond 128GB. This check will catch any infeasible gossip message being passed through the route seen on those stack traces, so we can narrow down the cause if it happens again.
Choice of limit here is arbitrary; it is not expected that an ordinary user of weave would see even 1MB gossip messages.

Sanity-check gossip messages

---

nameserver/dns_test.go

Fix races in TestRecursiveCompress

---

router/connection.go
router/overlay.go
router/protocol.go
router/sleeve.go

Restore sleeve compatibility with 1.1

---

router/connection.go
router/connection_maker.go
router/status.go

prevent ConnectionMaker.ConnectionTerminated race

---

nameserver/dns_test.go
nameserver/http.go
nameserver/nameserver.go
nameserver/nameserver_test.go
prog/weaver/main.go
weave

allow router exe to be run w/o access to Docker

---

circle.yml
test/gce.sh

Build GCE template on demand

---

ipam/allocator.go
ipam/allocator_test.go
ipam/http.go

When a container died before we got into the allocation code (inside the allocator run loop) we would not cancel the allocation since the container death event will have been processed by the allocator before it had any knowledge of the container.
The fix is to move the container-aliveness check inside the allocation code. That way we still detect the death even if the event has already flown past.
We only need to perform the check once, since any subsequent death will result in an event that is processed by the allocator when it has recorded the container in its state.
Fixes #1459.

don't stall in ipam on early container death

---

proxy/proxy.go

Fixes #1519 
Debating adding a test, as it's caught by the tests in #1518

[proxy] remove status.sock before binding status.sock

---

test/666_abuse_of_start_test.sh

Wait until container exits in test to remove race condition

---

weave

signal mismatches between WEAVE_NO_FASTDP and the bridge type

---

proxy/inspect_container_interceptor.go

Fixes #1523. Happy to add a test if necessary...

[proxy] only attempt to rewrite successful inspects

---

weave

And delete weave2 on stop-router.
Fixes #1548.

Don't fail in launch-router if weave2 already exists

---

weave

Add container FQDN to /etc/hosts

---

proxy/start_container_interceptor.go
test/666_abuse_of_start_test.sh

"There are more things in heaven and earth, `HostConfig`, than are dreamt of in your philosophy"
Fixes #1531 and #1532

Take more care over HostConfig on start request in proxy

---

test/666_abuse_of_start_test.sh

Reorder inspect template to work around docker/docker#17026

---

nameserver/http.go

Check weaveDNS subdomain on REST PUT

---

proxy/inspect_container_interceptor.go
proxy/inspect_exec_interceptor.go
proxy/proxy.go

Fixes #1549.  Replacement for #1573 to change branch.

Make inspect-rewrite wait for start

---

.gitignore
Makefile
prog/weaveexec/Dockerfile
prog/weavewait/check_network.go
prog/weavewait/main.go
prog/weavewait/noop.go
proxy/common.go
proxy/create_container_interceptor.go
proxy/proxy.go
proxy/start_container_interceptor.go
test/666_abuse_of_start_test.sh
test/config.sh

When container is started in host networkMode, we mount a noop weavewait

---

test/200_dns_test.sh
weave

Always add 'weave expose -h' argument to DNS

---

ipam/allocator.go
ipam/ring/ring.go
ipam/testutils_test.go
prog/weaver/main.go
test/165_reset_2_test.sh

Let IPAM pick any peer to transfer ownership to, on reset

---

weave

Fixes #1578
(continued from #1581)

Add an iptables rule for letting weaveDNS requests in

---

test/640_proxy_restart_reattaches_test.sh

Improves some symptoms discussed at #1588 and test hanging caused by #1556.  
Note this PR does not fix the root cause of either.

Improve proxy restart reattach test reliability

---

.gitignore
Makefile
circle.yml
site/building.md
test/190_no_fastdp_2_test.sh
test/gce.sh
test/setup.sh

Pending a resolution of https://github.com/docker/docker/issues/17823 we need to disable the code-coverage collection code.  Once that is fixed we should revert that commit.

Upgrade CI to Docker 1.9 and work round issues

---

site/features.md
weave

Implements part of weaveworks/docker-plugin#36.

Add plugin support to weave script

---

proxy/proxy.go
test/650_proxy_env_test.sh
test/690_proxy_autoconfig_test.sh
test/gce.sh
weave

Revert "Automatically symlink /var/run/*.sock sockets to /var/run/weave/*.sock"

---

mesh/connection.go

We need `Connection.Shutdown` to be non-blocked, and the way we achieved this is by spawning a goroutine. However, there can be a potentially unbounded number of `Connection.Shutdown` invocations. For example, if the TCP connection has gone bad then any `Connection.SendProtocolMsg` invocation will end up invoking `Connection.Shutdown`. There can be many such invocations until the `Connection` has been removed from the various data structures (e.g. `LocalPeer.connections` and `GossipSender.senders`). Hence we can end up with with an unbounded number of spawned goroutines.
To fix this, we introduce a one-element error channel on the connection. `Connection.Shutdown` does a non-blocking send on that, and the `Connection.actorLoop` reads from it and terminates.
This will throw away all but …

prevent unbounded number of goroutines for connection shutdown

---

nameserver/status.go
prog/weaver/http.go
site/weavedns.md

DNS upstream servers report

---

.gitignore
Makefile
plugin/dns.go
plugin/docker.go
plugin/driver.go
plugin/ipam.go
plugin/skel/listener.go
plugin/watcher.go
prog/plugin/Dockerfile
prog/plugin/main.go

Move Weave docker plugin into this repo

---

mesh/connection_maker.go

Set default port number on address before checking in `InitiateConnections`
Fixes #1714
Replacement for #1715, this time on 1.3 branch

Ensure `weave connect` attempts connection immediately

---

weave

Ensure /var/run/weave directory exists before telling Docker to use it

---

.gitignore
Makefile
prog/weaveexec/Dockerfile
prog/weaveproxy/main.go
prog/weavewait/check_network.go
prog/weavewait/check_network_iface.go
prog/weavewait/check_network_iface_mcast.go
prog/weavewait/noop.go
proxy/create_container_interceptor.go
proxy/proxy.go
proxy/start_container_interceptor.go
test/195_no_multicast_route_1_test.sh
weave

Option to disable multicast route

---

prog/weaver/http.go
site/troubleshooting.md

Add a 'json' function for 'weave report -f'

---

plugin/README.md
plugin/ipam/driver.go
plugin/net/driver.go
prog/plugin/main.go
site/features.md
site/plugin.md
site/troubleshooting.md
test/800_plugin_cross_hosts_2_test.sh
test/config.sh
weave

...so users don't need to set up a kv store
FIxes #1727

"mesh mode" plugin

---

router/fastdp.go

The kernel processes vport deletion asynchronously, meaning that we can sometimes fail to recreate vxlan vports on startup with an EADDRINUSE error. We compensate by retrying a small number of times with a short sleep on encountering this error, failing as before on a different error or exhaustion of retries.
Example log output:
```
[root@localhost ~]# weave stop-router; weave launch-router
b8a4b98fd2ed7270669c053063a14c45b429b2677a24414abcd4061daae2586a
[root@localhost ~]# docker logs weave
INFO: 2015/12/16 11:45:10.868200 Command line options: map[dns-effective-listen-address:172.17.0.1 dns-listen-address:172.17.0.1:53 http-addr:127.0.0.1:6784 ipalloc-range:10.32.0.0/12 nickname:localhost.localdomain docker-api:unix:///var/run/docker.sock datapath:datapath name:e2:33:24:21:e6:2c …
```

Introduce limited retry on vxlan vport creation

---

plugin/net/driver.go
prog/plugin/main.go
site/plugin.md
test/195_no_multicast_route_1_test.sh
weave

In the plugin, set up static route for multicast

---

prog/weaveproxy/main.go
proxy/proxy.go
test/630_proxy_dns_test.sh
weave

Fixes #1754 
Doc change is in 1d9ef76 on latest_release_doc_updates

Remove --with-dns option from proxy

---

site/plugin.md

Improve the look and add some notes about multiple networks.

Extend plugin docs

---

weave

I was confused for a while because the `else` lines up with the wrong `if`.
I checked the rest of the script and don't see anything else with the same problem.

Fix indentation of weave script

---

weave

...just as we don't launch anything if either the router or proxy are running.
Fixes #1818.

don't launch anything when plugin is running

---

weave

Show plugin version

---

weave

Fixes #1778 
Replacement for #1791 against 1.4 branch

Handle weave containers in 'restarting' state

---

weave

Check we have Docker 1.9 or newer before trying to remove a network

---

Makefile

Fixes #1723 
I think this is all that is required, but haven't re-done an entire release process to check.

Add the plugin to the list of images to tag and push

---

docs/release-process.md

Add more steps to the release process

---

mesh/routes.go

See commit message for explanation.
Fixes #1761.

lazy route calculation

---

site/troubleshooting.md

Update 'reboots' info

---

mesh/gossip.go
mesh/gossip_channel.go

clean up GossipSender

---

mesh/gossip.go
mesh/gossip_channel.go

don't stall gossip broadcasting when there are blocked connections

---

test/gce.sh

Stop masking failures in gce hosts destroy

---

mesh/connection.go
mesh/gossip.go
mesh/gossip_channel.go
mesh/gossip_test.go

get rid of GossipSender gc

---

ipam/http_test.go

There was a race between `CancelRequest` and `unpause`, so I rewrote the test to block waiting for consensus rather than using `pause`.
It seems this test is currently little more than a test of the `http` library's ability to cancel a request; perhaps we should do more, e.g. check whether `Allocator` has the request pending after it is cancelled.

Fix race condition in ipam TestHTTPCancel

---

net/if.go

Fix race condition in weavewait

---

site/features.md
site/ip-addresses.md
site/ipam.md

To provide some more explanation and guidance for people who are not familiar with the terminology.
Inspired by #1871

Documentation on IP addresses, routes and networks

---

weave

Fixes #1869, in a simpler way than #1885.

Allow plugin to keep running on 'weave launch'

---

Makefile
circle.yml

See individual commits for details

Improve build times on CircleCI

---

site/ipam.md
weave

Derive peer name from product_uuid

---

proxy/inspect_exec_interceptor.go
weave

Fix unexpected EOF with Docker 1.10-rc1 and proxy --rewrite-inspect

---

weave

Warn, don't error, if unable to remove network in 'weave stop'

---

site/plugin.md

Mitigation for https://github.com/docker/libnetwork/issues/813

Suggest disabling systemd timeout if using Weave Net plugin

---

vendor/README.md

Will follow up with an issue to automate update + prune.

Document vendored dependency management commands

---

plugin/net/driver.go

Reverts weaveworks/weave#1808; there is some uncertainty about when Docker may call `Delete` and `Leave`, and their implementation appears to do it differently.

Revert "Refactor plugin to create veths in CreateEndpoint"

---

router/sleeve.go
test/105_frag_2_test.sh

Negative fragment fix

---

api/ipam.go
ipam/claim.go
plugin/ipam/driver.go
plugin/skel/listener.go

Support requesting a specific IP from the plugin

---

weave

Don't rm old containers, in case we want the log

---

weave

Check if container is running before using its image to ask for version

---

net/listen.go
prog/plugin/main.go
proxy/proxy.go
weave

Fixes #1873
Also improves behaviour in the case that the user has set a restart policy on weaver or weaveproxy, and then encountered a problem.
Replacement for #1879, now on master branch

Improve visibility of startup problems

---

prog/weaveproxy/main.go
proxy/common.go
proxy/proxy.go

Builds on #1944; partially addresses #1940.

Use netlink instead of shelling out to `weave docker-bridge-ip`

---

prog/weaveutil/addrs.go
prog/weaveutil/docker_tls_args.go
prog/weaveutil/main.go
test/140_weave_local_test.sh
weave

Make weaveutil container-addrs observe $PROCFS

---

common/docker/client.go
proxy/proxy.go

treat 'restarting' as 'not running'

---

test/175_stop_start_test.sh
weave

Fixes #1859
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/weaveworks/weave/1967)

Start existing container, if its image and arguments match

---

prog/weaver/main.go
router/http.go
router/network_router.go
test/162_persist_ipam_2_test.sh

Building on #1971 
We had some discussion about whether it's a good idea to overwrite the command-line parameters with the last saved data.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/weaveworks/weave/1972)

Persist set of peers to connect to

---

common/utils.go
prog/weaveproxy/main.go
prog/weaveutil/addrs.go
prog/weaveutil/docker_tls_args.go
prog/weaveutil/main.go
proxy/common.go
proxy/proxy.go
weave

Fixes #578.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/weaveworks/weave/1982)

Use --pid=host

---

common/docker/client.go
ipam/allocator.go
prog/weaver/main.go
test/163_docker_restart_test.sh

New take on #1945, following on from #1971 
Here we are serializing the entire set every time it changes, which is overkill, but we don't expect the set to have more than 1,000 entries on one host and we don't expect it to change more than ~10 times per second.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/weaveworks/weave/1973)

Persist 'owned' addresses in IPAM

---

ipam/allocator.go
ipam/consense.go
ipam/http.go
site/ipam/overview-init-ipam.md
weave

Implement `weave consense`

---

common/docker/client.go

Retry docker event subscription

---

api/ipam.go
plugin/ipam/driver.go
test/820_plugin_subnet_test.sh

Fixes #2046; also adds smoke-test to catch if it gets broken in future

Fix plugin accepting --ip address

---

common/utils.go
prog/weaveutil/addrs.go
weave

Protect container-addrs util_op against stopped containers

---

ipam/allocator.go
ipam/allocator_test.go
ipam/ring/entry.go
ipam/ring/ring.go
ipam/ring/ring_test.go
ipam/space/space.go
ipam/space/space_test.go
ipam/testutils_test.go
net/address/address.go

To address https://github.com/weaveworks/weave/pull/2066#discussion_r56691677

Add address.Count type

---

ipam/allocator.go
ipam/allocator_test.go
ipam/http.go
ipam/ring/ring.go
ipam/space/space.go
ipam/space/space_test.go
site/ipam/stop-remove-peers-ipam.md

make 'rmpeer' report on size of transferred range, and not fail

---

ipam/allocator_test.go
ipam/testutils_test.go

Avoid data race in TestSpaceRequest

---

db/boltdb.go
ipam/allocator.go
ipam/testutils_test.go
prog/weaver/main.go
router/network_router.go
site/ipam/overview-init-ipam.md
test/380_ipam_seed_2_test.sh
weave

Allow specification of initial IPAM ring via --ipam-seed

---

test/335_rmpeer_3_test.sh

also gives us some coverage of `weave consense`

add 'rmpeer' test

---

site/ipam.md
site/troubleshooting.md

Correct IPAM state docs

---

circle.yml

collect coverage data from ci nodes before teardown

---

prog/weaver/main.go

extract IPAM config
and
- fix error handling - the "do we have an --ipalloc-range?" check was not performed in all required cases
- add a check for "--ipalloc-default-subnet requires --ipalloc-range"

Reify ipam config

---

build/Dockerfile
docs/fastdp.md
docs/weavedns-design.md
ipam/allocator.go
site/ip-addresses/configuring-weave.md
site/ipam/overview-init-ipam.md
site/troubleshooting.md
site/weave-docker-api/set-up-proxy.md
site/weavedns-design.md

Update tools to get misspell integration

---

plugin/ipam/driver.go
plugin/net/cni.go
plugin/net/driver.go
plugin/net/watcher.go

consistency, consistency, consistency
and elimination of dot imports.

clean up plugin logging

---

common/docker/client.go

...until the container has a pid, or we see the same container die.
This is to work around https://github.com/docker/docker/issues/18574
Fixes #2090. Partially addresses #1775.

Delay notifying observers about 'start' events

---

site/troubleshooting.md

Update reboot docs

---

ipam/allocator.go
ipam/paxos/participant.go
ipam/paxos/paxos.go
ipam/status.go
prog/weaver/http.go
site/ipam/troubleshooting-ipam.md

Better log and status messages for Paxos observer

---

ipam/allocator.go
ipam/allocator_test.go
ipam/testutils_test.go

Discovered while investigating #2139.

stop ipam tests from leaking routers

---

test/270_use_name_as_hostname_test.sh
weave

Remove trailing dot from FQDN

---

plugin/ipam/cni.go
test/830_cni_plugin_test.sh
weave

Bind-mount the docker socket for CNI plugin

---

testing/gossip/mocks.go

Lock round TestRouter map accesses

---

ipam/allocator.go
ipam/http.go
ipam/prime.go
prog/weaver/main.go
site/ipam.md
test/335_rmpeer_3_test.sh
test/340_observers_cannot_vote_3_test.sh
test/350_observers_can_call_election_3_test.sh
test/380_ipam_seed_2_test.sh
test/510_detach_hide_no_ipalloc.sh
weave

Fixes #2065.
This is all the implementation stuff, just working on the docs now. Comments welcome!

Rationalise IPAM concepts

---

test/090_docker_restart_policy_2_test.sh
weave

All variants of `weave launch` observe `--no-restart` to disable Docker restart policy.

Optional restart policy

---

weave

Add iptables rule excluding multicast from NAT on 'weave expose'

---

test/100_cross_hosts_2_test.sh
weave

2123: Use ContainerID when restarting a container

---

ipam/allocator.go
ipam/allocator_test.go
ipam/ring/ring.go
ipam/ring/ring_test.go

prevent excessive ring fragmentation due to repeated space requests

---

.gitmodules
prog/weaver/main.go

Upgrade all the things!
(Except Go.  Wishing to avoid the issue Docker hit where it rejects old Docker clients)
Each library was upgraded to the latest release, the latest commit, or some other appropriate commit.
See commit message for details on which versions were selected.

Upgrade vendored libs

---

circle.yml

So that I can push changes to wordepress master without breaking doc publishing.

Pin wordepress version used to publish site

---

common/http.go
prog/weaver/main.go

2034: Add LogHandler for logging REST API calls at server side

---

site/using-weave/fastdp.md

Add a section explaining WEAVE_MTU for fastdp

---

circle.yml

Please update github.com/weaveworks/weave/wiki/WorkingOnWeave on merge.

Publish doc previews for all branches, not just those named issues/*

---

plugin/README.md

Plugin README links refer to latest release docs

---

site/faq.md
site/using-weave/host-network-integration.md

Document adding a route on non-Weave hosts

---

site/weave-docker-api/using-proxy.md
weave

Also a couple of other options on the proxy that were not clearly documented.
CC @abuehrle 
Fixes #2245

Document --log-level

---

README.md

remove duplicate content in README

---

common/utils.go
prog/weaveutil/addrs.go
weave

Fixes #2194 as per @rade's suggestion.

Reclaim plugin addresses without warning

---

site/ipam.md

Doc preview will be available at https://dev-weavewww.pantheonsite.io/docs/net/2233-peer-name-docs/ipam/ once the CI build is complete.
CC @abuehrle 
Fixes #2233.

Document peer name

---

proxy/proxy.go
test/640_proxy_restart_reattaches_test.sh
weave

Fixes #2123 
I shall try to add a smoke-test.

Kill process instead of container, on container restart. 

---

site/ipam/troubleshooting-ipam.md

Doc preview available at
https://dev-weavewww.pantheonsite.io/docs/net/1876-weave-status-ipam-docs/ipam/troubleshooting-ipam/ once CI build finishes.
Fixes #1876.

Document `weave status ipam`

---

test/140_weave_local_test.sh
test/310_docker_restart_test.sh
test/320_claim_3_test.sh
test/640_proxy_restart_reattaches_test.sh
test/config.sh

This PR:
* Extracts and moves `wait_for_proxy` to _config.sh_.
* Introduces `wait_for_attached`.

Refactor wait_for_{proxy,attached}

---

proxy/proxy_intercept.go

Flush chunked response header immediately

---

circle.yml

...due to undiagnosed dev-weavewww issues

Temporarily disable doc previews

---

plugin/ipam/driver.go

Fixes #2300
Watch out for Docker releasing the fake gateway address we create when
the network is set up, and don't pass it on to Weave IPAM.

Don't release fake gateway address in plugin

---

plugin/net/driver.go
prog/plugin/main.go
prog/weaveutil/plugin_network.go
site/plugin.md
site/plugin/plugin-how-it-works.md
test/195_no_multicast_route_1_test.sh

This gives users a better way out of the problem in #1960

Add an option to disable multicast route per-network

---

ipam/allocator.go
ipam/ring/ring.go

Fix ring persistence after free space update

---

prog/weaver/main.go
weave

Make it easier for the user to see what is wrong.

Report a couple of options that are incompatible with --awsvpc

---

site/plugin.md

Describe creating multiple networks using the plugin

---

site/faq.md
site/features.md
site/ipam/allocation-multi-ipam.md
site/plugin.md
site/using-weave.md
site/using-weave/application-isolation.md
site/using-weave/dynamically-attach-containers.md
site/using-weave/manual-ip-address.md
site/weave-docker-api/automatic-discovery-proxy.md
site/weave-docker-api/ipam-proxy.md
site/weave-docker-api/launching-without-proxy.md
site/weave-docker-api/using-proxy.md
site/weavedns.md
site/weavedns/load-balance-fault-weavedns.md
site/weavedns/managing-domains-weavedns.md
site/weavedns/managing-entries-weavedns.md

Fixes #2290, except we still need to re-record the video
Dockerfile for the new image is at https://github.com/weaveworks/guides/pull/184
Ping @abuehrle for review of doc changes (should just the the FAQ entry as everything else is just a command parameter)

Use our own ubuntu image

---

nameserver/dns.go
nameserver/dns_test.go
nameserver/status.go
prog/weaver/main.go
weave

Observe resolv.conf changes

---

prog/weaveutil/docker_tls_args.go
proxy/proxy_intercept.go

Fixes #2379
Replacement for #2380 on 1.5 branch

Fix Docker 1.12 incompatibilities

---

site/using-weave.md
weave

and add some broader points about access control early on, since some users will wonder about that right from the start.
Fixes #2347

document --host

---

site/using-weave/security-untrusted-networks.md

improve --trusted-subnets docs

---

site/weavedns/how-works-weavedns.md
site/weavedns/load-balance-fault-weavedns.md

and move it to a more prominent location
Fixes #1710

correct RFC3484 address selection caveat

---

plugin/net/cni.go
site/cni-plugin.md

highlight the need for `weave expose` in CNI/k8s

---

router/fastdp.go

Fixes #1852.
Added log lines for packets that we will broadcast;
Added log lines for flows we don't know how to handle;
Moved the line for when we expect to insert a flow down to the miss-handler;
Packets handled by the bridge already have their own logging via `--pktdebug`

Move 'ODP miss' log from every miss to specific places

---

weave

Recent(ish) changes placed functions in the wrong sections. Fix that and label the sections more clearly.

refactor: restore grouping of functions in script

---

net/veth.go

Provide multicast isolation with in-container-netns iptables rules

---

site/cni-plugin.md

- Add Mesos CNI instructions
- Rename page to something more generic.
- Fix old links.
- Minor editing.
Review: @abuehrle 
cc: @bboreham, @pidster

Refactor CNI documentation.

---

router/fastdp.go

Check if a vxlan vport netdev is UP after its creation

---

site/features.md
site/plugin/plugin-how-it-works.md
site/weave-docker-api.md
site/weavedns.md

Added note to proxy about using the net flag, and what it does. 
Maybe add a link to this from the plugin section as well.

added note about net flag

---

weave

Fixes #2434
Fixes #2394
Fixes #2435

CNI setup fixes

---

common/mflagext/listvar.go

Needed for https://github.com/weaveworks/build-tools/issues/38
This is a temporary workaround to get our builds going, we still need a long term solution for this, tracked with #2490

Use mflag package from weaveworks fork until we find a better solution

---

circle.yml
test/600_proxy_docker_py.sh

The 14.04 VM includes go1.6 which uses `vendor/`.

Switch CircleCI build VM to 14.04

---

net/ethtool.go

On Google container-vm ("gci") machines, tx offload is unsupported and attempting to turn it off results in an error.  This PR fetches the current setting so we can avoid the error.

Check current tx value before trying to set it

---

common/utils.go

Filter out netns of non-existing containers

---

test/830_cni_plugin_test.sh

Enable unsolicited ARPs in 830 test suite

---

prog/weaver/main.go
router/network_router.go

Create restart.sentinel after storing the peer list

---

common/utils.go
net/netns.go
plugin/net/watcher.go
prog/weaveutil/main.go
prog/weaveutil/netdev.go

Fixes #2540 
This was created from a subset of #2475, extracted to make it safer to release as a patch, and I have retained the author on the commits herein.

Change namespace via nsenter, for plugin arp-config step

---

.gitignore
Makefile
prog/plugin/Dockerfile.template

Ensure Dockerfiles obey DOCKERHUB_USER

---

prog/weaver/metrics.go

Do not expose IPAM or DNS metrics if weave does not run IPAM or DNS

---

prog/weave-kube/launch.sh
weave

Serve metrics by default, on port 6782

---

prog/weaver/http.go
prog/weaver/metrics.go

Improve metric naming

---

.gitignore
.gitmodules
Makefile
docs/weavenpc-design.md
npc/analyser.go
npc/betatypes.go
npc/constants.go
npc/controller.go
npc/ipset/ipset.go
npc/metrics/metrics.go
npc/namespace.go
npc/rule.go
npc/selector.go
npc/shortname.go
npc/ulogd/ulogd.go
prog/kube-peers/main.go
prog/weave-npc/Dockerfile
prog/weave-npc/main.go
prog/weave-npc/ulogd.conf

Addresses most of weaveworks/weave-npc#16

Merge weave npc

---

prog/weave-npc/main.go

Change default NPC metrics port

---

site/cni-plugin.md
site/features.md
site/kube-addon.md
site/metrics.md

Fixes weaveworks/weave-kube#30, fixes weaveworks/weave-kube#43, fixes weaveworks/weave-npc#17.

Document k8s addon & prometheus metrics

---

api/ipam.go
ipam/allocate.go
ipam/claim.go
plugin/ipam/driver.go
test/830_cni_plugin_test.sh

Fix reclaim after using CNI

---

Vagrantfile

Include jq in the build VM

---

test/700_status_and_report_test.sh

Remove a race where we assert state before the router has actually run the check.

Wait up to 30s for version check error in logs

---

site/kube-addon.md

Attempt to fix the formatting of [kube-addon](https://dev-weavewww.pantheonsite.io/docs/net/fix-doc-formatting/kube-addon/)

Fix documentation's formatting.

---

test/gce.sh

and open up a rule from the specific IP running the tests
I created the `test` network by hand in the console; it has the following rules by default:
````
Name                  Source tag/IP    Allowed protocols/ports
test-allow-icmp       0.0.0.0/0        icmp
test-allow-internal   10.128.0.0/9     tcp:0-65535,udp:0-65535,icmp
test-allow-ssh        0.0.0.0/0        tcp:22
test-allow-weave      test             tcp:6783,udp:6783,udp:6784
````
and this PR adds specific rules for each test runner to open the Docker ports.
After this is merged we should be able to close down the `default` network rules.
Fixes #2667

Run GCE test VMs on a locked-down network

---

prog/weave-kube/launch.sh

Optional bridge-nf detection

---

prog/plugin/main.go

Remove CNI support from Docker plugin

---

net/veth.go

in case they get  "temporarily unavailable" exit status

Run iptables commands in a loop

---

npc/controller.go
npc/json.go
npc/namespace.go
npc/rule.go
npc/selector.go
prog/weave-npc/main.go

Log objects via JSON for better debugging

---

npc/metrics/metrics.go
npc/ulogd/ulogd.go
prog/weave-npc/main.go

Fixes #2692 
This was missed from #2666

Change rest of npc to weave common logging

---

test/sanity_check.sh

Previously checking local weave version.
Now checking test host's weave version.

Fixed typo in sanity check of weave's version

---

site/how-it-works/ip-addresses.md
site/ipam.md

Docs: improve IP route links

---

npc/namespace.go

fix a bug of updating network policy

---

net/bridge.go
plugin/net/cni.go
prog/weaveutil/addrs.go
prog/weaveutil/main.go
proxy/proxy.go
weave

and log the one we end up using
Also refactored three similar pieces of code into one.
Fixes #2580

Allow docker bridge to have more than one IP address

---

site/kube-addon.md

Warn not to delete all Weave Net pods

---

site/kube-addon.md

Fixes #2693 
cc @abuehrle for docs review

Fix instructions to view npc logs when >1 pod exists

---

prog/weave-npc/Dockerfile
prog/weaveexec/Dockerfile

Pin alpine container version

---

.gitmodules
Makefile
bin/circle-dependencies-post
bin/circle-test-pre

Subset of #2337 which should be of general usefulness; also something similar to the `testrunner` changes seems to be needed for the ARM port

Build improvements

---

test/830_cni_plugin_test.sh
test/config.sh
weave

Allow traffic to forward off the weave bridge

---

prog/weave-npc/main.go

Handle cache.DeleteFinalStateUnknown

---

docs/ipam.md

- Added section about persistence.
- Updated section about claiming an address.

Update IPAM documentation.

---

docs/fastdp-crypto.md
docs/fastdp.md
site/faq.md
site/features.md
site/how-it-works/encryption-implementation.md
site/how-it-works/encryption.md
site/installing-weave.md
site/introducing-weave.md
site/kube-addon.md
site/using-weave/awsvpc.md
site/using-weave/fastdp.md
site/using-weave/security-untrusted-networks.md

Add fastdp-crypto docs

---

README.md

@bboreham  updated the readme to include new slack community channel and how to join it,  and also a link to the Weave User Group.

update slack community and weave user group details

---

common/docker/client.go
prog/weaver/main.go
prog/weaver/reclaim.go

Only check running containers for existing addresses

---

prog/weaver/main.go

'redacted' is a better word than 'elided'

Change what we print in place of the password

---

prog/weave-kube/launch.sh
test/840_weave_kube_3_test.sh

Fixes #2836. 
Maybe more a workaround than a real fix? (see #2844).
However it seems to do the job -- see below manual testing.

Remove exec from weaver command

---

npc/constants.go
npc/ipset/ipset.go
npc/selector.go
prog/weave-npc/main.go
test/840_weave_kube_3_test.sh

Destroy ipsets prefixed `weave-` only

---

test/840_weave_kube_3_test.sh

Remove hard-coded number of hosts in kube test 840

---

weave

This just makes it easier to track down where we are really using this setting

Remove some unnecessary --privileged flags

---

plugin/net/cni.go
test/830_cni_plugin_test.sh
test/config.sh

Fixes #2839 
Plus a couple of improvements encountered when testing.

Ensure we don't send containerID to IPAM plugin when requesting bridge IP

---

site/kube-addon.md

Fixes formatting of: https://dev-weavewww.pantheonsite.io/docs/net/weave-kube-1.6-docs/kube-addon/

Fix formatting of code snippets in site/kube-addon.md.

---

ipam/allocator.go

because otherwise the pending ops can be modified from inside Try()
Fixes #2892

IPAM: Make sure we have a ring before calling tryOps()

---

plugin/skel/listener.go

Fix typo: 'JSON encode payload' -> 'JSON encoded'.

---

prog/weaver/main.go
router/fastdp.go

Improve hairpin log messages

---

code-of-conduct.md

Add code-of-conduct.md pointing to CNCF CoC

---

site/kube-addon.md

Explaining the issue described at #2794

Add pod resources and eviction to weave-kube doc

---

site/cni-plugin.md
site/operational-guide/tasks.md
site/plugin.md
site/weavedns/load-balance-fault-weavedns.md
site/weavedns/managing-entries-weavedns.md

These came up while testing the website.

Fix some broken links in documentation

---

prog/weave-npc/main.go

Flush weave ipsets before destroying

---

weave

Just a few things that don't need special handling any more.

Clean up some argument parsing in weave script

---

Makefile

As for some reasons Docker Store does not allow us to use :latest.

Use :latest_release tag for net-plugin

---

site/weave-docker-api.md
site/weave-docker-api/automatic-discovery-proxy.md
site/weave-docker-api/ipam-proxy.md
site/weave-docker-api/name-resolution-proxy.md
site/weave-docker-api/securing-proxy.md
site/weave-docker-api/using-proxy.md
site/weavedns.md

Related to #1642, and following #2936.
Note that I've also deleted trailing whitespaces for the files I have modified.
This is done as a separate commit for ease of review, but should be squashed before merging.

Update docs following merge of proxy & router

---

site/building.md
site/features.md
site/ipam.md
site/plugin-v2.md
site/plugin.md
site/plugin/plugin-how-it-works.md
site/troubleshooting.md
site/using-weave.md
site/using-weave/weave-cloud.md
site/weave-docker-api.md

Fixes #2396, the last outstanding part

Add plugin-v2 (net-plugin) docs

---

site/plugin-v2.md

Fixed network create command statement ordering.

Fix Network Commands

---

.github/ISSUE_TEMPLATE.md

Should hopefully help triage users and diagnose bugs in more effective ways.
**Edit**:
Original sample output: https://gist.github.com/marccarre/094e1b09c9205048dd94c158f475b7e7
Current sample output below.

Template for GitHub issues

---

docs/entrypoints.md

As requested by @bboreham. This is _known_ to be incomplete (and probably partially wrong too). But at least if it is documented, someone won't have to reverse engineer all the starting points to figure out how to add a new option like I did. :-)

First revision of how weave utils get launches

---

ipam/allocator_test.go
ipam/claim.go

Fix use of '_' as container ID in claim outside range

---

prog/weave-kube/weave-daemonset-k8s-1.6.yaml

Currently weave doesn't run on nodes with tolerations except the master
The suggested code change it to run on all nodes

modify tolerations to match any node

---

README.md
weave

Adds a message to `weave` script and updates the README to make it a bit more sane.

Update references to Weave Cloud

---

prog/weave-kube/weave-daemonset-k8s-1.6.yaml
prog/weave-kube/weave-daemonset.yaml

See also:
- https://github.com/weaveworks/launch-generator/issues/133
- https://github.com/weaveworks/launch-generator/pull/134
Command used:
```
$ curl -fsSo prog/weave-kube/weave-daemonset-k8s-1.6.yaml "http://localhost:8080/k8s/v1.6/net?v=latest"
$ curl -fsSo prog/weave-kube/weave-daemonset.yaml "http://localhost:8080/k8s/v1.5/net?v=latest"
```
Annotations then removed.

Update YAMLs to be what the Launch Generator serves.

---

prog/weave-kube/weave-daemonset-k8s-1.6.yaml
prog/weave-kube/weave-daemonset.yaml

Add back HOSTNAME env var for weave-npc container

---

prog/weavedb/Dockerfile

label weavedb image

---

prog/weaver/main.go

If DNS server is off then disable proxy DNS registration

---

prog/weaver/main.go

Supply the weave port number to bridgeConfig

---

test/840_weave_kube_3_test.sh

Per issue #3095 this crashes the commenting code.
Also added check to see if the pods are still running.

Extend weave-kube smoke test: add a policy with blank 'from'

---

npc/ipset/ipset.go

During initialisation try and create an ipset with the comment extension
If this fails, disable comment support
Fixes #3098

fix: Test for ipset comment support

---

weave

Remove db file for v2 plugin

---

site/install/plugin/plugin-v2.md
site/troubleshooting.md

Add instructions on troubleshooting the V2 plugin

---

site/concepts/ip-addresses.md

The page renders quite strangely

Escape a minus that is being interpreted as a bullet

---

Makefile
build/Dockerfile
build/shasums/qemu-ppc64le-static.sha256sum

This PR is for supporting weave networking for ppc64le platform.

Add ppc64le support

---

.gitmodules
npc/analyser.go
npc/controller.go
npc/controller_test.go
npc/namespace.go
npc/rule.go
npc/selector.go
prog/kube-peers/main.go
prog/weave-npc/main.go

I ran:
`go build -o weave-npc -a github.com/weaveworks/weave/prog/weave-npc`
and
`make tests`
to confirm this change doesn't break things, please advice if there other things I need to do. I also chose HEAD of origin/master on all the dependencies as at the time I did pull them.

Upgrading client go and vendoring it's extra dependencies.

---

site/install/plugin/plugin-how-it-works.md
site/install/plugin/plugin-v2.md

Since the latter is hard to update and hence frequently out of date.
Fixes #3153.

document using v2 plugin from dockerhub rather than store

---

site/kubernetes/kube-addon.md

Triggered by #3127 
I typed it in a bit of a hurry; am sure the English can be improved

Added 'things to watch out for' section in Kubernetes instructions

---

test/README.md

Minor doc addition for test-runner idiosyncrasy.

Document test runner feature to pick number of hosts

---

npc/controller_test.go
test/840_weave_kube_3_test.sh

- Add a test case for default allow all ingress traffic.
- Fix misleading comment.
- Fix a typo in another comment.

Extend NetworkPolicy smoke tests

---

prog/kube-peers/main.go
prog/weave-kube/launch.sh
prog/weaveutil/db_flag.go
prog/weaveutil/main.go

Set a flag in the persistence file, so we know whether we should expect to find our name in the peer list.
Fixes #3170

weave-kube reclaim: check for upgrade case

---

site/kubernetes/kube-addon.md

* Mention `--use-legacy-netpol` flag.
* Link to NetworkPolicy from 1.7.

Update k8s netpol docs

---

router/network_router.go

 Demote messages about MAC discovery and expiry to DEBUG level

---

site/kubernetes/kube-addon.md
site/tasks/weavedns/weavedns.md

Note that WeaveDNS is disabled in Kubernetes addon

---

prog/weaver/main.go

A number of people have reporting hitting this limit, raising the limit, and seeing no ill-effects.

Raise default connection limit from 30 to 100

---

site/kubernetes/kube-addon.md

Part of #3280 
I intentionally didn't say anything about turning it on, because really the user should have a detailed discussion about the implications of turning it on, which is beyond the scope of these docs.

Add note about ip forward setting

---

site/faq.md
site/kubernetes/kube-addon.md

In my opinion the information about which port needs to be open is not very clear, so here is a little PR to try to improve that.

[Docs] Improve the installation page concerning firewall

---

Makefile

Fix manifest-tool cmd in Makefile

---

site/kubernetes/kube-addon.md

"Check it is running" and "check the logs" are important steps when troubleshooting.

Add instructions to check weave-kube logs

---

site/kubernetes/kube-addon.md

add rbac prerequisite for using weave net on GKE

---

ipam/allocator.go

prevent a case where tryOps endsup called recursivley when persisted data exists but has empty data

---

prog/weaver/checkpoint.go
prog/weaver/main.go

add checkpoint to include Kubernetes cluster information

---

proxy/proxy.go

closes #2748
First PR in weave :)

Change log-level to debug for proxy access

---

site/troubleshooting.md

thanks [Manish on Slack for noticing](https://weave-community.slack.com/archives/C2ND76PAA/p1543223957407500)

fix link to kube-addon doc

---

site/concepts/network-topology.md
site/kubernetes/kube-addon.md

document connection limit

---

README.md

https://groups.google.com/a/weave.works/forum/#!topic/weave-users/0QXWGOPdBfY

weave-users mailing list is closed

---

prog/kube-utils/main.go

Check and report the error return from getKubePeers()

---

README.md

Just updating some language that might not have been looked at in a while judging by https://github.githistory.xyz/weaveworks/weave/blob/master/README.md

small grammatical changes to readme

---

ipam/ring/entry.go
ipam/ring/ring.go

add debug log for ipam ring and entry updates

---

ipam/allocator.go

gossip broadcast updated ring on donating a range to other peer

---

README.md

add net-dev as channel to ask question regarding weave-net

---

site/overview.md

Actually Bryan answered it, when a reader of our website asked.

Answer how Weave Net works

---

site/kubernetes/kube-addon.md

Add a note on how to secure the configuration.

---

bin/provision_test_vms.sh
test/run-integration-tests.sh

Fixes #3741
Needs https://github.com/weaveworks/build-tools/pull/161 for CI to pass

upgrade to newer terraform that is compatible with google cloud API

---

common/logging.go
prog/weave-npc/main.go

Weave-npc: while logging differentiate between fatal and non-fatal errors

---

site/kubernetes/kube-addon.md

Adding the Weave-net installaton steps on EKS as noted in https://github.com/weaveworks/weave/issues/3335#issuecomment-441522517

add steps to install weave-net on EKS

---

test/840_weave_kube_3_test.sh

Allow time for network policy changes to take effect; change from waiting longer to polling until connections are established after restarting Weave Net.

Kubernetes smoke-test improvements

---

ipam/allocator.go
ipam/allocator_test.go
ipam/http.go
ipam/http_test.go
ipam/paxos/paxos_test.go
ipam/ring/ring.go
ipam/space/space_test.go
ipam/testutils_test.go
nameserver/dns_test.go
net/ipsec/ipsec.go
npc/namespace.go
npc/selector.go
plugin/skel/listener.go
prog/kube-utils/main.go
prog/kube-utils/peerlist_test.go
prog/weave-npc/main.go
proxy/common.go
router/overlay_switch.go
router/pcap.go
test/images/network-tester/webserver.go
test/tls/generate_certs.go
testing/util.go

I ran golangci-lint and it pointed out a few things to clean up.
This isn't all of them, but nothing in the remaining set looked either important or easy.

Lint cleanup

---

SECURITY.md

Per https://github.com/weaveworks/corp/issues/1780

Suspend bug bounty program
